-- @aotv4-migration
-- description: 2026_08_21_class_ability_melee_range
-- check: SELECT `range` FROM `spells_new` WHERE `id` = 44700
-- condition: missing
-- match: 25
-- shared-memory: yes
-- band:
-- author: Claude
-- notes: GENERATED by custom/tools/gen_class_abilities.py -- edit the spec there, never this file.
-- notes: Every class ability shipped at range 200, copied from the stock disciplines where it is
-- notes: harmless because those are self buffs. A TARGETED ability is range-checked against it in
-- notes: Mob::CastSpell, so the melee ones could be swung from 200 units away.
-- notes: Only the abilities whose payload actually swings are narrowed; heals, nukes, runes, pet
-- notes: summons and group buffs keep 200.

UPDATE spells_new SET `range` = 25 WHERE id IN (44700, 44702, 44703, 44706, 44708, 44709, 44710, 44711, 44712, 44713, 44714, 44715, 44718, 44720, 44721, 44723, 44724, 44726, 44730, 44733, 44736, 44742, 44744, 44745, 44746, 44747);
