-- @aotv4-migration
-- description: 2026_08_21_rogue_class_abilities
-- check: SELECT `value` FROM `db_str` WHERE `id` = 44726 AND `type` = 6
-- condition: empty
-- match:
-- shared-memory: yes
-- band:
-- author: Claude
-- notes: Rogue tier 1/2/3 as DISCIPLINES. GENERATED by custom/tools/gen_class_abilities.py --
-- notes: edit the spec there, never this file.
-- notes: Cloned via temp table from stock rows so all ~236 columns stay byte-identical.

-- ⚠️⚠️ EndurTimerIndex IS LOAD BEARING AND MUST NOT BE 0. A discipline's recast lives EXCLUSIVELY in
-- `pTimerDisciplineReuseStart + timer_id` -- CastSpell's per-spell branch is guarded by
-- `&& !spells[spell_id].is_discipline`, so pTimerSpellStart is never started for one. Tier 1 takes
-- slot 5, tier 2 slot 6, tier 3 slot 2, the SAME three slots every class uses: a character is only
-- ever one class, so nobody can hold two tier 1s, and only slots 0-10 exist against 48 abilities.
-- ⚠️ EndurCost is 1, not 0 and not the real cost. IsDiscipline requires mana = 0 AND EndurCost > 0,
-- so 0 would leave the row out of the Combat Abilities window entirely. The real level-scaled cost
-- is charged by Lua, because EndurCost is a flat int column and cannot express `N x level`.

-- ⚠️ Scoped to exactly the ids this migration creates, so a half-applied run (the check keys on the
-- LAST thing written) re-runs cleanly instead of dying on a duplicate key.
DELETE FROM spells_new WHERE id IN (44724, 44725, 44726);

DROP TEMPORARY TABLE IF EXISTS aotv4_disc_tmpl;
CREATE TEMPORARY TABLE aotv4_disc_tmpl LIKE spells_new;

-- ---------------------------------------------------------------- Vital Strike (44724)
INSERT INTO aotv4_disc_tmpl SELECT * FROM spells_new WHERE id = 4499;
UPDATE aotv4_disc_tmpl SET
    id = 44724, name = 'Vital Strike', descnum = 44724,
    EndurCost = 1, EndurTimerIndex = 5, recast_time = 10000, recovery_time = 0,
    cast_time = 0, mana = 0, skill = 98, targettype = 5, goodEffect = 0,
    new_icon = 71, spellanim = 113, CastingAnim = 44,
    -- ⚠️⚠️ `IsDiscipline` IS A COLUMN AND IT IS NOT THE SAME THING AS THE IsDiscipline() FUNCTION.
    -- The function is DERIVED (mana == 0 AND EndurCost > 0) and was true for all of these from the
    -- start; the COLUMN is spells_new field 168, loaded into spells[].is_discipline, and its own
    -- header comment is "Will goto the combat window when cast". Cloning from a template that is not
    -- a discipline leaves it 0 -- and 0 is what makes the client treat the row as a spell.
    -- ⚠️ Stock writes -1, not 1. Strings::ToBool takes any non-zero number, but match stock.
    IsDiscipline = -1,
    -- ⚠️⚠️ `player_1` IS THE PARTICLE/TRAIL GRAPHIC, AND THE INSTANT TEMPLATE CARRIES `BLUE_TRAIL`.
    -- Cloning 4667 put a blue projectile trail on every sword swing. 263 of the 281 stock
    -- disciplines are `PLAYER_1`, which is the "no special effect" value, and so is every reference
    -- spell used for the presets above -- including the nukes and heals. So it is PLAYER_1 for all
    -- of these, not just the melee ones.
    player_1 = 'PLAYER_1',
    resisttype = 0, `range` = 25, AEDuration = 0, pushback = 0, pushup = 0,
    spellgroup = 0, `rank` = 0, teleport_zone = '',
    buffduration = 4, buffdurationformula = 11,
    numhits = 0, numhitstype = 0,
    effectid1 = 3, effect_base_value1 = -35, effect_limit_value1 = 0, formula1 = 100, max1 = 0,
    effectid2 = 254, effect_base_value2 = 0, effect_limit_value2 = 0, formula2 = 100, max2 = 0,
    effectid3 = 254, effect_base_value3 = 0, effect_limit_value3 = 0, formula3 = 100, max3 = 0,
    effectid4 = 254, effect_base_value4 = 0, effect_limit_value4 = 0, formula4 = 100, max4 = 0,
    effectid5 = 254, effect_base_value5 = 0, effect_limit_value5 = 0, formula5 = 100, max5 = 0,
    effectid6 = 254, effect_base_value6 = 0, effect_limit_value6 = 0, formula6 = 100, max6 = 0,
    effectid7 = 254, effect_base_value7 = 0, effect_limit_value7 = 0, formula7 = 100, max7 = 0,
    effectid8 = 254, effect_base_value8 = 0, effect_limit_value8 = 0, formula8 = 100, max8 = 0,
    effectid9 = 254, effect_base_value9 = 0, effect_limit_value9 = 0, formula9 = 100, max9 = 0,
    effectid10 = 254, effect_base_value10 = 0, effect_limit_value10 = 0, formula10 = 100, max10 = 0,
    effectid11 = 254, effect_base_value11 = 0, effect_limit_value11 = 0, formula11 = 100, max11 = 0,
    effectid12 = 254, effect_base_value12 = 0, effect_limit_value12 = 0, formula12 = 100, max12 = 0,
    classes1 = 255, classes2 = 255, classes3 = 255, classes4 = 255,
    classes5 = 255, classes6 = 255, classes7 = 255, classes8 = 255,
    classes9 = 1, classes10 = 255, classes11 = 255, classes12 = 255,
    classes13 = 255, classes14 = 255, classes15 = 255, classes16 = 255;
INSERT INTO spells_new SELECT * FROM aotv4_disc_tmpl;
DELETE FROM aotv4_disc_tmpl;
-- ---------------------------------------------------------------- Rupture (44725)
INSERT INTO aotv4_disc_tmpl SELECT * FROM spells_new WHERE id = 4499;
UPDATE aotv4_disc_tmpl SET
    id = 44725, name = 'Rupture', descnum = 44725,
    EndurCost = 1, EndurTimerIndex = 6, recast_time = 120000, recovery_time = 0,
    cast_time = 0, mana = 0, skill = 98, targettype = 5, goodEffect = 0,
    new_icon = 72, spellanim = 113, CastingAnim = 44,
    -- ⚠️⚠️ `IsDiscipline` IS A COLUMN AND IT IS NOT THE SAME THING AS THE IsDiscipline() FUNCTION.
    -- The function is DERIVED (mana == 0 AND EndurCost > 0) and was true for all of these from the
    -- start; the COLUMN is spells_new field 168, loaded into spells[].is_discipline, and its own
    -- header comment is "Will goto the combat window when cast". Cloning from a template that is not
    -- a discipline leaves it 0 -- and 0 is what makes the client treat the row as a spell.
    -- ⚠️ Stock writes -1, not 1. Strings::ToBool takes any non-zero number, but match stock.
    IsDiscipline = -1,
    -- ⚠️⚠️ `player_1` IS THE PARTICLE/TRAIL GRAPHIC, AND THE INSTANT TEMPLATE CARRIES `BLUE_TRAIL`.
    -- Cloning 4667 put a blue projectile trail on every sword swing. 263 of the 281 stock
    -- disciplines are `PLAYER_1`, which is the "no special effect" value, and so is every reference
    -- spell used for the presets above -- including the nukes and heals. So it is PLAYER_1 for all
    -- of these, not just the melee ones.
    player_1 = 'PLAYER_1',
    resisttype = 0, `range` = 200, AEDuration = 0, pushback = 0, pushup = 0,
    spellgroup = 0, `rank` = 0, teleport_zone = '',
    buffduration = 8, buffdurationformula = 11,
    numhits = 0, numhitstype = 0,
    effectid1 = 0, effect_base_value1 = -18, effect_limit_value1 = 0, formula1 = 1, max1 = 0,
    effectid2 = 254, effect_base_value2 = 0, effect_limit_value2 = 0, formula2 = 100, max2 = 0,
    effectid3 = 254, effect_base_value3 = 0, effect_limit_value3 = 0, formula3 = 100, max3 = 0,
    effectid4 = 254, effect_base_value4 = 0, effect_limit_value4 = 0, formula4 = 100, max4 = 0,
    effectid5 = 254, effect_base_value5 = 0, effect_limit_value5 = 0, formula5 = 100, max5 = 0,
    effectid6 = 254, effect_base_value6 = 0, effect_limit_value6 = 0, formula6 = 100, max6 = 0,
    effectid7 = 254, effect_base_value7 = 0, effect_limit_value7 = 0, formula7 = 100, max7 = 0,
    effectid8 = 254, effect_base_value8 = 0, effect_limit_value8 = 0, formula8 = 100, max8 = 0,
    effectid9 = 254, effect_base_value9 = 0, effect_limit_value9 = 0, formula9 = 100, max9 = 0,
    effectid10 = 254, effect_base_value10 = 0, effect_limit_value10 = 0, formula10 = 100, max10 = 0,
    effectid11 = 254, effect_base_value11 = 0, effect_limit_value11 = 0, formula11 = 100, max11 = 0,
    effectid12 = 254, effect_base_value12 = 0, effect_limit_value12 = 0, formula12 = 100, max12 = 0,
    classes1 = 255, classes2 = 255, classes3 = 255, classes4 = 255,
    classes5 = 255, classes6 = 255, classes7 = 255, classes8 = 255,
    classes9 = 5, classes10 = 255, classes11 = 255, classes12 = 255,
    classes13 = 255, classes14 = 255, classes15 = 255, classes16 = 255;
INSERT INTO spells_new SELECT * FROM aotv4_disc_tmpl;
DELETE FROM aotv4_disc_tmpl;
-- ---------------------------------------------------------------- Exploit Weakness (44726)
INSERT INTO aotv4_disc_tmpl SELECT * FROM spells_new WHERE id = 4667;
UPDATE aotv4_disc_tmpl SET
    id = 44726, name = 'Exploit Weakness', descnum = 44726,
    EndurCost = 1, EndurTimerIndex = 2, recast_time = 15000, recovery_time = 0,
    cast_time = 0, mana = 0, skill = 98, targettype = 5, goodEffect = 0,
    new_icon = 73, spellanim = 0, CastingAnim = 44,
    -- ⚠️⚠️ `IsDiscipline` IS A COLUMN AND IT IS NOT THE SAME THING AS THE IsDiscipline() FUNCTION.
    -- The function is DERIVED (mana == 0 AND EndurCost > 0) and was true for all of these from the
    -- start; the COLUMN is spells_new field 168, loaded into spells[].is_discipline, and its own
    -- header comment is "Will goto the combat window when cast". Cloning from a template that is not
    -- a discipline leaves it 0 -- and 0 is what makes the client treat the row as a spell.
    -- ⚠️ Stock writes -1, not 1. Strings::ToBool takes any non-zero number, but match stock.
    IsDiscipline = -1,
    -- ⚠️⚠️ `player_1` IS THE PARTICLE/TRAIL GRAPHIC, AND THE INSTANT TEMPLATE CARRIES `BLUE_TRAIL`.
    -- Cloning 4667 put a blue projectile trail on every sword swing. 263 of the 281 stock
    -- disciplines are `PLAYER_1`, which is the "no special effect" value, and so is every reference
    -- spell used for the presets above -- including the nukes and heals. So it is PLAYER_1 for all
    -- of these, not just the melee ones.
    player_1 = 'PLAYER_1',
    resisttype = 0, `range` = 25, AEDuration = 0, pushback = 0, pushup = 0,
    spellgroup = 0, `rank` = 0, teleport_zone = '',
    buffduration = 0, buffdurationformula = 0,
    numhits = 0, numhitstype = 0,
    effectid1 = 254, effect_base_value1 = 0, effect_limit_value1 = 0, formula1 = 100, max1 = 0,
    effectid2 = 254, effect_base_value2 = 0, effect_limit_value2 = 0, formula2 = 100, max2 = 0,
    effectid3 = 254, effect_base_value3 = 0, effect_limit_value3 = 0, formula3 = 100, max3 = 0,
    effectid4 = 254, effect_base_value4 = 0, effect_limit_value4 = 0, formula4 = 100, max4 = 0,
    effectid5 = 254, effect_base_value5 = 0, effect_limit_value5 = 0, formula5 = 100, max5 = 0,
    effectid6 = 254, effect_base_value6 = 0, effect_limit_value6 = 0, formula6 = 100, max6 = 0,
    effectid7 = 254, effect_base_value7 = 0, effect_limit_value7 = 0, formula7 = 100, max7 = 0,
    effectid8 = 254, effect_base_value8 = 0, effect_limit_value8 = 0, formula8 = 100, max8 = 0,
    effectid9 = 254, effect_base_value9 = 0, effect_limit_value9 = 0, formula9 = 100, max9 = 0,
    effectid10 = 254, effect_base_value10 = 0, effect_limit_value10 = 0, formula10 = 100, max10 = 0,
    effectid11 = 254, effect_base_value11 = 0, effect_limit_value11 = 0, formula11 = 100, max11 = 0,
    effectid12 = 254, effect_base_value12 = 0, effect_limit_value12 = 0, formula12 = 100, max12 = 0,
    classes1 = 255, classes2 = 255, classes3 = 255, classes4 = 255,
    classes5 = 255, classes6 = 255, classes7 = 255, classes8 = 255,
    classes9 = 10, classes10 = 255, classes11 = 255, classes12 = 255,
    classes13 = 255, classes14 = 255, classes15 = 255, classes16 = 255;
INSERT INTO spells_new SELECT * FROM aotv4_disc_tmpl;
DELETE FROM aotv4_disc_tmpl;
DROP TEMPORARY TABLE IF EXISTS aotv4_disc_tmpl;

-- ---------------------------------------------------------------- descriptions
-- ⚠️⚠️ A spell with no db_str type 6 row renders BLANK and nothing errors. Written in the same
-- migration as the rows, deliberately.
-- ⚠️ The CLIENT resolves these from its own dbstr_us.txt, so this migration alone changes nothing
-- in game: it needs ./export_client_files and that file shipped to players.
DELETE FROM db_str WHERE id IN (44724, 44725, 44726) AND type = 6;
INSERT INTO db_str (id, type, value) VALUES
 (44724, 6, 'Open a leg. What you have cut cannot run.'),
 (44725, 6, 'A wound that will not close on its own.'),
 (44726, 6, 'Put a blade where it is already bleeding, for half as much again. Shortens Rupture by 5 seconds.');
