-- @aotv4-migration
-- description: 2026_08_21_class_ability_is_discipline
-- check: SELECT `IsDiscipline` FROM `spells_new` WHERE `id` = 44700
-- condition: missing
-- match: -1
-- shared-memory: yes
-- band:
-- author: Claude
-- notes: GENERATED by custom/tools/gen_class_abilities.py -- edit the spec there, never this file.
-- notes: THE COLUMN IsDiscipline IS NOT THE FUNCTION IsDiscipline(). The function is derived from
-- notes: mana and EndurCost and was always true here; the column is spells_new field 168, whose
-- notes: header comment is "Will goto the combat window when cast", and a clone inherits it from
-- notes: its template. 32 of these 51 rows were cloned from spells that are not disciplines.

UPDATE spells_new SET IsDiscipline = -1 WHERE id BETWEEN 44700 AND 44755;
