-- @aotv4-migration
-- description: 2026_08_21_class_ability_messages
-- check: SELECT `cast_on_you` FROM `spells_new` WHERE `id` = 44701
-- condition: missing
-- match: You set yourself behind your guard.
-- ⚠️⚠️ KEYED ON A MESSAGE THIS MIGRATION WRITES, NOT ON ONE IT BLANKS. The first version keyed on
-- 44700, which is a swing and is deliberately set EMPTY -- and an empty result reads back as the
-- column name rather than as an empty string, so `not_empty` was true forever and world would have
-- re-run this on every boot. The validator caught it. Test for the thing the SQL CREATES.
-- shared-memory: yes
-- band:
-- author: Claude
-- notes: GENERATED by custom/tools/gen_class_abilities.py -- edit the spec there, never this file.
-- notes: Every class-ability row was cloned from a stock spell and inherited that spell's cast
-- notes: messages, so Sanctuary announced itself as a defensive fighting style and every swing
-- notes: printed "You are hit by an invisible force." A swing is blanked on purpose: its damage
-- notes: message already says what happened.

UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44700;
UPDATE spells_new SET cast_on_you = 'You set yourself behind your guard.', cast_on_other = ' sets himself behind his guard.', spell_fades = 'Your guard drops.' WHERE id = 44701;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44702;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44703;
UPDATE spells_new SET cast_on_you = 'You are sheltered.', cast_on_other = ' is sheltered.', spell_fades = 'The shelter lifts.' WHERE id = 44704;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44705;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44706;
UPDATE spells_new SET cast_on_you = 'Conviction mends you.', cast_on_other = ' is mended by conviction.', spell_fades = '' WHERE id = 44707;
UPDATE spells_new SET cast_on_you = 'You are rebuked.', cast_on_other = ' is rebuked.', spell_fades = 'The rebuke passes.' WHERE id = 44708;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44709;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44710;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44711;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44712;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44713;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44714;
UPDATE spells_new SET cast_on_you = 'Thorns tear at you.', cast_on_other = ' is wreathed in thorns.', spell_fades = 'The thorns wither.' WHERE id = 44715;
UPDATE spells_new SET cast_on_you = 'Growth closes your wounds.', cast_on_other = ' is wreathed in growth.', spell_fades = 'The growth fades.' WHERE id = 44716;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44717;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44718;
UPDATE spells_new SET cast_on_you = 'You stand in the space between blows.', cast_on_other = ' stands very still.', spell_fades = 'Your stance breaks.' WHERE id = 44719;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44720;
UPDATE spells_new SET cast_on_you = 'Your guard falters.', cast_on_other = ' guards himself worse.', spell_fades = 'Your guard steadies.' WHERE id = 44721;
UPDATE spells_new SET cast_on_you = 'Your second wind arrives early.', cast_on_other = ' catches a second wind.', spell_fades = '' WHERE id = 44722;
UPDATE spells_new SET cast_on_you = 'You are struck on the beat.', cast_on_other = ' is struck on the beat.', spell_fades = 'The beat is lost.' WHERE id = 44723;
UPDATE spells_new SET cast_on_you = 'Your leg gives under you.', cast_on_other = ' staggers.', spell_fades = 'Your leg steadies.' WHERE id = 44724;
UPDATE spells_new SET cast_on_you = 'You are bleeding badly.', cast_on_other = ' is bleeding badly.', spell_fades = 'The bleeding stops.' WHERE id = 44725;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44726;
UPDATE spells_new SET cast_on_you = 'A ward settles over you.', cast_on_other = ' is warded.', spell_fades = 'The ward gutters out.' WHERE id = 44727;
UPDATE spells_new SET cast_on_you = 'A crippling ward settles over you.', cast_on_other = ' is warded.', spell_fades = 'The ward gutters out.' WHERE id = 44728;
UPDATE spells_new SET cast_on_you = 'Your strength deserts you.', cast_on_other = ' sags.', spell_fades = 'Your strength returns.' WHERE id = 44729;
UPDATE spells_new SET cast_on_you = 'Rot spreads through you.', cast_on_other = ' begins to rot.', spell_fades = 'The rot clears.' WHERE id = 44730;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44731;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44732;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44733;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44734;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44735;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44736;
UPDATE spells_new SET cast_on_you = 'Servants answer the call.', cast_on_other = ' calls servants.', spell_fades = '' WHERE id = 44737;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44738;
UPDATE spells_new SET cast_on_you = 'Your wards against magic thin.', cast_on_other = ' is stripped of wards.', spell_fades = 'Your wards close again.' WHERE id = 44739;
UPDATE spells_new SET cast_on_you = 'Your thoughts come back to you.', cast_on_other = ' is given back his thoughts.', spell_fades = '' WHERE id = 44740;
UPDATE spells_new SET cast_on_you = 'You fray your mind against the working.', cast_on_other = ' frays his own mind.', spell_fades = 'Your mind settles.' WHERE id = 44741;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44742;
UPDATE spells_new SET cast_on_you = 'You move faster and mend faster.', cast_on_other = ' turns feral.', spell_fades = 'The frenzy passes.' WHERE id = 44743;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44744;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44745;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44746;
UPDATE spells_new SET cast_on_you = '', cast_on_other = '', spell_fades = '' WHERE id = 44747;
UPDATE spells_new SET cast_on_you = 'The shelter blooms.', cast_on_other = ' is healed by the shelter.', spell_fades = '' WHERE id = 44750;
UPDATE spells_new SET cast_on_you = 'The cold slows you.', cast_on_other = ' slows.', spell_fades = 'The cold passes.' WHERE id = 44751;
UPDATE spells_new SET cast_on_you = 'The cold slows you.', cast_on_other = ' slows.', spell_fades = 'The cold passes.' WHERE id = 44752;
UPDATE spells_new SET cast_on_you = 'You swear the next wound to yourself.', cast_on_other = ' swears a vow.', spell_fades = 'The vow lapses.' WHERE id = 44753;
UPDATE spells_new SET cast_on_you = 'A guardian answers.', cast_on_other = ' calls a guardian.', spell_fades = '' WHERE id = 44754;
UPDATE spells_new SET cast_on_you = 'A companion answers.', cast_on_other = ' calls a companion.', spell_fades = '' WHERE id = 44755;
