-- @aotv4-migration
-- description: 2026_08_21_class_ability_particle
-- check: SELECT `player_1` FROM `spells_new` WHERE `id` = 44700
-- condition: contains
-- match: BLUE_TRAIL
-- shared-memory: yes
-- band:
-- author: Claude
-- notes: GENERATED by custom/tools/gen_class_abilities.py -- edit the spec there, never this file.
-- notes: player_1 is the particle/trail graphic. The instant template (4667 Rebuke of the Ikaav) is
-- notes: BLUE_TRAIL, so 29 of these 51 rows fired a blue projectile trail -- on sword swings. 263 of
-- notes: the 281 stock disciplines use PLAYER_1, the no-effect value, and so does every spell the
-- notes: presets were sampled from, nukes and heals included.

UPDATE spells_new SET player_1 = 'PLAYER_1' WHERE id BETWEEN 44700 AND 44755;
