-- AUTO-GENERATED by gen_pool.py -- do not hand-edit.
-- pool[learn_level] = { {id=, name=}, ... }
-- Drawn from the CUSTOM ability set (ids 43000+), not native spells:
-- spells_new joined to aotv4_spell_origin, buckets A/B, levels 1-30.
-- Helper carriers (bucket H) are excluded, so they can never be offered.
return {
	[1]={ {id=43014,name="Throw Stone"}, {id=43017,name="Languid Healing"}, {id=43028,name="Minor Regeneration"}, {id=43040,name="Brawn"}, {id=43041,name="Nimbleness"} },
	[2]={ {id=43018,name="Woodskin"}, {id=43025,name="Breeze"}, {id=43027,name="Life Ebb"}, {id=43058,name="Thorncoat"} },
	[3]={ {id=43000,name="Ember"}, {id=43031,name="Passive Protection"}, {id=43032,name="Minor Fortify Attack"}, {id=43038,name="Courage"} },
	[4]={ {id=43035,name="Blade Turn"}, {id=43039,name="Thoughfulness"}, {id=43051,name="Chi Block"} },
	[5]={ {id=43019,name="Minor Magic Barrier"}, {id=43036,name="Manatap"}, {id=43049,name="Firefist"}, {id=43084,name="Ensnare"} },
	[6]={ {id=43033,name="Concentration"}, {id=43044,name="Summon Bear"}, {id=43050,name="Inner Focus"}, {id=43057,name="Reflect"} },
	[7]={ {id=43034,name="Willpower"}, {id=43045,name="Summon Leopard"}, {id=43048,name="Summon Willowisp"}, {id=43059,name="Vengeful Aura"} },
	[8]={ {id=43001,name="Zap"}, {id=43010,name="Kick"}, {id=43016,name="Basic Healing"}, {id=43061,name="Cinder"} },
	[9]={ {id=43008,name="Frost"}, {id=43043,name="Alacrity"}, {id=43060,name="Taunt"} },
	[10]={ {id=43004,name="Poison"}, {id=43037,name="Yawn"}, {id=43046,name="Summon Skeletal Minion"}, {id=43047,name="Summon Fire Imp"} },
	[11]={ {id=43029,name="Sturdy Footing"}, {id=43042,name="Haste"}, {id=43083,name="Thorns"}, {id=43090,name="Levitate"} },
	[12]={ {id=43002,name="Smolder"}, {id=43012,name="Lifetap"}, {id=43081,name="Shielding"}, {id=43088,name="Cancel Magic"} },
	[13]={ {id=43053,name="Ambidexterous"}, {id=43078,name="Barkskin"}, {id=43089,name="Invisibility"} },
	[14]={ {id=43009,name="Chill"}, {id=43056,name="Counterattack"}, {id=43065,name="Jolt"}, {id=43086,name="Blinding Flash"} },
	[15]={ {id=43006,name="Fever"}, {id=43062,name="Scorch"}, {id=43067,name="Rime"}, {id=43087,name="Concussion"} },
	[16]={ {id=43020,name="Tepid recovery"}, {id=43073,name="Mend"}, {id=43085,name="Terror"}, {id=43104,name="Malaise"} },
	[17]={ {id=43013,name="Dread"}, {id=43072,name="Siphon Life"}, {id=43098,name="Blade Ward"} },
	[18]={ {id=43003,name="Shock"}, {id=43092,name="Bloodward"}, {id=43097,name="Mending Grace"}, {id=43106,name="Falcon Eye"} },
	[19]={ {id=43015,name="Snipe"}, {id=43026,name="Minor Manaflow"}, {id=43069,name="Venom"}, {id=43101,name="Sleetfall"} },
	[20]={ {id=43052,name="Open Wounds"}, {id=43082,name="Resist Elements"}, {id=43099,name="Stoneshield"}, {id=43102,name="Emberfall"} },
	[21]={ {id=43054,name="The Left"}, {id=43063,name="Immolate"}, {id=43105,name="Scent of Ruin"} },
	[22]={ {id=43068,name="Glacial Spike"}, {id=43080,name="Arcane Ward"}, {id=43100,name="Spellshield"}, {id=43103,name="Veil of Forgetting"} },
	[23]={ {id=43091,name="Reptile Hide"}, {id=43094,name="Adrenaline Surge"}, {id=43108,name="Mind Shatter"}, {id=43110,name="Chorus of Replenishment"} },
	[24]={ {id=43011,name="Strike"}, {id=43066,name="Arc Lightning"}, {id=43096,name="Spirit of the Lynx"}, {id=43111,name="Torrent of Misery"} },
	[25]={ {id=43064,name="Ignite Blood"}, {id=43076,name="Group Mend"}, {id=43095,name="Arcane Bulwark"}, {id=43107,name="Moonfire"} },
	[26]={ {id=43077,name="Second Wind"}, {id=43079,name="Stoneskin"}, {id=43109,name="War March"} },
	[27]={ {id=43005,name="Toxic Gas"}, {id=43071,name="Withering Curse"}, {id=43074,name="Salve"}, {id=43112,name="Bond of Xalgoz"} },
	[28]={ {id=43007,name="Infection Cloud"}, {id=43070,name="Plague"}, {id=43075,name="Renewal"}, {id=43093,name="Last Rites"} },
	[29]={ {id=43022,name="Divine Aura"}, {id=43024,name="Harm Touch"}, {id=43030,name="Duel"}, {id=43055,name="Armor Rend"} },
	[30]={ {id=43021,name="Desperate recovery"}, {id=43023,name="Lay on Hands"} },
}
