-- AoTv4 class abilities -- the shared payload behind every class's three disciplines.
--
-- ⚠️⚠️ EVERY BEHAVIOUR LIVES HERE, KEYED BY SPELL ID. The 45 files in quests/global/spells/ are
-- four-line stubs that call M.fire; they are GENERATED by custom/tools/gen_class_abilities.py along
-- with the migrations, so editing one by hand is reverted the next time that runs. 45 near-identical
-- scripts would be 45 chances for the cost model, the cooldown cut and the swing to drift apart.
--
-- ⚠️⚠️ A DISCIPLINE'S RECAST IS KEYED ON `EndurTimerIndex`, NOT ON THE SPELL ID. CastSpell's
-- per-spell branch is guarded by `&& !spells[spell_id].is_discipline`, so pTimerSpellStart is never
-- started for one. Everything below that touches a cooldown uses the TIMER id.
--
-- ⚠️⚠️ THE PAYLOAD RUNS **BEFORE** THE SPELL APPLIES ITS OWN EFFECTS. The event fires at
-- spell_effects.cpp:163 and the effect-slot loop starts at :225, so a payload never sees its own
-- SPAs land -- a pet summoned by SPA 33 does not exist yet, and a buff's stat changes have not
-- happened. ⚠️ Returning non-zero from the event CANCELS the effects outright, so no payload may
-- return a value.

local M = {}

-- Three timer slots serve all sixteen classes: a character is only ever one class, so nobody can
-- hold two tier 1s. ⚠️ Only 0-10 are valid -- 11 collides with pTimerCombatAbility (Kick/Bash).
-- ⚠️ Not sequential on purpose: 1/4/7/8/9 carry stock discs reachable at our level cap.
M.TIMER = { [1] = 5, [2] = 6, [3] = 2 }

-- Flat cost model, charged here because EndurCost cannot scale.
-- ⚠️⚠️ ONLY FOR ABILITIES THAT ARE **NOT** A SWING. Anything routed through M.weapon_blow already
-- pays section 22's charge -- 33 percent of the damage dealt -- inside DoSpecialAttackDamage, and
-- charging both bills one swing twice. Design section 2b: the two models are chosen by what the
-- ability is and are never combined. M.SPEC below records which abilities take a flat cost.
M.COST_PER_LEVEL = { [1] = 1, [2] = 5, [3] = 2 }

-- ⚠️ The resource follows the ability, not the tier: endurance for the melee classes, mana for the
-- casters, and HEALTH for the Necromancer, which is the class that should be paying in it.
-- ⚠️⚠️ A discipline CANNOT carry a mana cost on its row -- IsDiscipline is `mana = 0 AND
-- EndurCost > 0`, so a caster's cost has to be taken here or the ability stops being a discipline
-- and leaves the Combat Abilities window entirely.
M.RESOURCE = {
	[1]="end", [3]="end", [4]="end", [5]="end", [7]="end", [8]="end", [9]="end", [15]="end", [16]="end",
	[2]="mana", [6]="mana", [10]="mana", [12]="mana", [13]="mana", [14]="mana",
	[11]="hp",
}

M.BUILT = { [1]=true, [2]=true, [3]=true, [4]=true, [5]=true, [6]=true, [7]=true, [8]=true, [9]=true,
            [10]=true, [11]=true, [12]=true, [13]=true, [14]=true, [15]=true, [16]=true }
-- ⚠️⚠️ PALADIN (3) IS IN THE LIST AS OF 2026-08-21, AND ITS THREE ACTIVATED AAs MUST BE RETIRED IN
-- THE SAME DEPLOY (migration 2026_08_21_paladin_retire_aas). It was the last class on a different
-- mechanism -- one class finding its kit in the AA window while fifteen found theirs in Combat
-- Abilities -- and that inconsistency is why it was converted. Ship one without the other and a
-- Paladin holds each ability twice.

M.TIER_LEVEL = { 1, 5, 10 }

function M.spell_id(class, tier) return 44700 + (class - 1) * 3 + (tier - 1) end
function M.tier_of(spell_id)
	if spell_id < 44700 or spell_id > 44747 then return nil end
	return ((spell_id - 44700) % 3) + 1
end
function M.class_of(spell_id)
	if spell_id < 44700 or spell_id > 44747 then return nil end
	return math.floor((spell_id - 44700) / 3) + 1
end

-- ⚠️ Resolve a caster through the entity list. `e.caster_id` gives a Lua_Mob, and CharacterID is
-- only defined on Lua_Client -- calling it on a Mob is a nil-value error at runtime with nothing to
-- warn you at write time (section 24).
function M.as_client(mob)
	if not mob then return nil end
	local ent = eq.get_entity_list()
	if not ent then return nil end
	return ent:GetClientByID(mob:GetID())
end

-- ---------------------------------------------------------------------------------------------
-- Cost, refund, cooldown

function M.charge(c, tier)
	local per = M.COST_PER_LEVEL[tier]
	if not per then return true end
	local cost = per * c:GetLevel()
	local res  = M.RESOURCE[c:GetClass()] or "end"

	if res == "mana" then
		if (c:GetMana() or 0) < cost then c:Message(13, "You lack the focus.") return false end
		c:SetMana(c:GetMana() - cost)
	elseif res == "hp" then
		-- ⚠️ Paying in health must never be able to kill you: a cost that can finish you off makes
		-- the ability unusable exactly when it matters. Floor it at 1.
		if (c:GetHP() or 0) <= cost then c:Message(13, "You are too close to death.") return false end
		c:SetHP(c:GetHP() - cost)
	else
		-- ⚠️ There is no AddEndurance binding, only Get/Set, so the floor is applied by hand or a
		-- cast at an empty bar sets endurance negative.
		if (c:GetEndurance() or 0) < cost then c:Message(13, "You are too winded.") return false end
		c:SetEndurance(c:GetEndurance() - cost)
	end
	return true
end

-- ⚠️⚠️ HAND THE COOLDOWN BACK WHEN AN ABILITY REFUSES ITSELF AFTER THE CAST HAS ALREADY HAPPENED.
-- `UseDiscipline` only checks the row's EndurCost, which is a token 1 (the real cost is level-scaled
-- and paid in M.charge), and it starts the recast BEFORE the payload runs. So a player one point
-- short would otherwise land the ability, be told they cannot pay, and lose the whole cooldown for
-- nothing. Clearing the timer is the only refund path there is.
function M.refund(c, tier)
	return c:AoTv4ReduceDisciplineTimer(M.TIMER[tier], 100000)
end

-- ---------------------------------------------------------------------------------------------
-- Feedback
--
-- ⚠️⚠️ EVERY PRESS MUST SAY SOMETHING, AND THAT IS A DIAGNOSTIC REQUIREMENT AS MUCH AS A PLAYER
-- ONE. A weapon swing already prints its own damage through DoSpecialAttackDamage, but the RIDER --
-- the leech, the heal, the cooldown cut, the number of targets an AoE actually found -- was
-- invisible. So an ability that fired and found nothing looked exactly like one that never fired,
-- which is what made "Harrowing does not do an AoE lifetap" unanswerable by reading the code: the
-- payload was correct and the only way to tell was to print what it hit.
-- 📌 Chat::Yellow (15), matching the messages this module already used. Deliberately NOT
-- Chat::Skills (270) -- a player filtering skill-up spam would lose their ability feedback with it.
local MSG = 15
local said = false

function M.tell(c, text)
	said = true
	if c then c:Message(MSG, text) end
end

-- Report what a NUKE on the spell row is rated for.
-- ⚠️⚠️ THE PAYLOAD RUNS BEFORE THE SPELL RESOLVES, so the number that actually lands is not knowable
-- here -- crits, focus and the section 5 DC Overpower bonus all push it up, a partial resist pulls it
-- down. The wording therefore says "before resists" rather than claiming a result: a confident wrong
-- number is worse than none.
-- 📌 The engine sends its own "hit for N points of non-melee damage" line, but that goes out on
-- Chat::NonMelee behind the player FilterSpellDamage setting -- so it is the first thing to check when
-- spell damage seems to be missing, and it is why these abilities do not rely on it alone.
function M.tell_nuke(c, spell_id, t, label)
	local base    = math.abs(eq.get_spell_stat(spell_id, "base", 1) or 0)
	local formula = eq.get_spell_stat(spell_id, "formula", 1) or 100
	local cap     = eq.get_spell_stat(spell_id, "max", 1) or 0
	if base <= 0 then return false end
	local dmg = base
	if formula > 0 and formula < 100 then dmg = base + c:GetLevel() * formula end
	if cap > 0 and dmg > cap then dmg = cap end
	M.tell(c, string.format("%s strikes %s for %d before resists.",
		label or (eq.get_spell_name(spell_id) or "It"),
		(t and t.valid) and t:GetCleanName() or "your target", dmg))
	return true
end

-- Report what a heal over time is actually worth, at cast.
-- ⚠️⚠️ THE ENGINE'S OWN PER TICK LINE IS GATED BEHIND `Spells:HealAmountMessageFilterThreshold`,
-- WHICH IS 100 -- a live EQ number. At a level 30 cap a tick of 17 to 42 is a real heal and is
-- silently under it, so relying on HOT_HEAL_SELF would show nothing at any level this server
-- reaches. Announcing the whole thing once at cast is also better information than a per tick
-- trickle, and it costs no chat volume. Section 38 is the same trap in three other places.
-- ⚠️ Read off the ROW rather than hardcoded, so retuning the spell cannot leave this lying. Formula
-- 1-99 is `base + level * formula` and 100 is the static case (section 5); buff_duration is the tick
-- count because these rows all carry the duration as the CAP on their duration formula.
function M.tell_hot(c, spell_id)
	local base    = eq.get_spell_stat(spell_id, "base", 1) or 0
	local formula = eq.get_spell_stat(spell_id, "formula", 1) or 100
	local ticks   = eq.get_spell_stat(spell_id, "buff_duration") or 0
	if base <= 0 or ticks <= 0 then return false end
	local per = base
	if formula > 0 and formula < 100 then per = base + c:GetLevel() * formula end
	M.tell(c, string.format("%s will mend %d hit points a tick for %d ticks -- %d in all.",
		eq.get_spell_name(spell_id) or "It", per, ticks, per * ticks))
	return true
end

-- Shorten this character's tier-2 cooldown. ⚠️ Takes the TIMER id, not the spell id.
-- ⚠️ The cut is announced HERE rather than at each call site: seventeen abilities cut the tier 2
-- recast and every one of them would otherwise need its own copy of this line to drift out of step.
function M.cut_tier2(c, seconds)
	if not seconds or seconds <= 0 then return false end
	local ok = c:AoTv4ReduceDisciplineTimer(M.TIMER[2], seconds)
	if ok then
		local t2 = eq.get_spell_name(M.spell_id(c:GetClass(), 2)) or "your second ability"
		M.tell(c, string.format("%s will be ready %d seconds sooner.", t2, seconds))
	end
	return ok
end

-- ---------------------------------------------------------------------------------------------
-- Granting

-- ⚠️⚠️ THE ROGUELITE DEATH WIPES TRAINED DISCIPLINES -- death_loss calls UntrainDiscAll, and they
-- live in character_disciplines, not the spellbook. So this must run on death as well as on connect
-- and on level up, or a character comes back from every run with no class abilities at all. Class
-- AAs are permanent and need no such hook, which is why grant_class_aas has only two callers.
-- ⚠️⚠️ ALWAYS RESYNCS THE CLIENT AT THE END, EVEN WHEN IT GRANTED NOTHING.
-- The Combat Abilities window is only ever refreshed by Client::SendDisciplineUpdate, which ships the
-- WHOLE array -- and the roguelite death calls `UntrainDiscAll(false)` on purpose, which sends
-- nothing. So a path that only REMOVES disciplines left the player staring at abilities the server had
-- already taken: reported as a Shaman who died, became a Berserker, and still saw Shaman disciplines.
-- 📌 One call at the end covers every entry point at once -- connect, level up, death and the forced
-- relog after a reforge -- instead of each of them having to remember.
function M.grant(c)
	if not c then return end
	local class = c:GetClass()
	if not M.BUILT[class] then
		if c.SendDisciplineUpdate then c:SendDisciplineUpdate() end
		return
	end
	for tier = 1, 3 do
		local id = M.spell_id(class, tier)
		if c:GetLevel() >= M.TIER_LEVEL[tier] and not c:HasDisciplineLearned(id) then
			-- ⚠️ TrainDiscBySpellID validates NOTHING -- not class, not level, not whether you
			-- already know it (zone/effects.cpp:883). It fills the first empty slot, so a second
			-- call would list the same ability twice. This guard is the only thing stopping that.
			c:TrainDiscBySpellID(id)
			c:Message(15, string.format("You have learned %s.", eq.get_spell_name(id)))
		end
	end
	-- ⚠️ The resync is unconditional: it must fire even when nothing was trained, because the case
	-- that needed fixing is exactly "the server removed abilities and added none back".
	if c.SendDisciplineUpdate then c:SendDisciplineUpdate() end
end

-- ---------------------------------------------------------------------------------------------
-- The shared swing
--
-- ⚠️⚠️ ROUTE EVERY BLOW THROUGH DoSpecialAttackDamage. It is the choke point Kick, Bash, Frenzy and
-- the monk strikes all use, so the blow inherits mitigation, avoidance, the damage packet, skill
-- procs and section 22's damage-proportional endurance charge. Rolling damage by hand inherits none.
-- ⚠️⚠️ IT TAKES AT MOST SIX ARGUMENTS (other, skill, base_damage, min_damage, hate_override,
-- reuse_seconds). A seventh matches no overload and is a luabind error at runtime.
-- ⚠️⚠️ THE SKILL IS THE EQUIPPED WEAPON'S OWN SKILL. `my_hit.offense` and `GetTotalToHit` are both
-- computed from the skill argument (special_attacks.cpp:296), and on this server a character may
-- genuinely have 0 in a special's skill (section 4: a cap exists for every class, the VALUE is only
-- granted if native or picked). Naming an untrained skill quietly wrecks the to-hit roll, and it
-- makes the client's damage message read as that special rather than as a weapon hit.
local SKILL_OF_ITEMTYPE = {
	[0]  = 1,    -- 1H Slash    -> Skill1HSlashing
	[1]  = 3,    -- 2H Slash    -> Skill2HSlashing
	[2]  = 36,   -- 1H Pierce   -> Skill1HPiercing
	[3]  = 0,    -- 1H Blunt    -> Skill1HBlunt
	[4]  = 2,    -- 2H Blunt    -> Skill2HBlunt
	[35] = 77,   -- 2H Pierce   -> Skill2HPiercing
}
local SKILL_HAND_TO_HAND = 28
local SKILL_ARCHERY      = 7
local SLOT_PRIMARY       = 13
local SLOT_RANGE         = 11
local ITEMTYPE_BOW       = 5

-- Returns skill, base_damage, delay for whatever is in the primary slot.
-- ⚠️ GetItemIDAt returns INVALID_ID (-1) for an empty slot, NOT 0.
function M.weapon_profile(c)
	local id = c:GetItemIDAt(SLOT_PRIMARY)
	if not id or id <= 0 then
		return SKILL_HAND_TO_HAND, math.max(1, math.floor(c:GetLevel() / 2)), 36
	end
	local itemtype = eq.get_item_stat(id, "itemtype") or -1
	local dmg      = eq.get_item_stat(id, "damage") or 0
	local delay    = eq.get_item_stat(id, "delay") or 36
	-- 📌 Reading the ITEM ID means gear tiers are already counted: a Hallowed or Mythic copy is its
	-- own row with its own damage column (section 10), so nothing here has to know tiers exist.
	return SKILL_OF_ITEMTYPE[itemtype] or SKILL_HAND_TO_HAND,
	       math.max(1, dmg + math.floor(c:GetLevel() / 2)), math.max(1, delay)
end

function M.has_bow(c)
	local id = c:GetItemIDAt(SLOT_RANGE)
	if not id or id <= 0 then return false end
	return (eq.get_item_stat(id, "itemtype") or -1) == ITEMTYPE_BOW
end

-- 📌 Damage is `weapon damage + level/2`, about twice a Frenzy swing (Frenzy is weapon damage / 2,
-- special_attacks.cpp:70). First-pass tuning; `mult` lets one ability hit harder than another
-- without every payload re-deriving the formula.
-- ⚠️ hate_override is passed as -1 ("use the damage") rather than a number, because
-- `AoT:SpecialBonusThreat` overwrites it for every non-Bash special anyway (special_attacks.cpp:293).
-- An ability that wants threat adds it EXPLICITLY afterwards.
function M.weapon_blow(c, target, reuse_seconds, mult, skill_override)
	if not c or not target or not target.valid then return false end
	local skill, base = M.weapon_profile(c)
	base = math.max(1, math.floor(base * (mult or 1.0)))
	local used = skill_override or skill

	-- Tag the swing so floating combat text can colour it as an ABILITY rather than an autoattack.
	-- ⚠⚠ THIS HAS TO BE DONE HERE BECAUSE NOTHING DOWNSTREAM CAN TELL. These abilities swing with
	-- the WEAPON's own skill (weapon_profile above), not with Bash or Kick, so by the time the damage
	-- reaches Mob::CommonDamage a Reckless Cleave is byte for byte an ordinary 2H Slashing hit -- same
	-- skill, same path, same message. It was reported from play as the ability "not showing up" when in
	-- fact it was showing, in the same white as every autoattack around it.
	-- 📌 An entity variable rather than a new binding: SetEntityVariable is already bound and the
	-- server clears this the moment it consumes it. WHICH ability it was comes from `aotv4_fct_ability`,
	-- set once per press in M.fire -- this one is a per-SWING flag, because an ability like Frenzied
	-- Onslaught lands five separate blows and each has to be tagged on its own.
	c:SetEntityVariable("aotv4_fct_swing", "1")
	c:DoSpecialAttackDamage(target, used, base, 1, -1, reuse_seconds or 0)
	-- ⚠️⚠️ DoSpecialAttackDamage DOES NOT TRAIN THE SKILL -- it contains no CheckIncreaseSkill at all.
	-- Every stock special calls it separately AFTER the damage (Bash at special_attacks.cpp:533,
	-- Frenzy :563, Kick :696, Backstab :899), which is easy to miss because the call sites look like
	-- part of the special rather than part of the swing. Without this these abilities are the only
	-- melee attacks in the game that never raise the weapon skill they use.
	-- 📌 chance_mod 10, matching every stock special.
	c:CheckIncreaseSkill(used, target, 10)
	return true
end

-- ⚠️⚠️ AN AoE MUST NOT PICK ITS TARGETS BY PROXIMITY ALONE. IsAttackAllowed says the banker behind
-- your target CAN be hit, not that it should be, and one cleave through a town is a KOS faction hit
-- nobody asked for (section 28). Every sweep is limited to the creature you are actually fighting
-- and anything already holding you on its hate list.
-- ⚠️ `for m in list.entries do` -- a Lua_NPC_List is NOT an array, so ipairs() yields nothing.
-- ⚠️ `frontal` uses `not BehindMob`, a 180 degree arc: Mob::InFrontMob (the 56 degree one) HAS NO
-- LUA BINDING on this build. MobAngle reads the HEADING OF THE ARGUMENT and the position passed in,
-- so the caster must be the argument and the creature's own coordinates the point.
function M.sweep(c, range, frontal)
	local out = {}
	local tgt = c:GetTarget()
	local list = eq.get_entity_list():GetNPCList()
	for m in list.entries do
		if m and m.valid and m:GetHP() > 0 and c:IsAttackAllowed(m)
		   and (m:CheckAggro(c) or (tgt and tgt.valid and m:GetID() == tgt:GetID()))
		   and c:CalculateDistance(m:GetX(), m:GetY(), m:GetZ()) <= range
		   and ((not frontal) or (not m:BehindMob(c, m:GetX(), m:GetY()))) then
			out[#out + 1] = m
		end
	end
	return out
end

-- ---------------------------------------------------------------------------------------------
-- Pets -- Magician and Beastlord
--
-- ⚠️⚠️ THE ABILITY GRANTS THE PET RATHER THAN DEPENDING ON ONE. Pets normally come from spells, and
-- on a random-progression server a Magician may simply never be offered one -- an ability that waits
-- on a random reward is not an ability.
-- ⚠️⚠️ A PET'S STATS ARE FROZEN AT SUMMON (Mob::MakePet, pets.cpp:140), which is the same reason
-- SPA 213 PetMaxHP does nothing to a pet you already have. "Levels with you" therefore has to be a
-- rescale, and it is applied here on every press and from global_player on every level up.
-- ⚠️ SpellFinished, NOT CastSpell: the helper rows are classes 255 for everyone (they are cast BY
-- something, never by a player), so a real cast would be refused on the class gate.
function M.ensure_pet(c, pet_spell)
	local p = c:GetPet()
	if p and p.valid then M.rescale_pet(c) return false end
	c:SpellFinished(pet_spell, c)
	return true
end

function M.rescale_pet(c)
	local p = c:GetPet()
	if not p or not p.valid then return end
	local lvl = c:GetLevel()
	if p:GetLevel() == lvl then return end          -- deadband: nothing to do on most presses
	local n = p:CastToNPC()
	if not n then return end
	-- ⚠️ ModifyNPCStat takes STRINGS, and ScaleNPC is deliberately NOT used: it rewrites the stat
	-- block wholesale from npc_scale_global_base and would throw away everything set here.
	n:ModifyNPCStat("level",   tostring(lvl))
	n:ModifyNPCStat("max_hp",  tostring(40 * lvl))
	n:ModifyNPCStat("min_hit", tostring(lvl))
	n:ModifyNPCStat("max_hit", tostring(lvl * 3))
	n:ModifyNPCStat("ac",      tostring(lvl * 4))
	n:ModifyNPCStat("atk",     tostring(lvl * 5))
	-- ⚠️ max_hp clamps DOWN only -- raising the maximum does not raise current health, so without
	-- this the pet levels up and stays wounded.
	p:SetHP(p:GetMaxHP())
end

-- ---------------------------------------------------------------------------------------------
-- Warrior tier 2 -- Bulwark. The absorb is paid here because SPA 162's per-hit cap is a fixed
-- number on the spell row and this one is `AC / 10`, which is per character and per moment.
--
-- ⚠️⚠️ THE CHARGES ARE COUNTED HERE, NOT BY THE ENGINE, AND THAT IS NOT A PREFERENCE.
-- `numhits`/`numhitstype 6` would give a free client-side counter, but the engine spends the last
-- charge and FADES THE BUFF in CheckNumHitsRemaining (attack.cpp:4621) -- which runs BEFORE
-- EVENT_DAMAGE_TAKEN (attack.cpp:4689) in the same Mob::CommonDamage call. So on the fifth hit the
-- payload would find no buff and absorb nothing: an ability that advertises five absorbs and
-- delivers four, silently. **Any Lua-paid charge effect has this problem; count it yourself.**
local BULWARK_SPELL   = 44701
local BULWARK_CHARGES = 5
local BULWARK_VAR     = "aotv4_bulwark"

-- ⚠️⚠️ THIS RUNS ON EVERY DAMAGE EVENT FOR EVERY PLAYER. The arithmetic early-outs come first,
-- before the entity-variable lookup and long before FindBuff walks the buff slots (section 5).
-- ⚠️⚠️ THE RETURN VALUE IS A DAMAGE OVERRIDE: positive REPLACES the damage, negative NEGATES the
-- hit, and nil leaves it alone (attack.cpp:4706). Reducing a blow to exactly nothing therefore means
-- returning a negative, not returning 0.
function M.on_damage_taken(e)
	local dmg = e.damage or 0
	if dmg <= 0 then return end
	-- Melee only: Mob::Damage defaults spell_id to SPELL_UNKNOWN, so a swing carries 0 or 65535.
	if not (e.spell_id == 0 or e.spell_id == 65535) then return end

	local c = e.self
	if not c or not c.valid or not c:IsClient() then return end

	local left = tonumber(c:GetEntityVariable(BULWARK_VAR) or "") or 0
	if left <= 0 then return end

	-- ⚠️ The counter is an ENTITY variable, so it does not survive zoning while the buff does. The
	-- buff is the authority on whether the ability is still up: no buff means the count is stale.
	if not c:FindBuff(BULWARK_SPELL) then
		c:SetEntityVariable(BULWARK_VAR, "0")
		return
	end

	local absorb = math.floor((c:GetAC() or 0) / 10)
	if absorb < 1 then absorb = 1 end

	left = left - 1
	c:SetEntityVariable(BULWARK_VAR, tostring(left))
	if left <= 0 then
		c:BuffFadeBySpellID(BULWARK_SPELL)
		c:Message(15, "Your bulwark is spent.")
	end

	if absorb >= dmg then return -1 end
	return dmg - absorb
end

-- ---------------------------------------------------------------------------------------------
-- Wizard Ley Tap stacks, counted the same way and for the same reason.
-- ⚠️⚠️ THE BUFFS ARE THE STATE. Ley Tap used to bank its count in an entity variable, which meant
-- nothing appeared on the buff bar at all -- reported as "not providing a visible buff for Overload".
-- A buff row cannot display a number, so the count is encoded in WHICH row is up (the section 17b
-- Shield Wall pattern, three rows for three counts).
-- ⚠️ Reading the count back off the buffs, rather than keeping a variable beside them, is the whole
-- point: a variable plus a buff is two sources of truth and they drift the moment one expires and the
-- other does not. There is nothing left to desync.
local LEYTAP_MAX  = 3
local LEYTAP_BUFF = { 44756, 44757, 44758 }   -- 1, 2, 3 threads

local function ley_stacks(c)
	for n = LEYTAP_MAX, 1, -1 do
		if c:FindBuff(LEYTAP_BUFF[n]) then return n end
	end
	return 0
end

local function ley_set(c, n)
	for _, id in ipairs(LEYTAP_BUFF) do c:BuffFadeBySpellID(id) end
	if n > 0 then c:ApplySpellBuff(LEYTAP_BUFF[n]) end
end

-- ---------------------------------------------------------------------------------------------
-- SPEC: what M.fire does for an ability before its payload runs.
--   cost = the tier whose flat cost this ability pays, or nil for a swing (which pays section 22)
--   buff = a self buff, so a refused cost must fade it as well as refund the cooldown
local S = function(cost, buff) return { cost = cost, buff = buff } end
M.SPEC = {
	-- Warrior
	[44700]=S(nil), [44701]=S(2,true), [44702]=S(nil),
	-- Paladin (tiers 1 and 3 are swings, so only the heal takes a flat cost)
	[44706]=S(nil), [44707]=S(2), [44708]=S(nil),
	-- Cleric            Ranger              Shadowknight
	[44703]=S(nil), [44704]=S(2), [44705]=S(3),
	[44709]=S(nil), [44710]=S(nil), [44711]=S(nil),
	[44712]=S(nil), [44713]=S(nil), [44714]=S(nil),
	-- Druid
	[44715]=S(nil), [44716]=S(2), [44717]=S(3),
	-- Monk
	[44718]=S(nil), [44719]=S(2,true), [44720]=S(nil),
	-- Bard
	[44721]=S(nil), [44722]=S(2), [44723]=S(nil),
	-- Rogue
	[44724]=S(nil), [44725]=S(2), [44726]=S(nil),
	-- Shaman
	[44727]=S(1), [44728]=S(2), [44729]=S(3),
	-- Necromancer
	[44730]=S(nil), [44731]=S(2), [44732]=S(3),
	-- Wizard
	[44733]=S(nil), [44734]=S(2), [44735]=S(3),
	-- Magician
	[44736]=S(nil), [44737]=S(2,true), [44738]=S(3),
	-- Enchanter (tier 1 is Tashania, the one tier 1 that is not a swing)
	[44739]=S(1), [44740]=S(2), [44741]=S(3,true),
	-- Beastlord
	[44742]=S(nil), [44743]=S(2,true), [44744]=S(nil),
	-- Berserker
	[44745]=S(nil), [44746]=S(2), [44747]=S(nil),
}

-- ---------------------------------------------------------------------------------------------
-- NOTE: the line printed for an ability whose spell ROW does everything, so it has no payload below
-- and would otherwise be the only kind of ability that says nothing at all when pressed.
-- ⚠️ Keep this in step with the payload table: an id with neither an entry here nor a payload falls
-- back to a bare "You use X", which is not wrong but tells the player nothing.
M.NOTE = {
	[44704] = "You raise a sanctuary over your group.",
	[44722] = "Your crescendo restores your group's endurance.",
	[44725] = "You rupture your target. It will bleed.",
	[44727] = "You weave a foresight rune. Anything striking through it is slowed.",
	[44728] = "You wrap your group in crippling spirits.",
	[44737] = "An elemental swarm answers your call.",
	[44739] = "Tashania strips your target's resistances.",
	[44740] = "You gift your group clearer thought.",
}

-- ---------------------------------------------------------------------------------------------
-- PAYLOAD: everything an ability does beyond its own spell effects. Nil = the row does it all.
local P = {}
M.PAYLOAD = P

-- ============================================================== 1 WARRIOR
P[44700] = function(c, t)                                    -- Cleaving Blow
	if not M.weapon_blow(c, t, 10) then return end
	-- Threat is added EXPLICITLY: AoT:SpecialBonusThreat floors the bonus hate of every non-Bash
	-- special to a token 1 inside DoSpecialAttackDamage, so a hate_override would be overwritten.
	t:AddToHateList(c, c:GetLevel() * 6)
	M.tell(c, string.format("Your cleave seizes %s's attention.", t:GetCleanName()))
end
P[44701] = function(c)                                       -- Bulwark
	c:SetEntityVariable(BULWARK_VAR, tostring(BULWARK_CHARGES))
	M.tell(c, string.format("You set yourself behind your guard, turning aside the next %d attacks.",
		BULWARK_CHARGES))
end
P[44702] = function(c)                                       -- Broad Cleave
	local hit = M.sweep(c, 30, true)
	for _, m in ipairs(hit) do
		-- ⚠️⚠️ NO AddToHateList HERE, DELIBERATELY. An AoE that pulls everything you were not
		-- fighting is the exact "spamming it is both optimal and wrong" trap the tier 3 rule exists
		-- to avoid. The damage still generates ordinary threat inside Mob::Damage.
		M.weapon_blow(c, m, 15)
	end
	-- ⚠️⚠️ THE CUT IS EARNED BY HITTING SOMETHING, NOT BY PRESSING THE BUTTON.
	if #hit > 0 then
		M.tell(c, string.format("Your cleave sweeps through %d foes.", #hit))
		M.cut_tier2(c, math.min(#hit * 3, 9))
	else
		M.tell(c, "Your cleave finds nothing in front of you.")
	end
end

-- ============================================================== 2 CLERIC
P[44703] = function(c, t)                                    -- Templar Strike
	if not M.weapon_blow(c, t, 10) then return end
	-- ⚠️ DoSpecialAttackDamage returns void, so the damage actually dealt is unknowable from Lua.
	-- Every "a share of the damage" rider in this file is therefore a LEVEL-scaled flat amount.
	local mend = c:GetLevel() * 2
	c:HealDamage(mend, c)
	M.tell(c, string.format("Your templar strike mends you for %d hit points.", mend))
end
P[44705] = function(c, t)                                    -- Condemn
	-- bodytype 3 is Undead. The nuke itself is on the spell row; this is only the cut.
	local undead = t and t:GetBodyType() == 3
	M.tell_nuke(c, 44705, t, "Condemn")
	if undead then M.tell(c, "The undead burn for it.") end
	M.cut_tier2(c, undead and 10 or 5)
end

-- ============================================================== 3 PALADIN
-- Ported from lua_modules/aotv4_paladin.lua, which drove the retired AA versions. Only the delivery
-- changed; the tuning and the reasons for it are unchanged.
-- ⚠️⚠️ ALL THREE EFFECTS ARE HERE RATHER THAN ON THE ROW BECAUSE NONE CAN BE EXPRESSED IN
-- `spells_new`: Ardent Strike scales with STRENGTH (no SPA reads a caster stat as its magnitude),
-- Hand of Conviction heals a percentage of the CASTER's max HP (SPA 147 is a percentage of the
-- TARGET's, a different spell entirely), and the cooldown cut reaches a recast timer, which nothing
-- in the spell system does.
local PAL_PER_LEVEL, PAL_PER_STR = 1, 0.10
local PAL_CONVICTION_PCT = 0.25

P[44706] = function(c, t)                                    -- Ardent Strike
	-- ⚠️ Deliberately WEAKER than Cleaving Blow (0.8): the Paladin trades swing damage for the heal
	-- and the taunt. It goes through the same M.weapon_blow as every other tier 1.
	if not M.weapon_blow(c, t, 10, 0.8) then return end
	-- ⚠️ KEEP THE BONUS SMALL. It is unmitigated -- Mob::Damage does NOT run MeleeMitigation, that
	-- lives in Mob::Attack -- so every point is a point the target cannot reduce. An earlier version
	-- computed max(level*3, STR*0.75) and applied it this way, which read as ~150 at level 15 and was
	-- reported from play as hitting far too hard.
	-- ⚠️ Both halves are needed: Strength alone is useless at level 1 (a naked character's STR does
	-- not rise with level -- stats come entirely from gear here), and a level floor alone would make
	-- Strength pointless forever.
	local bonus = math.max(c:GetLevel() * PAL_PER_LEVEL, math.floor((c:GetSTR() or 0) * PAL_PER_STR))
	if bonus > 0 then
		-- ⚠️ spell_id 0, not the ability id: passing it would report this as MAGIC damage and let
		-- spell-damage modifiers touch it. This is the divine part of a weapon blow.
		t:Damage(c, bonus, 0, 10, false)
	end
	t:AddToHateList(c, c:GetLevel() * 8)
	M.tell(c, string.format("Your ardent strike sears %s for %d and holds its attention.",
		t:GetCleanName(), bonus))
end

P[44707] = function(c)                                       -- Hand of Conviction
	local amount = math.floor((c:GetMaxHP() or 0) * PAL_CONVICTION_PCT)
	if amount <= 0 then return end

	local grp = c:GetGroup()
	if not grp or not grp.valid then
		-- Solo heals the Paladin. An ability worth nothing without a group would be dead weight for
		-- most of a run, and soloing is normal here.
		c:HealDamage(amount, c)
		M.tell(c, string.format("Your conviction restores %d hit points.", amount))
		return
	end

	-- ⚠️ GetMember hands back a Lua_Mob and only members IN THIS ZONE resolve through the entity
	-- list. A member elsewhere is simply not healed; there is no cross-zone heal.
	local healed = 0
	for i = 0, (grp:GroupCount() or 0) - 1 do
		local m = grp:GetMember(i)
		if m and m.valid then
			local mc = eq.get_entity_list():GetClientByID(m:GetID())
			if mc and mc.valid then
				mc:HealDamage(amount, c)
				healed = healed + 1
			end
		end
	end
	M.tell(c, string.format("Your conviction restores %d hit points to %d in your group.",
		amount, healed))
end

P[44708] = function(c, t)                                    -- Divine Reproach
	-- ⚠️ The stun is the row's own SPA 21, so the engine owns resist, immunity and the message.
	-- 📌 The design asks for the cut "only if the stun lands", and that is NOT observable here: the
	-- payload runs BEFORE the spell applies its own effects, so the stun has not been rolled yet.
	-- Same limitation as the Monk's crit-doubled cut. It cuts on a landed swing instead.
	if not M.weapon_blow(c, t, 15) then return end
	t:AddToHateList(c, c:GetLevel() * 6)
	M.tell(c, string.format("Your reproach rebukes %s.", t:GetCleanName()))
	M.cut_tier2(c, 5)
end

-- ============================================================== 4 RANGER
P[44709] = function(c, t)                                    -- Twin Slash
	M.weapon_blow(c, t, 10, 0.6)
	M.weapon_blow(c, t, 10, 0.6)
	M.tell(c, string.format("You slash %s twice.", t and t:GetCleanName() or "your target"))
end
P[44710] = function(c)                                       -- Volley
	local hit = M.sweep(c, 60, true)
	for _, m in ipairs(hit) do
		M.weapon_blow(c, m, 120, 0.8, SKILL_ARCHERY)
	end
	M.tell(c, #hit > 0
		and string.format("Your volley falls on %d foes.", #hit)
		or "Your volley finds no mark.")
end
P[44711] = function(c, t)                                    -- Point Blank Shot
	if M.has_bow(c) then
		-- ⚠️ RangedAttack needs a bow AND ammunition; with either missing it simply does nothing,
		-- which is why the fallback below exists rather than a bare refusal.
		c:RangedAttack(t)
		M.tell(c, "You loose an arrow at point blank range.")
		M.cut_tier2(c, 10)
	else
		M.weapon_blow(c, t, 15, 1.2)
		M.tell(c, "With no bow to hand, you drive the blow home instead.")
		M.cut_tier2(c, 5)
	end
end

-- ============================================================== 5 SHADOWKNIGHT
local SK_VOW = 44753
P[44712] = function(c, t)                                    -- Reaving Strike
	if not M.weapon_blow(c, t, 10) then return end
	local leech = c:GetLevel() * 2
	local vowed = c:FindBuff(SK_VOW)
	if vowed then
		leech = leech * 2
		c:BuffFadeBySpellID(SK_VOW)          -- the vow is spent on one strike, as promised
	end
	c:HealDamage(leech, c)
	M.tell(c, string.format("Your reaving strike drains %d life%s.", leech,
		vowed and ", your vow spent" or ""))
end
P[44713] = function(c)                                       -- Harrowing
	-- ⚠️⚠️ THE SWEEP ONLY TAKES CREATURES ALREADY FIGHTING YOU, plus your current target. That is
	-- the section 2 rule every AoE here obeys, and it means Harrowing on a lone target is a single
	-- drain by design rather than a broken AoE. Reported from play as "does not do an AoE lifetap";
	-- the payload was correct and there was simply nothing on screen saying how many it had found.
	local hit = M.sweep(c, 40, false)
	for _, m in ipairs(hit) do M.weapon_blow(c, m, 120, 0.7) end
	if #hit > 0 then
		local leech = #hit * c:GetLevel() * 2
		c:HealDamage(leech, c)
		M.tell(c, string.format("Your harrowing tears through %d %s, draining %d life.",
			#hit, #hit == 1 and "foe" or "foes", leech))
	else
		M.tell(c, "Your harrowing finds nothing fighting you.")
	end
end
P[44714] = function(c, t)                                    -- Reaving Vow
	if not M.weapon_blow(c, t, 15) then return end
	c:ApplySpellBuff(SK_VOW)
	M.tell(c, "You swear a reaving vow. Your next reaving strike drains double.")
	M.cut_tier2(c, 6)
end

-- ============================================================== 6 DRUID
P[44716] = function(c, t)                                    -- Wildgrowth (SPA 100 is on the row)
	if not M.tell_hot(c, 44716) then
		M.tell(c, "Wildgrowth takes root, mending over time.")
	end
	if t and t.valid and t:GetID() ~= c:GetID() then
		M.tell(c, string.format("It takes root in %s.", t:GetCleanName()))
	end
end
P[44715] = function(c, t)                                    -- Thorned Strike (SPA 121 is on the row)
	if not M.weapon_blow(c, t, 10) then return end
	M.tell(c, string.format("Thorns wreathe %s. It will wound itself on every blow it lands.",
		t:GetCleanName()))
end
P[44717] = function(c, t)                                    -- Sunflare
	-- ⚠️ There is no "is it standing still" test in the engine, so stationary means ROOTED, MEZZED,
	-- STUNNED or carrying our own snare -- the whole definition, deliberately.
	local held = t and (t:IsRooted() or t:IsMezzed() or t:IsStunned() or t:FindBuff(44724))
	M.tell_nuke(c, 44717, t, "Sunflare")
	if held then
		local bonus = c:GetLevel() * 6
		t:Damage(c, bonus, 44717, 24, false)
		M.tell(c, string.format("Your sunflare catches %s helpless, searing it for %d more.",
			t:GetCleanName(), bonus))
		M.cut_tier2(c, 10)
	else
		M.tell(c, "Your sunflare blazes, but your target is not held fast.")
		M.cut_tier2(c, 5)
	end
end

-- ============================================================== 7 MONK
P[44718] = function(c, t)                                    -- Iron Palm
	-- Design formula: delay x (0.2 + level x 0.035), which is what makes a slow weapon worth more
	-- to a Monk than a fast one.
	local _, _, delay = M.weapon_profile(c)
	local dmg = math.max(1, math.floor(delay * (0.2 + c:GetLevel() * 0.035)))
	c:DoSpecialAttackDamage(t, SKILL_HAND_TO_HAND, dmg, 1, -1, 10)
	c:CheckIncreaseSkill(SKILL_HAND_TO_HAND, t, 10)
	M.tell(c, string.format("Your iron palm lands with the weight of your weapon (%d).", dmg))
end
-- ⚠️ Charge count mirrors `numhits` on the 44719 row (migration 2026_08_22_void_stance_charges).
-- There is no get_spell_stat key for numhits, so this is the one number that cannot be read back --
-- same "the SQL is documentation, this table pays" arrangement aotv4_thirst.lua uses. Change one and
-- change the other.
local VOID_CHARGES = 4
P[44719] = function(c)                                       -- Void Stance (SPA 172 is on the row)
	-- ⚠️⚠️ SAY WHAT IT DOES IN NUMBERS. A pure chance modifier with no message and no visible tell is
	-- indistinguishable from an ability that does nothing -- which is exactly how this was reported.
	-- The magnitude is read off the row so retuning the spell cannot leave this line lying.
	local pct = eq.get_spell_stat(44719, "base", 1) or 0
	if pct > 0 then
		M.tell(c, string.format(
			"You settle into a void stance: %d percent harder to hit until %d blows land.",
			pct, VOID_CHARGES))
	else
		M.tell(c, "You settle into a void stance.")
	end
end
P[44720] = function(c, t)                                    -- Pressure Point
	if not M.weapon_blow(c, t, 15, 1.6) then return end
	t:AddToHateList(c, c:GetLevel() * 4)
	M.tell(c, string.format("You strike a pressure point on %s.", t:GetCleanName()))
	-- 📌 The design asked for a doubled cut on a CRIT. DoSpecialAttackDamage returns void, so
	-- whether the blow critted is not knowable from Lua -- the cut is a flat 6 until that is.
	M.cut_tier2(c, 6)
end

-- ============================================================== 8 BARD
-- ⚠️ Mirrors `numhits` on the 44723 row. `get_spell_stat` has no key for numhits, so this is the one
-- number that cannot be read back -- same arrangement as VOID_CHARGES and aotv4_thirst.lua's table.
local CADENCE_HITS = 5
-- ⚠️⚠️ SPA 1 `ArmorClass` IS **FLAT**, NOT A PERCENTAGE. `bonuses.cpp:649` is `newbon->AC +=
-- base_value` -- there is no percentage form of it. The design doc asserted the opposite and sized
-- the row against "15 percent of target AC" (23 on an average mob, 79 on a 529 AC elite); what
-- actually ships is a flat 25 everywhere, which happens to hit the average and under-delivers badly
-- on the elites the debuff is for. Corrected in CLASS_ABILITIES_DESIGN.md rather than papered over.
-- 📌 It IS applied: the cached `mitigation_ac` is recomputed because applying a buff calls
-- CalcBonuses, which calls CalcAC (bonuses.cpp:38). The problem was never that it did nothing -- it
-- is that nothing said what it did.
P[44721] = function(c, t)                                    -- Discordant Strike (SPA 1 is on the row)
	if not M.weapon_blow(c, t, 10) then return end
	local ac = math.abs(eq.get_spell_stat(44721, "base", 1) or 0)
	M.tell(c, ac > 0
		and string.format("Discord strips %d armor from %s.", ac, t:GetCleanName())
		or string.format("Discord rattles %s.", t:GetCleanName()))
end
P[44723] = function(c, t)                                    -- Cadence Strike
	-- 📌 GetInstrumentMod is Bard-only and is NOT Lua-bound, so "instrument scaled" is expressed as
	-- a flat bonus for holding one rather than as the real multiplier.
	local mult = 1.2
	local rng = c:GetItemIDAt(SLOT_RANGE)
	if rng and rng > 0 then
		local it = eq.get_item_stat(rng, "itemtype") or -1
		if it >= 23 and it <= 26 then mult = 1.5 end     -- 23-26 are the instrument item types
	end
	if not M.weapon_blow(c, t, 15, mult) then return end
	M.tell(c, mult > 1.2
		and "Your cadence rings through your instrument."
		or "Your cadence strikes true, though you carry no instrument.")
	-- ⚠️ SPA 197 SkillDamageTaken with limit -1 (ALL_SKILLS): a POSITIVE base is +damage taken
	-- (`hit.damage_done += hit.damage_done * pct / 100`, attack.cpp:7000), and the charge is spent on
	-- the TARGET's incoming hits (numhitstype 6). All correct -- and entirely invisible, which is how
	-- it came to be reported as doing nothing.
	local pct = eq.get_spell_stat(44723, "base", 1) or 0
	if pct > 0 and t and t.valid then
		M.tell(c, string.format("%s will take %d percent more melee damage for the next %d hits.",
			t:GetCleanName(), pct, CADENCE_HITS))
	end
	M.cut_tier2(c, 5)
end

-- ============================================================== 9 ROGUE
P[44724] = function(c, t)                                    -- Vital Strike (SPA 3 snare is on the row)
	if not M.weapon_blow(c, t, 10) then return end
	M.tell(c, string.format("Your vital strike hobbles %s.", t:GetCleanName()))
end
P[44726] = function(c, t)                                    -- Exploit Weakness
	local bleeding = t and t:FindBuff(44725)
	if not M.weapon_blow(c, t, 15, bleeding and 1.5 or 1.0) then return end
	M.tell(c, bleeding
		and "You exploit the wound you opened, striking half again as hard."
		or "You find no open wound to exploit.")
	M.cut_tier2(c, 5)
end

-- ============================================================== 10 SHAMAN
P[44729] = function(c, t)                                    -- Malaise
	local slowed = t and (t:FindBuff(44751) or t:FindBuff(44752))
	M.tell(c, slowed
		and "Your malaise settles deep into an already sluggish foe."
		or "Your malaise saps your target.")
	M.cut_tier2(c, slowed and 10 or 5)
end

-- ============================================================== 11 NECROMANCER
P[44730] = function(c, t)                                    -- Withering Touch (the DoT is on the row)
	if not M.weapon_blow(c, t, 10) then return end
	M.tell(c, string.format("Your touch withers %s.", t:GetCleanName()))
end

-- ⚠️⚠️ REMAINING DoT DAMAGE IS NOW REAL, NOT A GUESS. This used to say ticsremaining "has no
-- binding" and assumed a flat THREE ticks per affliction, so a DoT with one tick left counted the
-- same as one with ten and the whole ability was an estimate.
-- 📌 The binding did exist -- `Mob::GetBuffStatValueBySlot(slot, "ticsremaining")`
-- (spell_effects.cpp:10794) -- but `lua_mob.cpp` registered it with a cast to `void`, so luabind
-- discarded the return and Lua got **nil** on every call. Fixed at the binding; the workaround here
-- is retired. ⚠️ The `or 3` fallback stays: if that binding ever regresses to nil again this
-- degrades to the old estimate instead of computing zero damage.
-- ⚠️ eq.get_spell_stat exposes effectid/base/formula per slot, which is what makes detecting
-- somebody else's DoT possible at all.
local function dot_pool(t, caster_level)
	local total, found = 0, {}
	for slot = 0, 24 do
		local sid = t:FindBuffBySlot(slot)
		if sid and sid > 0 then
			if (eq.get_spell_stat(sid, "goodeffect") or 0) == 0 then
				-- ⚠️⚠️ THE SLOT ARGUMENT IS 1-BASED. GetSpellStatValue does `if (slot > 0) slot -= 1`
				-- (common/spdat.cpp:2433), so 0 and 1 BOTH read effect slot 1 -- looping from 0 reads
				-- the first slot twice and never sees the third.
				for i = 1, 3 do
					local eff = eq.get_spell_stat(sid, "effectid", i)
					local base = eq.get_spell_stat(sid, "base", i) or 0
					if eff == 0 and base < 0 then
						local formula = eq.get_spell_stat(sid, "formula", i) or 100
						local per = math.abs(base)
						if formula > 0 and formula < 100 then per = per + caster_level * formula end
						-- ⚠️ REAL tics left, not an assumed 3. Clamped to at least 1: a DoT about to
						-- expire is still worth its last tick, and 0 would make it free to consume.
						local tics = tonumber(t:GetBuffStatValueBySlot(slot, "ticsremaining")) or 3
						if tics < 1 then tics = 1 end
						total = total + per * tics
						found[#found + 1] = sid
						break
					end
				end
			end
		end
	end
	return total, found
end
P[44731] = function(c, t)                                    -- Soul Harvest
	if not t or not t.valid then return end
	local total, found = dot_pool(t, c:GetLevel())
	if total <= 0 then M.tell(c, "Nothing is afflicting your target.") return end
	t:Damage(c, total, 44731, 24, false)
	local healed = math.floor(total / 2)
	c:HealDamage(healed, c)
	M.tell(c, string.format("You harvest %d afflictions for %d damage, drawing %d life.",
		#found, total, healed))
	-- The afflictions are CONSUMED -- that is the whole ability, and it is also what stops it being
	-- pressed twice on the same pool.
	for _, sid in ipairs(found) do t:BuffFadeBySpellID(sid) end
end
P[44732] = function(c, t)                                    -- Toll of the Dead
	if not t or not t.valid then return end
	local total = dot_pool(t, c:GetLevel())
	if total <= 0 then M.tell(c, "Nothing is afflicting your target.") return end
	local share = (total >= (t:GetHP() or 0)) and 25 or 5
	local toll = math.max(1, math.floor(total * share / 100))
	t:Damage(c, toll, 44732, 24, false)
	M.tell(c, string.format("Death's toll claims %d%s.", toll,
		share == 25 and " -- your afflictions alone would already have killed it" or ""))
	M.cut_tier2(c, 15)
end

-- ============================================================== 12 WIZARD
P[44733] = function(c, t)                                    -- Arcane Fist
	-- ⚠️⚠️ THIS HAD NO PAYLOAD AND AN INERT ROW, so pressing it did literally nothing -- the one
	-- ability of the 48 that was dead in both halves at once. Found by intersecting "row has no real
	-- SPAs" with "module has no PAYLOAD entry"; neither list alone would have shown it.
	if not M.weapon_blow(c, t, 10, 0.7) then return end
	-- The strike returns a little of what it costs to cast. Flat and level-scaled, because
	-- DoSpecialAttackDamage returns void and the damage dealt is not knowable here.
	local back = c:GetLevel() * 2
	c:SetMana(math.min((c:GetMana() or 0) + back, c:GetMaxMana() or 0))
	M.tell(c, string.format("Your arcane fist returns %d mana.", back))
end
P[44734] = function(c, t)                                    -- Overload
	-- The nuke is on the row; this is the recoil and the Ley Tap payoff.
	M.tell_nuke(c, 44734, t, "Overload")
	local stacks = ley_stacks(c)
	if stacks > 0 and t and t.valid then
		local bonus = math.floor(c:GetLevel() * 20 * 0.15 * stacks)
		t:Damage(c, bonus, 44734, 24, false)
		ley_set(c, 0)
		M.tell(c, string.format("Your overload discharges %d ley threads for %d more damage.",
			stacks, bonus))
	else
		M.tell(c, "Your overload discharges, with no ley threads gathered.")
	end
	M.tell(c, "The recoil leaves you reeling.")
	c:Stun(2000)
end
P[44735] = function(c, _, e)                                 -- Ley Tap
	M.tell_nuke(c, 44735, e and e.target, "Ley Tap")
	local stacks = math.min(ley_stacks(c) + 1, LEYTAP_MAX)
	ley_set(c, stacks)
	M.tell(c, string.format("Ley threads gathered: %d of %d.", stacks, LEYTAP_MAX))
	M.cut_tier2(c, 5)
end

-- ============================================================== 13 MAGICIAN
P[44736] = function(c, t)                                    -- Elemental Fist
	if not M.weapon_blow(c, t, 10) then return end
	if M.ensure_pet(c, 44754) then
		M.tell(c, "Your elemental fist lands, and an elemental guardian answers.")
	else
		M.tell(c, "Your elemental fist lands.")
	end
end
P[44738] = function(c, t)                                    -- Cinder Blast
	M.tell_nuke(c, 44738, t, "Cinder Blast")
	local p = c:GetPet()
	local pt = (p and p.valid) and p:GetTarget() or nil
	if t and t.valid and pt and pt.valid and pt:GetID() == t:GetID() then
		local bonus = c:GetLevel() * 3
		t:Damage(c, bonus, 44738, 24, false)                -- doubles the row's own damage
		M.tell(c, string.format("Your companion is already on that target -- the blast flares for %d more.",
			bonus))
	else
		M.tell(c, "Your cinder blast strikes, though your companion fights elsewhere.")
	end
	M.cut_tier2(c, 7)
end

-- ============================================================== 14 ENCHANTER
P[44741] = function(c)                                       -- Mind Fray (SPA 286 is on the row)
	M.tell(c, "Your mind frays, sharpening what you cast next.")
	M.cut_tier2(c, 5)
end

-- ============================================================== 15 BEASTLORD
P[44742] = function(c, t)                                    -- Feral Swipe
	if not M.weapon_blow(c, t, 10) then return end
	if M.ensure_pet(c, 44755) then
		M.tell(c, "Your feral swipe lands, and a feral companion answers.")
	else
		M.tell(c, "Your feral swipe lands.")
	end
end
P[44743] = function(c)                                       -- Feral Frenzy
	local p = c:GetPet()
	-- ⚠️ The row is targettype 6 (self), so the pet half has to be applied by hand. ApplySpellBuff
	-- puts the buff straight on without a cast, which is what "and your companion" needs.
	if p and p.valid then
		p:ApplySpellBuff(44743)
		M.tell(c, "You and your companion fall into a feral frenzy.")
	else
		M.tell(c, "You fall into a feral frenzy, with no companion to share it.")
	end
end
P[44744] = function(c, t)                                    -- Bloodscent
	local wounded = t and t.valid and (t:GetHPRatio() or 100) <= 50
	if not M.weapon_blow(c, t, 15, wounded and 1.8 or 1.0) then return end
	M.tell(c, wounded
		and "You scent blood and tear into the wound."
		or "You find your quarry still whole.")
	M.cut_tier2(c, wounded and 10 or 5)
end

-- ============================================================== 16 BERSERKER
P[44745] = function(c, t)                                    -- Reckless Cleave
	if not M.weapon_blow(c, t, 10, 1.4) then return end
	-- ⚠️ Self damage must never be able to kill you -- an ability that can finish you off is one
	-- nobody presses. SetHP, not Damage: Damage would put the Berserker on their own hate list.
	local bleed = math.max(1, math.floor(c:GetMaxHP() * 0.01))
	c:SetHP(math.max(1, c:GetHP() - bleed))
	M.tell(c, string.format("You cleave recklessly, tearing %d from yourself.", bleed))
end
P[44746] = function(c, t)                                    -- Frenzied Onslaught
	for _ = 1, 5 do M.weapon_blow(c, t, 120, 0.5) end
	M.tell(c, string.format("You rain five blows on %s.", t and t:GetCleanName() or "your target"))
end
P[44747] = function(c, t)                                    -- Blood Frenzy
	if not M.weapon_blow(c, t, 15) then return end
	-- 2 seconds per tenth of health missing: fully wounded is the full 18, untouched is nothing.
	local missing = 100 - (c:GetHPRatio() or 100)
	local cut = math.floor(missing / 10) * 2
	M.tell(c, cut > 0
		and "Your own wounds feed the frenzy."
		or "You are unhurt, and the frenzy finds nothing to feed on.")
	M.cut_tier2(c, cut)
end

-- ---------------------------------------------------------------------------------------------
-- The Class Abilities WINDOW (dll: core_abilities.cpp).
--
-- ⚠️⚠️ THIS IS NOT A CONVENIENCE DUPLICATE OF THE STOCK COMBAT ABILITIES WINDOW. That window will
-- not open at all for a caster on this client, so for eleven of the sixteen classes this is the only
-- way to click these. See core_abilities.h for the disassembly that went looking for a class gate.
--
-- Protocol: server -> "ABILDATA <n>^spellid|name|tier|unlocked|ready_secs|reuse_secs^..."
--           client -> "/say abiluse <spellid>" , "/say abilrefresh"
-- ⚠️ The description rides on the SAME row rather than as a second line: three abilities of ~150
-- characters is well inside Client::Message's 4096 byte buffer, and a second line would be a second
-- chance for the RoF2 chat pipe to drop or reorder it (section 15).
M.RECAST_SECS = { [1] = 10, [2] = 120, [3] = 15 }

-- ⚠️ GENERATED alongside the db_str rows by custom/tools/gen_class_abilities.py, so the window text
-- and the spellbook text come from one spec. There is no Lua binding to read db_str, and hand
-- copying the strings would be two sources of truth.
local DESC = require("aotv4_class_ability_desc")

function M.send_data(c)
	if not c then return end
	local class = c:GetClass()
	if not M.BUILT[class] then
		c:Message(15, "Your class has no class abilities.")
		return
	end

	local rows, n = "", 0
	for tier = 1, 3 do
		local id       = M.spell_id(class, tier)
		local unlocked = (c:GetLevel() >= M.TIER_LEVEL[tier] and c:HasDisciplineLearned(id)) and 1 or 0

		-- ⚠️ Client::GetDisciplineTimer already guards on the timer being enabled and returns 0 when
		-- it is not -- but clamp anyway: section 19 records PersistentTimer::GetRemainingTime
		-- answering 0xFFFFFFFF for a timer that EXISTS but is DISABLED, which displays as a 49 day
		-- cooldown on an ability that is actually ready.
		local ready = c:GetDisciplineTimer(M.TIMER[tier]) or 0
		if ready < 0 or ready > 86400 then ready = 0 end

		rows = rows .. string.format("^%d|%s|%d|%d|%d|%d|%s",
			id, eq.get_spell_name(id), tier, unlocked, ready, M.RECAST_SECS[tier],
			DESC[id] or "")
		n = n + 1
	end
	c:Message(15, string.format("ABILDATA %d%s", n, rows))
end

-- ⚠️ Routed through UseDiscipline, the SAME entry point the stock hotbutton uses, so the level gate,
-- the endurance cost and the recast timer all still apply. A modified client gains nothing.
function M.handle_say(c, msg)
	if not c or not msg then return false end
	if msg == "abilrefresh" then
		M.send_data(c)
		return true
	end
	local id = msg:match("^abiluse%s+(%d+)$")
	if id then
		id = tonumber(id)
		-- ⚠️ Bounded to OUR band. Without this the window becomes a way to fire any discipline in the
		-- game by id, which a modified client would happily do.
		if id and id >= 44700 and id <= 44747 then
			local tgt = c:GetTarget()
			c:UseDiscipline(id, (tgt and tgt.valid) and tgt:GetID() or c:GetID())
		end
		return true
	end
	return false
end

-- ---------------------------------------------------------------------------------------------
-- The one entry point every stub calls.
--
-- ⚠️⚠️ THE COST IS TAKEN AFTER THE ABILITY HAS ALREADY LANDED, so a refusal must hand back BOTH the
-- buff and the cooldown. UseDiscipline checks only the row's token EndurCost of 1 and starts the
-- recast before this runs.
function M.fire(spell_id, e)
	-- ⚠️⚠️ `e.target`, NOT `e.self`. A SPELL event sets exactly six fields -- target, spell_id,
	-- caster_id, tics_remaining, caster_level, buff_slot, spell (`handle_spell_event`,
	-- zone/lua_parser_events.cpp:2081) -- and **`self` is not one of them**. Reading e.self gives nil,
	-- so every targeted ability silently did nothing: M.weapon_blow returns false on a nil target and
	-- the swing never happens. Only the self-buffs, which ignore the target, appeared to work.
	-- 📌 `e.self` IS correct in the DAMAGE hooks below -- a different event builder, different fields.
	-- The two look identical at the call site and are not.
	local target = e.target
	local caster = M.as_client(eq.get_entity_list():GetMobID(e.caster_id))
	if not caster then return end

	-- Name the ability for the damage meter's breakdown. Set once per press and deliberately NOT
	-- cleared: M.weapon_blow's per-swing flag is what the server consumes, and this only says which
	-- ability that swing belonged to.
	-- ⚠ A stale value is harmless -- it is only ever read while the per-swing flag is set.
	caster:SetEntityVariable("aotv4_fct_ability", tostring(spell_id))

	local spec = M.SPEC[spell_id]
	if spec and spec.cost then
		if not M.charge(caster, spec.cost) then
			if spec.buff then caster:BuffFadeBySpellID(spell_id) end
			M.refund(caster, spec.cost)
			return
		end
	end

	-- ⚠️⚠️ EVERY PRESS ANSWERS FOR ITSELF. `said` is cleared here and set by M.tell, so a payload
	-- that early-returns -- no target, nothing in range, no bow, nothing afflicting -- still leaves
	-- the player with a line explaining why. Without it "nothing happened" and "it fired and found
	-- nothing" are the same on screen, which is exactly the ambiguity that made Harrowing look broken.
	said = false
	local fn = P[spell_id]
	if fn then fn(caster, target, e) end
	if not said then
		-- The ten abilities whose spell row does all the work have no payload at all, so their line
		-- lives in M.NOTE. Anything else reaching here early-returned without saying why, which is a
		-- bug in that payload rather than in this fallback -- the generic line is the safety net.
		M.tell(caster, M.NOTE[spell_id]
			or string.format("You use %s.", eq.get_spell_name(spell_id) or "your ability"))
	end
	-- ⚠️ NO RETURN VALUE. Returning non-zero from EVENT_SPELL_EFFECT_* cancels the spell's own
	-- effects (spell_effects.cpp:172), which would silently delete every native half of these rows.
end

return M
