#!/usr/bin/env python3
"""
Generate the AoTv4 summon-pet system.

The five Summon abilities are NOT cast -- "Pets cannot be summoned via casting
and instead will summon automatically outside of combat" -- so each is a scribed
trait, and Lua summons the pet on a timer.

WHY THIS IS BUILT OUT OF SPELL ROWS
Mob::MakePet is not exposed to Lua (zone/pets.cpp:71 has no binding), so the only
way for a script to create a real, owned pet is to finish a spell carrying
SPA 33 (SummonPet). Such a spell names ONE pet type in `teleport_zone`, and pet
types are level-banded -- hence one helper spell per pet per band.

Emits:
  aotv4_summon_pets.sql  -- cloned bear/leopard npc_types, pets rows, helper spells
  ../quests/lua_modules/aotv4_summon_table.lua  -- band -> spell id lookup

Bear and Leopard have no usable native family (BLpet starts at level 9,
SpiritWolf only covers 26-58 and is a wolf), so they are CLONED from the
skel_pet_ family -- the only one spanning 1-68 -- with the race swapped. Same
stat scaling, correct appearance, no invented numbers.
"""
import os, subprocess

BANDS        = [1, 10, 20, 30, 40, 50, 60, 65]
HELPER_BASE  = 50200        # helper summon spells live here
NPC_BEAR     = 950000       # cloned npc_types blocks
NPC_LEOPARD  = 950100
RACE_BEAR    = 43           # a_blistered_bear / cave bear
RACE_LEOPARD = 439          # a_famished_leopard / ice tiger

# design-sheet ability id -> (label, source family, cloned?)
PETS = [
    (50044, "Bear",           "bear",       True),
    (50045, "Leopard",        "leopard",    True),
    (50046, "SkeletalMinion", "skel_pet_",  False),
    (50047, "FireImp",        "SumFireR",   False),
    (50048, "Willowisp",      "SumAirR",    False),
]

Q = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                 "..", "..", "..", "..", "q.sh")


def query(sql):
    """Run a query through the mariadb container and return rows as lists."""
    out = subprocess.run(
        ["sudo", "docker", "exec", "-i", "akk-stack-mariadb-1", "mysql",
         "-ueqemu", "-pr98nurg6qZExI7dyC7946SNh1yQhrd6", "peq", "-N", "-B", "-e", sql],
        capture_output=True, text=True, check=True).stdout
    return [line.split("\t") for line in out.strip().split("\n") if line]


def main():
    here = os.path.dirname(os.path.abspath(__file__))

    # ---- what the native families actually offer --------------------------
    families = {}
    for fam in ("skel_pet_", "SumFireR", "SumAirR"):
        # petpower = 0 is the BASE tier. A pet type has one row per petpower tier
        # (GetPoweredPetEntry picks the highest tier <= the caster's pet focus,
        # zone/pets.cpp:382) -- without this filter the join multiplies each type
        # by its tiers and scrambles the level ordering.
        rows = query(
            "SELECT p.type, n.level FROM pets p JOIN npc_types n ON n.id=p.npcID "
            "WHERE p.type LIKE '%s%%' AND p.petpower=0 ORDER BY n.level;"
            % fam.replace("_", r"\_"))
        families[fam] = [(int(lvl), t) for t, lvl in rows]

    def pick(fam, band):
        """Best band at or below `band`; falls back to the lowest available."""
        usable = [(l, t) for l, t in families[fam] if l <= band]
        return (usable[-1] if usable else families[fam][0])

    # the skeleton bands the bear/leopard clones are built from
    skel_for_band = {b: pick("skel_pet_", b) for b in BANDS}

    sql = [
        "-- AoTv4 summon-pet system -- GENERATED by gen_summons.py, do not hand-edit.",
        "-- Bear and Leopard are cloned from the skel_pet_ family (the only one",
        "-- spanning levels 1-68) with the race swapped: same stat scaling, right look.",
        "",
        "-- idempotent: clear anything a previous run made",
        "DELETE FROM pets      WHERE type LIKE 'AoTBear%%' OR type LIKE 'AoTLeopard%%';",
        "DELETE FROM npc_types WHERE id BETWEEN %d AND %d;" % (NPC_BEAR, NPC_LEOPARD + 99),
        "DELETE FROM spells_new         WHERE id BETWEEN %d AND %d;" % (HELPER_BASE, HELPER_BASE + 199),
        "DELETE FROM aotv4_spell_origin WHERE spell_id BETWEEN %d AND %d;" % (HELPER_BASE, HELPER_BASE + 199),
        "",
    ]

    # ---- clone npc_types ---------------------------------------------------
    # SELECT * into a temp table so this survives npc_types gaining columns;
    # naming every column here would rot the moment the schema changes.
    for label, base_id, race in (("Bear", NPC_BEAR, RACE_BEAR),
                                 ("Leopard", NPC_LEOPARD, RACE_LEOPARD)):
        sql.append("-- %s clones" % label)
        for i, band in enumerate(BANDS):
            lvl, src_type = skel_for_band[band]
            new_id = base_id + i
            sql += [
                "CREATE TEMPORARY TABLE aotv4_clone AS SELECT n.* FROM npc_types n "
                "JOIN pets p ON p.npcID=n.id WHERE p.type='%s' AND p.petpower=0 LIMIT 1;" % src_type,
                "UPDATE aotv4_clone SET id=%d, race=%d, name='AoT%s%d', lastname='';"
                % (new_id, race, label, band),
                "INSERT INTO npc_types SELECT * FROM aotv4_clone;",
                "DROP TEMPORARY TABLE aotv4_clone;",
                "INSERT INTO pets (type, petpower, npcID, temp, petcontrol, petnaming, "
                "monsterflag, equipmentset) VALUES ('AoT%s%d', 0, %d, 0, 2, 3, 0, -1);"
                % (label, band, new_id),
            ]
        sql.append("")

    # ---- helper summon spells ---------------------------------------------
    # Shape copied from native pet spells (e.g. 58 Elementalkin: Earth):
    # effectid1 = 33 (SummonPet), base 1, targettype 6 (self), pet type in
    # teleport_zone. classes8 = 255 so none of these are ever scribable.
    sql.append("-- helper summon spells: one per pet per band")
    lua_rows = []
    sid = HELPER_BASE
    for ability_id, label, fam, cloned in PETS:
        entries = []
        for band in BANDS:
            if cloned:
                pet_type = "AoT%s%d" % (label, band)
            else:
                _, pet_type = pick(fam, band)
            sql.append(
                "INSERT INTO spells_new (`id`,`name`,`teleport_zone`,`range`,`cast_time`,"
                "`recast_time`,`recovery_time`,`buffdurationformula`,`buffduration`,`mana`,"
                "`icon`,`new_icon`,`memicon`,`targettype`,`resisttype`,`goodEffect`,`classes8`,"
                "`spell_category`,`not_extendable`,`effectid1`,`effect_base_value1`,`formula1`) "
                "VALUES (%d,'Summon %s','%s',0,0,0,0,0,0,0,2511,161,161,6,0,1,255,-99,1,33,1,100);"
                % (sid, label, pet_type, ))
            sql.append("INSERT INTO aotv4_spell_origin (spell_id, origin, bucket) "
                       "VALUES (%d, 'aotv4', 'H');" % sid)
            entries.append((band, sid, pet_type))
            sid += 1
        lua_rows.append((ability_id, label, entries))
        sql.append("")

    with open(os.path.join(here, "aotv4_summon_pets.sql"), "w") as f:
        f.write("\n".join(sql) + "\n")

    # ---- Lua lookup table --------------------------------------------------
    lua = [
        "-- aotv4_summon_table.lua -- GENERATED by gen_summons.py, do not hand-edit.",
        "-- ability spell id -> ordered level bands -> the helper spell that summons",
        "-- that pet at that band. Consumed by aotv4_summons.lua.",
        "return {",
    ]
    for ability_id, label, entries in lua_rows:
        lua.append("\t[%d] = {  -- Summon %s" % (ability_id, label))
        for band, helper, pet_type in entries:
            lua.append("\t\t{ band = %-3d, spell = %d },  -- %s" % (band, helper, pet_type))
        lua.append("\t},")
    lua.append("}")

    with open(os.path.join(here, "..", "quests", "lua_modules",
                           "aotv4_summon_table.lua"), "w") as f:
        f.write("\n".join(lua) + "\n")

    print("bands: %s" % BANDS)
    for ability_id, label, entries in lua_rows:
        print("%-16s %s" % (label, ", ".join("L%d->%s" % (b, t) for b, _, t in entries)))
    print("\nhelper spells %d..%d" % (HELPER_BASE, sid - 1))


if __name__ == "__main__":
    main()
