#!/usr/bin/env python3
"""
Regenerate the level-up reward pool from the custom ability set.

spell_choice.gather_candidates reads a STATIC table out of spell_pool.lua
(spell_choice.lua:49) keyed by level -- it does not query the database. So the
new abilities are invisible to the reward window until this runs, no matter what
is in spells_new.

Emits into ../quests/lua_modules/:
  spell_pool.lua      pool[level] = { {id=, name=}, ... }
  spell_icons.lua     id -> new_icon   (the dll window's 40x40 icon index)
  spell_desc.lua      id -> description (the dll window's hover text)
  spell_blacklist.lua { [id]=true }    (now empty; see below)

Sources:
  * pool/icons  from spells_new joined to aotv4_spell_origin (bucket A/B only,
    so helper carriers can never be offered)
  * descriptions from the design CSVs, NOT db_str -- the new rows have
    descnum = 0, so there is no dbstr entry to read
"""
import csv, os, subprocess

BUCKETS   = ("A", "B")     # design abilities only; 'H' helpers are never offered
LEVEL_CAP = 30


def query(sql):
    out = subprocess.run(
        ["sudo", "docker", "exec", "-i", "akk-stack-mariadb-1", "mysql",
         "-ueqemu", "-pr98nurg6qZExI7dyC7946SNh1yQhrd6", "peq", "-N", "-B", "-e", sql],
        capture_output=True, text=True, check=True).stdout
    return [l.split("\t") for l in out.strip().split("\n") if l]


def lua_str(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    mods = os.path.join(here, "..", "quests", "lua_modules")

    rows = query(
        "SELECT s.classes8, s.id, s.name, s.new_icon "
        "FROM spells_new s JOIN aotv4_spell_origin o ON o.spell_id = s.id "
        "WHERE o.origin='aotv4' AND o.bucket IN (%s) "
        "AND s.classes8 BETWEEN 1 AND %d ORDER BY s.classes8, s.id;"
        % (",".join("'%s'" % b for b in BUCKETS), LEVEL_CAP))

    by_level = {}
    icons    = []
    for lvl, sid, name, icon in rows:
        by_level.setdefault(int(lvl), []).append((int(sid), name))
        icons.append((int(sid), int(icon)))

    # ---- descriptions come from the design sheets -------------------------
    desc = {}
    names_to_id = {name: sid for lvl, sid, name, _ in
                   ((r[0], int(r[1]), r[2], r[3]) for r in rows)}
    for fn in ("spell_design.csv", "spell_design_extra.csv"):
        with open(os.path.join(here, fn)) as f:
            for r in csv.DictReader(f):
                sid = names_to_id.get(r["name"])
                if sid:
                    desc[sid] = r["description"]

    # ---- spell_pool.lua ----------------------------------------------------
    out = ["-- AUTO-GENERATED by gen_pool.py -- do not hand-edit.",
           "-- pool[learn_level] = { {id=, name=}, ... }",
           "-- Drawn from the CUSTOM ability set (ids 50000+), not native spells:",
           "-- spells_new joined to aotv4_spell_origin, buckets %s, levels 1-%d."
           % ("/".join(BUCKETS), LEVEL_CAP),
           "-- Helper carriers (bucket H) are excluded, so they can never be offered.",
           "return {"]
    for lvl in sorted(by_level):
        entries = ", ".join('{id=%d,name="%s"}' % (sid, lua_str(n))
                            for sid, n in by_level[lvl])
        out.append("\t[%d]={ %s }," % (lvl, entries))
    out.append("}")
    open(os.path.join(mods, "spell_pool.lua"), "w").write("\n".join(out) + "\n")

    # ---- spell_icons.lua ---------------------------------------------------
    out = ["-- AUTO-GENERATED by gen_pool.py -- do not hand-edit.",
           "-- id -> spellbook icon index, for the eq-core-dll choice window.",
           "return {"]
    out += ["\t[%d]=%d," % (sid, ic) for sid, ic in icons]
    out.append("}")
    open(os.path.join(mods, "spell_icons.lua"), "w").write("\n".join(out) + "\n")

    # ---- spell_desc.lua ----------------------------------------------------
    out = ["-- AUTO-GENERATED by gen_pool.py -- do not hand-edit.",
           "-- id -> description, taken from the design CSVs. The custom rows have",
           "-- descnum = 0, so there is no db_str entry to read for them.",
           "return {"]
    out += ['\t[%d]="%s",' % (sid, lua_str(t)) for sid, t in sorted(desc.items())]
    out.append("}")
    open(os.path.join(mods, "spell_desc.lua"), "w").write("\n".join(out) + "\n")

    # ---- spell_blacklist.lua ----------------------------------------------
    # The old criteria (rez, Enchant-material, curse-cure, LDoN utility) all
    # describe NATIVE junk. The custom pool is hand-authored, so nothing in it
    # needs suppressing -- but spell_choice still requires the module.
    open(os.path.join(mods, "spell_blacklist.lua"), "w").write(
        "-- AUTO-GENERATED by gen_pool.py -- do not hand-edit.\n"
        "-- Empty by design: the reward pool is now a hand-authored custom set,\n"
        "-- so there is no native junk (rez / enchant-material / LDoN) to filter.\n"
        "return {}\n")

    total = sum(len(v) for v in by_level.values())
    print("pool: %d abilities across levels %d-%d"
          % (total, min(by_level), max(by_level)))
    print("per level: " + " ".join("L%d:%d" % (l, len(by_level.get(l, [])))
                                   for l in range(1, LEVEL_CAP + 1)))
    print("icons: %d   descriptions: %d" % (len(icons), len(desc)))


if __name__ == "__main__":
    main()
