-- AUTO-GENERATED: level-indexed AA reward pool. Do not hand-edit.
-- pool[level] = { {id=,name=,icon=,cls=,cost=,desc=,pr={{a=,r=}}}, ... }
-- Bard-tagged (classes&128), classic (expansion<=4), level<=60, deduped by name.
-- icon = cast-spell new_icon else thematic fallback. desc = db_str type 4 (truncated).
return {
  [1] = {
    {id=17,name="First Aid",icon=48,cls=65407,cost=1,desc="This ability increases the maximum that you can bind wound by 10 percent for each ability level."},
    {id=18,name="Healing Adept",icon=48,cls=16942,cost=2,desc="The first three ranks of this ability increase the maximum effectiveness of your healing spells by 2, 5, and 10 percent.  Additional ranks increase the maximum effectiveness of your healing by an additional 3 percent per rank."},
    {id=19,name="Healing Gift",icon=48,cls=16942,cost=2,desc="The first three ranks of this ability grant you a chance to score an exceptional heal at 3, 6, and 10 percent. Additional ranks up to rank 15 further increase the chance by 2 percent per rank. Rank 16+ increase this chance by 1 percent per rank. An exceptional heal doubles the he"},
    {id=20,name="Spell Casting Mastery",icon=21,cls=15906,cost=2,desc="This ability lowers the mana cost of spells by 2, 5, 10, and 15 percent."},
    {id=21,name="Spell Casting Reinforcement",icon=21,cls=25150,cost=2,desc="This ability increases the duration of beneficial spells that you cast. Ranks 1, 2, and 3 increase the duration by 5, 15, and 30 percent respectively. Each additional rank increases this duration by 20 percent."},
    {id=23,name="Spell Casting Fury",icon=21,cls=32318,cost=2,desc="The three ranks of this ability give you a 2, 4, and 7 percent chance to land critical hits with your direct damage spells."},
    {id=25,name="Spell Casting Subtlety",icon=21,cls=15360,cost=2,desc="The first three ranks of this ability make NPCs notice your magical activities 5, 10, and 20 percent less.  Additional ranks further enhance this effect."},
    {id=26,name="Spell Casting Expertise",icon=21,cls=15376,cost=2,desc="This ability makes it impossible for you to fizzle a spell. The first level affects all spells below level 20.  The second, on all spells below level 35.  The third, on all spells below level 52."},
    {id=27,name="Spell Casting Deftness",icon=21,cls=7184,cost=2,desc="This ability reduces the casting time of beneficial spells that have a duration longer than instant and a cast time greater than three seconds.  The ability levels reduce these casting times by 10, 25, and 50 percent."},
    {id=28,name="Natural Durability",icon=155,cls=65407,cost=2,desc="This ability increases your maximum hitpoints by 2, 5, and 10 percent for the first three ranks, and one additional percent for each rank after that.  (The percentages are based off of your base hitpoints, which include stamina and stamina effects.)"},
    {id=29,name="Natural Healing",icon=48,cls=49501,cost=2,desc="This ability raises your natural regeneration by one point per ability level."},
    {id=30,name="Combat Fury",icon=6,cls=16468,cost=2,desc="This ability increases your chance to land a critical hit.  Non-Warriors will nearly match the original critical hit abilities of Warriors, while Warriors will remain significantly ahead of other classes."},
    {id=31,name="Fear Resistance",icon=155,cls=49501,cost=2,desc="This ability grants you a resistance bonus to fear type spells of 5, 10, and 25 percent. It also increases the chance of breaking fear earlier."},
    {id=32,name="Finishing Blow",icon=6,cls=49501,cost=2,desc="This ability gives you a chance to finish off an NPC that is below 10 percent health and fleeing with a single blow.  Additional ranks increase the maximum level of affected NPC.  Rank 1: level 50, Rank 2: level 52, Rank 3: level 54, Rank 4: level 56, Rank 5: level 58, Rank 6: le"},
    {id=33,name="Combat Stability",icon=6,cls=65407,cost=2,desc="The first three ranks of this ability increase melee damage mitigation by 2, 5, and 10 percent.  Additional ranks further increase this effect."},
    {id=34,name="Combat Agility",icon=6,cls=65407,cost=2,desc="The first three ranks of this ability increase your melee damage avoidance by 2, 5 and 10 percent.  Additional ranks further increase this effect."},
    {id=35,name="Mass Group Buff",icon=-1,cls=30254,cost=9,desc="This ability turns the next group buff that you cast into a beneficial area effect spell, hitting everyone within its radius, at the cost of doubling the spell's mana usage."},
    {id=36,name="Divine Resurrection",icon=101,cls=2,cost=5,desc="This ability allows you to provide a resurrection that restores 100 percent experience, all hit points and mana, and causes no adverse resurrection effects.",pr={{a=19,r=3}}},
    {id=38,name="Celestial Regeneration",icon=118,cls=2,cost=5,desc="When activated, Celestial Regeneration heals all group members within range. Additional ranks in this ability further increase the amount healed by Celestial Regrowth.",pr={{a=19,r=3}}},
    {id=39,name="Bestow Divine Aura",icon=46,cls=2,cost=6,desc="This ability gives you the ability to cast a Divine Aura spell on a Player target, temporarily rendering the target invulnerable."},
    {id=41,name="Purify Soul",icon=42,cls=2,cost=5,desc="This ability allows you to cast a spell that cures most ailments. Rank 2 doubles the range of the spell.",pr={{a=19,r=3}}},
    {id=42,name="Quick Evacuation",icon=21,cls=2080,cost=3,desc="This ability reduces the casting time on your evacuation and succor spells by 10, 25, and 50 percent."},
    {id=43,name="Exodus",icon=129,cls=2080,cost=6,desc="This ability gives you the ability to cast an extremely fast-casting, no mana cost evacuation or succor spell."},
    {id=44,name="Quick Damage",icon=21,cls=6176,cost=3,desc="This ability reduces the casting time on your damage spells that have a casting time greater than three seconds by 2, 5, 10, 15, and 20 percent.",pr={{a=23,r=3}}},
    {id=45,name="Enhanced Root",icon=21,cls=32,cost=5,desc="This ability reduces the chance that a rooted NPC will be freed by your damage spells by 50 percent."},
    {id=46,name="Dire Charm",icon=26,cls=8192,cost=9,desc="This ability gives you the chance to permanently charm an NPC.  (Enchanters: All.  Druids: Animals only.  Necromancers: Undead only.)"},
    {id=47,name="Cannibalization",icon=115,cls=512,cost=5,desc="This ability will give the caster a new, massive Cannibalize spell.  Further ranks increase both the mana that can be harvested by using the ability as well as the amount of hit points consumed by the cannibalization.",pr={{a=224,r=3}}},
    {id=48,name="Quick Buff",icon=21,cls=25134,cost=3,desc="This ability reduces the casting time of many beneficial spells that have a duration by 10, 25, and 50 percent."},
    {id=49,name="Alchemy Mastery",icon=163,cls=512,cost=3,desc="This ability reduces your chances of failing alchemy combinations by 10, 25, and 50 percent."},
    {id=50,name="Rabid Bear",icon=49,cls=512,cost=5,desc="This ability turns you into a Rabid Bear, boosting all of your offensive capabilities.  Additional ranks increase the effect."},
    {id=52,name="Improved Familiar",icon=125,cls=2048,cost=9,desc="This ability will summon an improved familiar that is an upgrade from the greater familiar. This improved familiar is higher in level, has more hit points, and is very resistant to all spells.  Additional ranks will call forth a familiar that provides even greater benefits to its"},
    {id=53,name="Nexus Gate",icon=103,cls=2048,cost=6,desc="This ability gives you an instant-cast self gate spell to the Nexus."},
    {id=55,name="Permanent Illusion",icon=21,cls=8192,cost=3,desc="This ability allows you to zone without losing your current illusion."},
    {id=56,name="Jewel Craft Mastery",icon=163,cls=8192,cost=2,desc="This ability reduces your chance of failing jewelcraft combinations by 10, 25, and 50 percent."},
    {id=57,name="Gather Mana",icon=21,cls=8192,cost=5,desc="This ability allows you to recover up to 10,000 points of mana nearly instantly.",pr={{a=224,r=3}}},
    {id=58,name="Mend Companion",icon=99,cls=21504,cost=5,desc="This ability allows you to cast a quick healing spell on your pet."},
    {id=60,name="Frenzied Burnout",icon=53,cls=4096,cost=6,desc="This ability allows you to cast a buff on your pet that will cause it to go berserk, doing increased damage. Additional ranks improve your pet's ability to take and dispense damage."},
    {id=61,name="Elemental Form: Fire",icon=163,cls=4096,cost=3,desc="This ability will allow you to turn into a fire elemental, granting innate benefits of the form. Ranks 4 and above will give your fire spells a chance to proc a damage increasing buff on your group, each rank will increase the chance that the buff will proc."},
    {id=62,name="Elemental Form: Water",icon=163,cls=4096,cost=3,desc="This ability will allow you to turn into a water elemental, granting increased mana regeneration with each additional rank."},
    {id=63,name="Elemental Form: Earth",icon=163,cls=4096,cost=3,desc="This ability will allow you to turn into an earth elemental, granting innate benefits of the form. Ranks 4 and above will give your detrimental spells a chance to proc an absorb damage buff on your group, each rank will increase the chance that the buff will proc."},
    {id=64,name="Elemental Form: Air",icon=163,cls=4096,cost=3,desc="This ability will allow you to turn into a air elemental, granting innate benefits of the form. Ranks 4 and above will give your detrimental spells a chance to stun their target, each rank increasing the chance the stun will proc."},
    {id=67,name="Elemental Pact",icon=21,cls=4096,cost=5,desc="This ability will prevent components used in the summoning of pets from being expended."},
    {id=68,name="Life Burn",icon=47,cls=1024,cost=9,desc="This ability allows you to cast a no-resist direct damage spell equal to that of your current hitpoints. The effect drains your life and provides a life bond effect that does 250 damage per tick, for 6 ticks."},
    {id=69,name="Dead Mesmerization",icon=36,cls=1024,cost=3,desc="This ability allows you to cast an AE low resist mesmerization spell effective against the undead."},
    {id=70,name="Fear Storm",icon=28,cls=1024,cost=5,desc="Allows you to cast an AE low resist fear spell."},
    {id=71,name="Flesh to Bone",icon=83,cls=1024,cost=3,desc="This ability allows you to turn most meat or body part items into bone chips.  You must hold the item or stack on your cursor. *Warning* This ability will use magical or \"no trade\" items if they are held on the cursor."},
    {id=72,name="Call to Corpse",icon=109,cls=1024,cost=6,desc="This ability allows you to cast a no component summon corpse spell."},
    {id=73,name="Divine Stun",icon=161,cls=4,cost=9,desc="Training in this ability gives you a new, fast-casting spell that has the chance to interrupt NPCs up to level 68 for rank 1, level 73 for rank 2, level 78 for rank 3, level 83 for rank 4, level 88 for rank 5, level 93 for rank 6, level 95 for rank 7, level 98 for rank 8, level 1"},
    {id=75,name="Slay Undead",icon=6,cls=4,cost=3,desc="This ability will cause your critical hits to inflict greatly improved damage versus the undead.  Additional ranks increase both the damage you cause and the chance for it to occur.",pr={{a=30,r=3}}},
    {id=76,name="Act of Valor",icon=99,cls=4,cost=3,desc="This noble ability will allow you to transfer all of your hit points to a target player, killing you in the process."},
    {id=77,name="Holy Steed",icon=112,cls=4,cost=5,desc="This ability provides you with the power to call the ultimate holy steed to your side."},
    {id=78,name="Fearless",icon=155,cls=20,cost=6,desc="This ability will make you permanently immune to fear spells.",pr={{a=31,r=3}}},
    {id=79,name="2 Hand Bash",icon=6,cls=20,cost=6,desc="This ability will allow you to use your Bash skill while wielding any 2-handed weapon."},
    {id=81,name="Ambidexterity",icon=6,cls=16713,cost=9,desc="This ability increases your chance to use dual wield successfully."},
    {id=82,name="Archery Mastery",icon=6,cls=8,cost=3,desc="This ability increases your archery damage 30, 60, 100, and 120 percent."},
    {id=84,name="Endless Quiver",icon=6,cls=8,cost=9,desc="This ability provides you a never-ending supply of arrows."},
    {id=85,name="Unholy Steed",icon=112,cls=16,cost=5,desc="This ability provides you with the power to call the ultimate unholy steed to your side."},
    {id=87,name="Leech Touch",icon=47,cls=16,cost=6,desc="This ability gives you a life tap harm touch that can be used in addition to your existing harm touch ability."},
    {id=89,name="Soul Abrasion",icon=21,cls=16,cost=3,desc="Each rank in this ability gives you increased damage off of the lifetap procs that result from your self buffs."},
    {id=90,name="Instrument Mastery",icon=4,cls=0,cost=3,desc="This ability allows for improved use of all instrument types."},
    {id=94,name="Jam Fest",icon=4,cls=0,cost=3,desc="This ability allows you to sing your songs at a higher apparent level.  Note: This does not allow you to sing songs that are actually higher than your level."},
    {id=97,name="Critical Mend",icon=48,cls=64,cost=3,desc="Each rank of this ability increases the chance to perform a superior mend.",pr={{a=17,r=3}}},
    {id=98,name="Purify Body",icon=-1,cls=64,cost=9,desc="This ability removes all negative effects from your body except for fear, charm, and resurrection effects. This ability does not work when you are silenced."},
    {id=100,name="Rapid Feign",icon=6,cls=64,cost=3,desc="This ability reduces your reuse time on feign death by 10, 25, and 50 percent."},
    {id=101,name="Return Kick",icon=6,cls=64,cost=3,desc="This ability gives you the chance to automatically perform a bonus flying kick on ripostes 25, 35, and 50 percent of the time."},
    {id=102,name="Escape",icon=-1,cls=256,cost=9,desc="This ability will cause all NPCs to forget about you.  If you are out of immediate combat, this ability will also make you invisible similar to your hiding ability."},
    {id=103,name="Poison Mastery",icon=6,cls=256,cost=3,desc="This ability reduces your chance of failing on a poison combination by 10, 25, and 50 percent. It also reduces the time to apply poison by 2.5 seconds per ability level. Once one point is applied to this ability, you will never again fail in poison application."},
    {id=104,name="Double Riposte",icon=6,cls=49501,cost=3,desc="The first three ranks of this ability will give you an increased chance to execute a double riposte 15, 35, and 50 percent of the time.  Additional ranks further increase this effect."},
    {id=107,name="Purge Poison",icon=-1,cls=256,cost=5,desc="This ability will remove all poisons from your body."},
    {id=108,name="Flurry",icon=6,cls=32769,cost=3,desc="This ability will allow you to perform up to 2 additional attacks from your primary hand. Each rank increases the chance to flurry.",pr={{a=309,r=3}}},
    {id=109,name="Rampage",icon=-1,cls=32769,cost=5,desc="This ability will allow you to strike everything in a small radius. Each rank increases the number of strikes upon your enemies."},
    {id=110,name="Area Taunt",icon=-1,cls=1,cost=5,desc="This ability will allow you to taunt everything in a small radius."},
    {id=111,name="War Cry",icon=17,cls=1,cost=3,desc="This ability will allow you to make your entire group immune to fear for 10 seconds per level of the ability.",pr={{a=31,r=3}}},
    {id=112,name="Bandage Wound",icon=48,cls=32769,cost=3,desc="This ability will give you increased healing ability per bandage by 10, 25, and 50 percent.",pr={{a=17,r=3}}},
    {id=114,name="Spell Casting Fury Mastery",icon=21,cls=2048,cost=3,desc="Each rank of this ability gives you an increased chance to score a critical hit with your direct damage spells. Starting with rank 15, you will receive an increase in critical damage as well.",pr={{a=23,r=3}}},
    {id=116,name="Dragon Punch",icon=161,cls=64,cost=5,desc="This ability augments Dragon Punch for human and drakkin monks and Tail Rake for iksars with the chance to automatically perform a Knockback."},
    {id=117,name="Strong Root",icon=117,cls=2048,cost=5,desc="This ability will grant you the ability to cast an extremely low resistance Root-type spell."},
    {id=118,name="Singing Mastery",icon=4,cls=0,cost=3,desc="This ability allows for specialization and improved use of your voice."},
    {id=119,name="Body and Mind Rejuvenation",icon=48,cls=16412,cost=5,desc="This ability will give you one additional point of mana and hit point regeneration."},
    {id=120,name="Physical Enhancement",icon=155,cls=49501,cost=5,desc="This ability will give you additional improvements in your Natural Durability, Avoidance Boost, and Mitigation Boost."},
    {id=121,name="Adv. Trap Negotiation",icon=163,cls=256,cost=3,desc="This ability will reduce the reuse time on your sense and disarm trap skills."},
    {id=122,name="Acrobatics",icon=6,cls=320,cost=3,desc="This ability will reduce the damage that you take from falling."},
    {id=123,name="Scribble Notes",icon=4,cls=0,cost=3,desc="This ability will reduce the amount of time that it takes you to memorize a song."},
    {id=124,name="Chaotic Stab",icon=6,cls=256,cost=6,desc="This ability will allow you to do minimal backstab damage on your backstab attempt, even if you are not positioned behind the monster."},
    {id=125,name="Pet Discipline",icon=6,cls=22032,cost=6,desc="This ability will allow you to give your pet a 'hold' command until explicitly told to attack. Usage: /pet hold. Pet Hold is now a state that your pet is either in or not. When your pet is in the hold state, your pet will only attack something when you tell it to, and your pet wi"},
    {id=126,name="Hobble of Spirits",icon=60,cls=16384,cost=5,desc="Once you train this ability, you may imbue your pet with an attack that is reputed to slow an enemy's walking.  Additional ranks increase the effectiveness and duration of your pet's ability to slow an enemy's walking speed."},
    {id=127,name="Frenzy of Spirit",icon=49,cls=16384,cost=4,desc="This ability gives Beastlords the power to send themselves into an animalistic frenzy, bent only on slaughter, for a brief period of time."},
    {id=128,name="Paragon of Spirit",icon=72,cls=16384,cost=6,desc="This ability allows the Beastlord to share some of his natural attunement with his party in the form of health and mana.  Additional ranks increase the amount of health and mana that is shared with party."},
    {id=141,name="New Tanaan Crafting Mastery",icon=163,cls=65407,cost=3,desc="Training with the sages and merchants of New Tanaan gives adventurers the chance to hone their crafting skills.  For each rank of this ability that you purchase, you are able to raise an additional trade skill past its Specialization level (200).  (This ability applies to Baking,"},
    {id=218,name="Headshot",icon=6,cls=8,cost=4,desc="This ability provides you the chance of instantly killing an opponent (humanoid only) who is too far below you in level to provide a challenge, when using a bow.  Additional ranks increase the maximum level of humanoid that can be affected by your headshot by 2 levels per rank.",pr={{a=82,r=1}}},
    {id=223,name="Quick Summoning",icon=21,cls=4096,cost=3,desc="This ability reduces the casting time of your summoning spells by 10, 25, and 50 percent."},
    {id=224,name="Mental Clarity",icon=21,cls=32318,cost=2,desc="This ability increases your natural mana regeneration by 1 point per ability level."},
    {id=227,name="Extended Notes",icon=4,cls=0,cost=3,desc="Each rank of this ability increases the range of your songs.  Rank 1 increases it by 10%, rank 2 by 15%, rank 3 by 25%, rank 4 by 30%, rank 5 by 35%, and rank 6 by 40%."},
    {id=229,name="Improved Reclaim Energy",icon=21,cls=4096,cost=3,desc="This ability will increase the amount of mana returned to you when reclaiming your pet."},
    {id=331,name="Origin",icon=31,cls=65407,cost=0,desc="Upon using this ability, you will be transported back to your starting city. This ability is usable every 18 minutes."},
    {id=367,name="Throwing Mastery",icon=6,cls=32768,cost=3,desc="Each rank of this ability increases the damage you do with throwing weapons."},
    {id=369,name="Hastened War Cry",icon=6,cls=32768,cost=3,desc="This ability reduces the timer on the various war cry disciplines by 3 minutes per rank."},
    {id=372,name="Tireless Sprint",icon=4,cls=32768,cost=3,desc="This ability gives you an enhanced form of your Sprint discipline that refresh much more quickly."},
    {id=558,name="Turn Undead",icon=164,cls=2,cost=3,desc="This ability infuses an undead NPC with holy energy, causing it to continually take damage for the next 30 seconds.  Each additional level of this ability increases the damage done.  Occasionally an undead NPC will react violently to the infusion of holy energy, potentially destr"},
    {id=559,name="Turn Summoned",icon=164,cls=4096,cost=3,desc="This ability infuses a summoned NPC with elemental energy, causing it to continually take damage for the next 30 seconds.  Each additional level of this ability increases the damage done.  Occasionally a summoned NPC will react violently to the infusion of energy, potentially des"},
    {id=565,name="Mana Burn",icon=153,cls=2048,cost=5,desc="This ability allows you to channel up to 3000 mana into a raw, unfocused blast of pure magical energy aimed at your target.",pr={{a=224,r=3}}},
    {id=918,name="Furious Refrain",icon=4,cls=0,cost=3,desc="This ability gives you the chance to automatically perform a bonus attack when you riposte."},
    {id=5005,name="Foraging",icon=6,cls=65407,cost=3,desc="Grants an increase of 50 points to the Forage skill of anyone who purchases it. Will increase the skill cap for those that have the Forage skill and grant the skill and raise the cap to those that do not."},
    {id=6000,name="Harm Touch",icon=161,cls=16,cost=0,desc="Grants the Shadow Knight a powerful destructive ability that inflicts terrible pain and damage on their target."},
    {id=6001,name="Lay on Hands",icon=99,cls=4,cost=0,desc="Grants the Paladin a Divine heal. Additional ranks increase the power of this ability by increasing the amount healed."},
    {id=6002,name="Hunter's Attack Power",icon=6,cls=8,cost=0,desc="This ability increases your attack power by 4 each rank. You will gain this ability automatically once each level starting at level 55."},
  },
}
