-- aotv4_summon_table.lua -- GENERATED by gen_summons.py, do not hand-edit.
-- ability spell id -> ordered level bands -> the helper spell that summons
-- that pet at that band. Consumed by aotv4_summons.lua.
return {
	[50044] = {  -- Summon Bear
		{ band = 1  , spell = 50200 },  -- AoTBear1
		{ band = 10 , spell = 50201 },  -- AoTBear10
		{ band = 20 , spell = 50202 },  -- AoTBear20
		{ band = 30 , spell = 50203 },  -- AoTBear30
		{ band = 40 , spell = 50204 },  -- AoTBear40
		{ band = 50 , spell = 50205 },  -- AoTBear50
		{ band = 60 , spell = 50206 },  -- AoTBear60
		{ band = 65 , spell = 50207 },  -- AoTBear65
	},
	[50045] = {  -- Summon Leopard
		{ band = 1  , spell = 50208 },  -- AoTLeopard1
		{ band = 10 , spell = 50209 },  -- AoTLeopard10
		{ band = 20 , spell = 50210 },  -- AoTLeopard20
		{ band = 30 , spell = 50211 },  -- AoTLeopard30
		{ band = 40 , spell = 50212 },  -- AoTLeopard40
		{ band = 50 , spell = 50213 },  -- AoTLeopard50
		{ band = 60 , spell = 50214 },  -- AoTLeopard60
		{ band = 65 , spell = 50215 },  -- AoTLeopard65
	},
	[50046] = {  -- Summon SkeletalMinion
		{ band = 1  , spell = 50216 },  -- skel_pet_1_
		{ band = 10 , spell = 50217 },  -- skel_pet_9_
		{ band = 20 , spell = 50218 },  -- skel_pet_19_
		{ band = 30 , spell = 50219 },  -- skel_pet_29_
		{ band = 40 , spell = 50220 },  -- skel_pet_37_
		{ band = 50 , spell = 50221 },  -- skel_pet_47_
		{ band = 60 , spell = 50222 },  -- skel_pet_63_
		{ band = 65 , spell = 50223 },  -- skel_pet_67_
	},
	[50047] = {  -- Summon FireImp
		{ band = 1  , spell = 50224 },  -- SumFireR2
		{ band = 10 , spell = 50225 },  -- SumFireR3
		{ band = 20 , spell = 50226 },  -- SumFireR6
		{ band = 30 , spell = 50227 },  -- SumFireR9
		{ band = 40 , spell = 50228 },  -- SumFireR11
		{ band = 50 , spell = 50229 },  -- SumFireR14
		{ band = 60 , spell = 50230 },  -- SumFireR15
		{ band = 65 , spell = 50231 },  -- SumFireR16
	},
	[50048] = {  -- Summon Willowisp
		{ band = 1  , spell = 50232 },  -- SumAirR2
		{ band = 10 , spell = 50233 },  -- SumAirR3
		{ band = 20 , spell = 50234 },  -- SumAirR6
		{ band = 30 , spell = 50235 },  -- SumAirR9
		{ band = 40 , spell = 50236 },  -- SumAirR11
		{ band = 50 , spell = 50237 },  -- SumAirR14
		{ band = 60 , spell = 50238 },  -- SumAirR15
		{ band = 65 , spell = 50239 },  -- SumAirR16
	},
}
