-- AUTO-GENERATED by gen_pool.py -- do not hand-edit.
-- Empty by design: the reward pool is now a hand-authored custom set,
-- so there is no native junk (rez / enchant-material / LDoN) to filter.
return {}
