-- AUTO-GENERATED by gen_pool.py -- do not hand-edit.
-- pool[learn_level] = { {id=, name=}, ... }
-- Drawn from the CUSTOM ability set (ids 50000+), not native spells:
-- spells_new joined to aotv4_spell_origin, buckets A/B, levels 1-30.
-- Helper carriers (bucket H) are excluded, so they can never be offered.
return {
	[1]={ {id=50014,name="Throw Stone"}, {id=50017,name="Languid Healing"}, {id=50028,name="Minor Regeneration"}, {id=50040,name="Brawn"}, {id=50041,name="Nimbleness"} },
	[2]={ {id=50018,name="Woodskin"}, {id=50025,name="Breeze"}, {id=50027,name="Life Ebb"}, {id=50058,name="Thorncoat"} },
	[3]={ {id=50000,name="Ember"}, {id=50031,name="Passive Protection"}, {id=50032,name="Minor Fortify Attack"}, {id=50038,name="Courage"} },
	[4]={ {id=50035,name="Blade Turn"}, {id=50039,name="Thoughfulness"}, {id=50051,name="Chi Block"} },
	[5]={ {id=50019,name="Minor Magic Barrier"}, {id=50036,name="Manatap"}, {id=50049,name="Firefist"}, {id=50084,name="Ensnare"} },
	[6]={ {id=50033,name="Concentration"}, {id=50044,name="Summon Bear"}, {id=50050,name="Inner Focus"}, {id=50057,name="Reflect"} },
	[7]={ {id=50034,name="Willpower"}, {id=50045,name="Summon Leopard"}, {id=50048,name="Summon Willowisp"}, {id=50059,name="Vengeful Aura"} },
	[8]={ {id=50001,name="Zap"}, {id=50010,name="Kick"}, {id=50016,name="Basic Healing"}, {id=50061,name="Cinder"} },
	[9]={ {id=50008,name="Frost"}, {id=50043,name="Alacrity"}, {id=50060,name="Taunt"} },
	[10]={ {id=50004,name="Poison"}, {id=50037,name="Yawn"}, {id=50046,name="Summon Skeletal Minion"}, {id=50047,name="Summon Fire Imp"} },
	[11]={ {id=50029,name="Sturdy Footing"}, {id=50042,name="Haste"}, {id=50083,name="Thorns"}, {id=50090,name="Levitate"} },
	[12]={ {id=50002,name="Smolder"}, {id=50012,name="Lifetap"}, {id=50081,name="Shielding"}, {id=50088,name="Cancel Magic"} },
	[13]={ {id=50053,name="Ambidexterous"}, {id=50078,name="Barkskin"}, {id=50089,name="Invisibility"} },
	[14]={ {id=50009,name="Chill"}, {id=50056,name="Counterattack"}, {id=50065,name="Jolt"}, {id=50086,name="Blinding Flash"} },
	[15]={ {id=50006,name="Fever"}, {id=50062,name="Scorch"}, {id=50067,name="Rime"}, {id=50087,name="Concussion"} },
	[16]={ {id=50020,name="Tepid recovery"}, {id=50073,name="Mend"}, {id=50085,name="Terror"}, {id=50104,name="Malaise"} },
	[17]={ {id=50013,name="Dread"}, {id=50072,name="Siphon Life"}, {id=50098,name="Blade Ward"} },
	[18]={ {id=50003,name="Shock"}, {id=50092,name="Bloodward"}, {id=50097,name="Mending Grace"}, {id=50106,name="Falcon Eye"} },
	[19]={ {id=50015,name="Snipe"}, {id=50026,name="Minor Manaflow"}, {id=50069,name="Venom"}, {id=50101,name="Sleetfall"} },
	[20]={ {id=50052,name="Open Wounds"}, {id=50082,name="Resist Elements"}, {id=50099,name="Stoneshield"}, {id=50102,name="Emberfall"} },
	[21]={ {id=50054,name="The Left"}, {id=50063,name="Immolate"}, {id=50105,name="Scent of Ruin"} },
	[22]={ {id=50068,name="Glacial Spike"}, {id=50080,name="Arcane Ward"}, {id=50100,name="Spellshield"}, {id=50103,name="Veil of Forgetting"} },
	[23]={ {id=50091,name="Reptile Hide"}, {id=50094,name="Adrenaline Surge"}, {id=50108,name="Mind Shatter"}, {id=50110,name="Chorus of Replenishment"} },
	[24]={ {id=50011,name="Strike"}, {id=50066,name="Arc Lightning"}, {id=50096,name="Spirit of the Lynx"}, {id=50111,name="Torrent of Misery"} },
	[25]={ {id=50064,name="Ignite Blood"}, {id=50076,name="Group Mend"}, {id=50095,name="Arcane Bulwark"}, {id=50107,name="Moonfire"} },
	[26]={ {id=50077,name="Second Wind"}, {id=50079,name="Stoneskin"}, {id=50109,name="War March"} },
	[27]={ {id=50005,name="Toxic Gas"}, {id=50071,name="Withering Curse"}, {id=50074,name="Salve"}, {id=50112,name="Bond of Xalgoz"} },
	[28]={ {id=50007,name="Infection Cloud"}, {id=50070,name="Plague"}, {id=50075,name="Renewal"}, {id=50093,name="Last Rites"} },
	[29]={ {id=50022,name="Divine Aura"}, {id=50024,name="Harm Touch"}, {id=50030,name="Duel"}, {id=50055,name="Armor Rend"} },
	[30]={ {id=50021,name="Desperate recovery"}, {id=50023,name="Lay on Hands"} },
}
