#!/usr/bin/env python3
"""Generate lua_modules/aotv4_gamble_pool.lua -- the prize pool for the Gilded Wager NPC.

⚠️⚠️ LUA CANNOT QUERY THE DATABASE, so this pool has to be baked into a module. Re-run it whenever
the loot tables, merchant lists or zone_regions change, or the casino will keep handing out prizes
from a world that has moved on.

WHAT COUNTS AS A PRIZE
  * WEARABLE only (items.slots > 0). Everything else is a tradeskill component, food or quest paper,
    and -- decisively -- only wearables have Hallowed and Mythic rows (section 10), so nothing else
    could be sold at the 5000p and 10000p tiers at all.
  * Obtainable in a zone belonging to one of the six choosable regions, either as LOOT from something
    that spawns there or as MERCHANT stock sold there.
  * BASE ids only (< 300000). The tier is chosen by what the player pays, so a tier id in the pool
    would let them buy a Mythic at the base price.
  * BOTH tier rows must exist, or the 5000p and 10000p prices could silently deliver nothing.

THE LEVEL ON EACH ROW is the gate for "nothing above your level".
⚠️ It is NOT `reclevel`: section 26 records that as useless here, because classic gear mostly leaves
it 0. It is the strongest of reqlevel, reclevel and the LOWEST level of anything that drops it --
the same "minimum dropper level" measure quest_difficulty.pl and the augment work already use.
📌 Merchant stock has no dropper, so it contributes level 1 and is gated by reqlevel/reclevel alone.
That is correct: a merchant sells to anyone who can carry the coin.
"""
import subprocess, os, sys, collections

SRC  = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT  = os.path.join(SRC, "repo", "quests", "lua_modules", "aotv4_gamble_pool.lua")
STEP = 300000

SQL = """
SELECT g.region_id, g.item,
       GREATEST(IFNULL(i.reqlevel,0), IFNULL(i.reclevel,0), MIN(g.lvl)) AS L
FROM (
  SELECT DISTINCT zr.region_id, lde.item_id AS item, nt.level AS lvl
  FROM spawn2 s2
  JOIN zone z ON z.short_name = s2.zone
  JOIN zone_regions zr ON zr.zone_id = z.zoneidnumber
  JOIN spawnentry se ON se.spawngroupID = s2.spawngroupID
  JOIN npc_types nt ON nt.id = se.npcID
  JOIN loottable_entries lte ON lte.loottable_id = nt.loottable_id
  JOIN lootdrop_entries lde ON lde.lootdrop_id = lte.lootdrop_id
  WHERE zr.region_id BETWEEN 1 AND 6 AND lde.item_id < 300000
  UNION
  SELECT DISTINCT zr.region_id, ml.item, 1
  FROM spawn2 s2
  JOIN zone z ON z.short_name = s2.zone
  JOIN zone_regions zr ON zr.zone_id = z.zoneidnumber
  JOIN spawnentry se ON se.spawngroupID = s2.spawngroupID
  JOIN npc_types nt ON nt.id = se.npcID
  JOIN merchantlist ml ON ml.merchantid = nt.merchant_id
  WHERE zr.region_id BETWEEN 1 AND 6 AND nt.merchant_id > 0 AND ml.item < 300000
) g
JOIN items i  ON i.id = g.item
JOIN items h  ON h.id = g.item + {step}
JOIN items m  ON m.id = g.item + {step} * 2
WHERE i.slots > 0
GROUP BY g.region_id, g.item
ORDER BY g.region_id, g.item;
""".format(step=STEP)

def q(sql):
    p = subprocess.run(["mysql", "-h127.0.0.1", "-upeq", "-ppeqpass", "peq", "-N", "-B", "-e", sql],
                       capture_output=True, text=True)
    if p.returncode:
        sys.exit("query failed: " + p.stderr)
    return [l.split("\t") for l in p.stdout.strip().split("\n") if l]

rows = q(SQL)
byreg = collections.defaultdict(list)
for r, item, lvl in rows:
    byreg[int(r)].append((int(item), int(lvl)))

out = [
 "-- GENERATED by custom/tools/gen_gamble_pool.py -- do not edit.",
 "-- The Gilded Wager prize pool: wearable items obtainable in each region, as loot or merchant stock.",
 "-- Each entry is {item_id, level}. The id is always a BASE id; the tier the player receives is",
 "-- decided by what they pay, so a tier id here would let them buy a Mythic at the base price.",
 "-- ⚠️ Every entry is guaranteed to have BOTH a Hallowed and a Mythic row, so the 5000p and 10000p",
 "-- prices can never resolve to nothing.",
 "-- ⚠️ `level` is the strongest of reqlevel, reclevel and the lowest level of anything that drops it",
 "-- -- NOT reclevel alone, which section 26 records as useless on classic gear.",
 "return {",
]
total = 0
for reg in sorted(byreg):
    entries = byreg[reg]
    total += len(entries)
    out.append("\t[%d] = {" % reg)
    line = "\t\t"
    for item, lvl in entries:
        piece = "{%d,%d}," % (item, lvl)
        if len(line) + len(piece) > 110:
            out.append(line); line = "\t\t"
        line += piece
    if line.strip():
        out.append(line)
    out.append("\t},")
out.append("}")
open(OUT, "w").write("\n".join(out) + "\n")
print("wrote %s" % os.path.relpath(OUT, SRC))
for reg in sorted(byreg):
    lv = [l for _, l in byreg[reg]]
    print("  region %d: %4d prizes   usable at level 5: %4d   at 15: %4d   at 30: %4d"
          % (reg, len(lv), sum(1 for x in lv if x <= 5), sum(1 for x in lv if x <= 15),
             sum(1 for x in lv if x <= 30)))
print("  total %d entries" % total)
