#!/usr/bin/perl
# AoTv4 -- generate rank 2-5 rows for every damage / heal spell reachable at the level cap.
# =============================================================================================
# Emits custom/sql/aotv4_spell_ranks.sql (the rows) and lua_modules/spell_ranks.lua (base -> chain,
# for the upgrade system to read at runtime).
#
# Each rank is +10 percent output and -5 percent mana, COMPOUNDING off the base:
#     output = base * 1.10^(rank-1)      rank 5 = +46.4 percent
#     mana   = mana * 0.95^(rank-1)      rank 5 = -18.5 percent
#
# ⚠️⚠️ WHY REAL SPELL ROWS RATHER THAN A RUNTIME MULTIPLIER. A real row shows its real damage and
# real mana in the NATIVE spellbook, and the mana saving is genuine -- the client checks against the
# rank's own cost. A per-character multiplier applied in GetActSpellDamage would leave the client
# displaying base values and would make the mana discount partly cosmetic, since the client decides
# whether you may BEGIN a cast from its own copy of the cost. This became affordable only after the
# rank-variant prune freed the id space (3,951 -> 10,077).
#
# ⚠️⚠️ SCOPE IS DAMAGE AND HEALING ONLY -- SPA 0 CurrentHP, 79 CurrentHPOnce, 100 HealOverTime.
# Buffs are excluded because a buff's magnitude has NO hook: it is read straight out of the spell row
# in SpellEffect, so "+10 percent to buff stats" could not be delivered even if the rows existed.
# DoTs ARE included: a DoT is SPA 0 with a duration, so it is the same field and scales identically.
#
# ⚠️ Naming is "<name> Rk. II".."Rk. V" ON PURPOSE. gen_stock_pool.pl filters the offerable pool with
# `name NOT LIKE '% Rk. %'`, so this convention makes rank rows UNOFFERABLE by the level-up picker
# for free -- they are reachable only by upgrading. Changing the naming silently puts them in the
# reward pool.
# ⚠️ spells_new.name is varchar(64) and the longest qualifying name is 55 -> 61 with " Rk. V". Any
# future widening of the scope must re-check that; MySQL truncates silently.
#
# ⚠️ Ids are assigned CONTIGUOUSLY from RANK_ID_FIRST. 188 spells x 4 = 752 rows, against 1,424 free
# in the unbroken 43576-44999 run. Keep them contiguous: the alternative is scattering across gaps,
# which is exactly the sporadic numbering the prune was meant to clean up.
#
# ⚠️ `spells_new` IS SHARED MEMORY: world down, ./shared_memory, restart, then export_client_files
# and reinstall spells_us.txt or the client will not know the rank rows exist.

use strict;
use warnings;

my $SQL_OUT  = ".devcontainer/custom/sql/aotv4_spell_ranks.sql";
my $LUA_OUT  = ".devcontainer/repo/quests/lua_modules/spell_ranks.lua";
my $RANK_ID_FIRST = 43576;   # first id of the unbroken free run
my $RANK_ID_LAST  = 44999;   # the RoF2 client ceiling is 45000, measured -- see SPELL_RANKS.md
my $MAX_RANK      = 5;
my $LEVEL_CAP     = 35;

my @HP_SPA   = (0, 79, 100);          # CurrentHP, CurrentHPOnce, HealOverTime
my $HP_SPA_IN = join(',', @HP_SPA);

sub mysql {
    my ($sql) = @_;
    open(my $h, "-|", "mysql", "-h127.0.0.1", "-upeq", "-ppeqpass", "peq", "-N", "--batch", "-e", $sql)
        or die "mysql: $!";
    my @r; while (<$h>) { chomp; push @r, [split /\t/, $_, -1] } close $h; return @r;
}
die "run from /src\n" unless -d ".devcontainer/repo/quests";

# ---------------------------------------------------------------- pick the spells
# Any slot carrying an HP-change effect qualifies. Scanning only slot 1 would miss a nuke with a
# rider effect first, and every DoT whose damage sits in a later slot.
my @slot_tests;
for my $s (1 .. 12) {
    push @slot_tests, "(effectid$s IN ($HP_SPA_IN) AND effect_base_value$s <> 0)";
}
my $qualifies = join(' OR ', @slot_tests);

my @spells = mysql(qq{
    SELECT id, name, mana
    FROM   spells_new
    WHERE  id < 10000
      AND  name NOT LIKE '% Rk. %'
      AND  classes8 BETWEEN 1 AND $LEVEL_CAP
      AND  ($qualifies)
    ORDER  BY id
});
die "no qualifying spells found\n" unless @spells;

my $need = @spells * ($MAX_RANK - 1);
my $room = $RANK_ID_LAST - $RANK_ID_FIRST + 1;
die sprintf("need %d ids but only %d in %d-%d -- narrow the scope or pick another band\n",
            $need, $room, $RANK_ID_FIRST, $RANK_ID_LAST) if $need > $room;

# ⚠️ Refuse to start if the band is not actually empty. Overwriting a live spell would be silent.
my ($busy) = mysql("SELECT COUNT(*) FROM spells_new WHERE id BETWEEN $RANK_ID_FIRST AND "
                   . ($RANK_ID_FIRST + $need - 1));
die "band $RANK_ID_FIRST..".($RANK_ID_FIRST+$need-1)." is not empty ($busy->[0] rows) -- refusing\n"
    if $busy->[0] > 0;

# ---------------------------------------------------------------- emit SQL
my @ROMAN = ('', 'I', 'II', 'III', 'IV', 'V');
open(my $out, '>', $SQL_OUT) or die "write $SQL_OUT: $!";
print $out <<"HEAD";
-- AoTv4 spell ranks -- GENERATED by custom/tools/gen_spell_ranks.pl. DO NOT HAND EDIT.
-- $need rows: ranks 2-$MAX_RANK for @{[scalar @spells]} damage/heal spells reachable at level $LEVEL_CAP.
-- Ids $RANK_ID_FIRST-@{[$RANK_ID_FIRST + $need - 1]}, contiguous.
--
-- ⚠️ Each rank is cloned VIA A TEMP TABLE so all ~236 columns stay byte-identical to the base spell.
-- Hand-listing columns is the section 5 rule; a cloned spell that silently differs in `formula` or
-- `max` is the trap that bit the Sinew line.
-- ⚠️ Named "Rk. II".."Rk. V" so gen_stock_pool.pl's `name NOT LIKE '% Rk. %'` filter keeps them OUT
-- of the level-up reward pool. They are obtainable only by upgrading.
-- ⚠️ spells_new IS SHARED MEMORY: world down, ./shared_memory, restart, re-export client files.
-- Re-runnable: the DELETE below clears exactly the band this script owns.

DELETE FROM spells_new WHERE id BETWEEN $RANK_ID_FIRST AND $RANK_ID_LAST;

HEAD

my (%chain, $next_id);
$next_id = $RANK_ID_FIRST;

for my $sp (@spells) {
    my ($base_id, $base_name) = ($sp->[0], $sp->[1]);
    for my $rank (2 .. $MAX_RANK) {
        my $id  = $next_id++;
        my $out_mult  = 1.10 ** ($rank - 1);
        my $mana_mult = 0.95 ** ($rank - 1);
        my $name = "$base_name Rk. $ROMAN[$rank]";
        $name = substr($name, 0, 64);

        push @{ $chain{$base_id} }, $id;

        print $out "-- $base_name -> rank $rank\n";
        print $out "CREATE TEMPORARY TABLE aotv4_tmp_rank AS SELECT * FROM spells_new WHERE id = $base_id;\n";
        print $out "UPDATE aotv4_tmp_rank SET id = $id, name = " . dbq($name) . ",\n";
        print $out "    `rank` = $rank, spellgroup = $base_id,\n";
        # ⚠️ ROUND, not truncate: at 1.10 a small heal would otherwise gain nothing per rank.
        printf $out "    mana = GREATEST(0, ROUND(mana * %.6f))", $mana_mult;
        for my $s (1 .. 12) {
            # ⚠️ Scale BOTH the base value and `max`. `max` caps a level-scaling formula, so leaving
            # it alone would let the cap silently erase the rank's benefit at higher levels.
            printf $out ",\n    effect_base_value$s = IF(effectid$s IN ($HP_SPA_IN), ROUND(effect_base_value$s * %.6f), effect_base_value$s)", $out_mult;
            printf $out ",\n    max$s = IF(effectid$s IN ($HP_SPA_IN) AND max$s <> 0, ROUND(max$s * %.6f), max$s)", $out_mult;
        }
        print $out ";\n";
        print $out "INSERT INTO spells_new SELECT * FROM aotv4_tmp_rank;\n";
        print $out "DROP TEMPORARY TABLE aotv4_tmp_rank;\n\n";
    }
}

print $out "SELECT CONCAT('rank rows created: ', COUNT(*)) AS x FROM spells_new WHERE id BETWEEN $RANK_ID_FIRST AND $RANK_ID_LAST;\n";
close $out;

sub dbq { my $s = shift; $s =~ s/\\/\\\\/g; $s =~ s/'/\\'/g; return "'$s'" }

# ---------------------------------------------------------------- emit the Lua chain map
open(my $lua, '>', $LUA_OUT) or die "write $LUA_OUT: $!";
print $lua <<'LHEAD';
-- AoTv4 spell rank chains -- GENERATED by custom/tools/gen_spell_ranks.pl. DO NOT HAND EDIT.
--
-- M.chain[base_spell_id] = { rank2_id, rank3_id, rank4_id, rank5_id }
-- M.base[any_rank_id]    = base_spell_id      (reverse lookup)
--
-- ⚠️ Upgrading is unscribe-old / scribe-new, exactly as native Rk. lines work -- a rank is a
-- DIFFERENT SPELL, not a modifier on the old one.
-- ⚠️ Regenerate together with the SQL. A chain pointing at an id the DB does not have fails silently:
-- the upgrade appears to work and the player ends up with nothing scribed.
local M = {}

LHEAD
print $lua "M.chain = {\n";
for my $base (sort { $a <=> $b } keys %chain) {
    printf $lua "  [%d] = {%s},\n", $base, join(',', @{ $chain{$base} });
}
print $lua "}\n\nM.base = {}\nfor b, ids in pairs(M.chain) do for _, id in ipairs(ids) do M.base[id] = b end end\n\nreturn M\n";
close $lua;

printf "wrote %s\n  spells: %d   rank rows: %d   ids %d-%d (%d spare in the band)\n",
    $SQL_OUT, scalar @spells, $need, $RANK_ID_FIRST, $RANK_ID_FIRST + $need - 1,
    $RANK_ID_LAST - ($RANK_ID_FIRST + $need - 1);
printf "wrote %s\n", $LUA_OUT;
