#!/usr/bin/perl
# =============================================================================================
# AoTv4 -- generate lua_modules/aa_pool.lua from the ENABLED AA set              2026-07-31
#
#   perl .devcontainer/custom/tools/gen_aa_pool.pl > .devcontainer/repo/quests/lua_modules/aa_pool.lua
#
# The pool the death picker (aa_choice.lua) draws from. One entry per ENABLED ability.
#
# ⚠️⚠️ THE POOL MUST MATCH THE ENABLED SET EXACTLY. An ability in the pool but not enabled is offered
# and then silently refused by GrantAlternateAdvancementAbility -- no message, the pick just does
# nothing (section 6). Re-run this after enabling or disabling ANY AA.
# ⚠️ `name` is the CLIENT-VISIBLE title from db_str type 1, NOT aa_ability.name -- the custom trees
# are hosted on native rows, so the internal name is the host's and would display the wrong thing.
# ⚠️ `mr` is the real rank count, walked by next_id (rank ids are NOT contiguous, section 10).
# ⚠️ `era` is always 0: the expansion-unlock system is orphaned (section 12) and aa_choice only tests
#    `era <= current`, so 0 always passes. Kept as a field so aa_choice needs no edit.
# ⚠️ Do NOT name a helper `q` -- that is Perl's quote operator and cannot be overridden; doing so
#    silently turns the SQL into a literal string and the generator emits a near-empty pool.
# =============================================================================================
use strict;
use warnings;

my $DB = 'mysql -h127.0.0.1 -upeq -ppeqpass peq -N -e';

sub dbq {
    my $sql = shift;
    $sql =~ s/\s+/ /g;
    $sql =~ s/"/\\"/g;
    return `$DB "$sql" 2>/dev/null`;
}

my $sql_rows = <<'SQL';
WITH RECURSIVE chain AS (
  SELECT a.id aa_id, r.id rank_id, r.next_id, 1 depth
  FROM aa_ability a JOIN aa_ranks r ON r.id=a.first_rank_id WHERE a.enabled=1
  UNION ALL SELECT c.aa_id,r2.id,r2.next_id,c.depth+1
  FROM chain c JOIN aa_ranks r2 ON r2.id=c.next_id WHERE c.depth<40),
rc AS (SELECT aa_id, COUNT(*) ranks FROM chain GROUP BY aa_id)
SELECT a.id, COALESCE(NULLIF(TRIM(t.value),''),TRIM(a.name)), r.cost, COALESCE(rc.ranks,1),
       COALESCE(REPLACE(REPLACE(d.value,CHAR(13),' '),CHAR(10),' '),'')
FROM aa_ability a JOIN aa_ranks r ON r.id=a.first_rank_id
LEFT JOIN rc ON rc.aa_id=a.id
LEFT JOIN db_str t ON t.id=r.title_sid AND t.type=1
LEFT JOIN db_str d ON d.id=r.desc_sid AND d.type=4
WHERE a.enabled=1 ORDER BY a.id
SQL

my $sql_prereqs = <<'SQL';
SELECT a.id, p.aa_id, p.points FROM aa_ability a
JOIN aa_rank_prereqs p ON p.rank_id = a.first_rank_id WHERE a.enabled=1
SQL

my @rows;
for my $line (split /\n/, dbq($sql_rows)) {
    chomp $line;
    next unless $line =~ /\S/;
    my ($id, $name, $cost, $ranks, $desc) = split /\t/, $line, 5;
    next unless defined $id && $id =~ /^\d+$/;
    push @rows, {
        id   => $id,
        name => $name,
        cost => ($cost && $cost >= 1) ? $cost : 1,
        mr   => ($ranks && $ranks >= 1) ? $ranks : 1,
        desc => (defined $desc ? $desc : ''),
    };
}

my %pr;
for my $line (split /\n/, dbq($sql_prereqs)) {
    chomp $line;
    next unless $line =~ /\S/;
    my ($id, $req, $pts) = split /\t/, $line;
    next unless defined $pts;
    push @{ $pr{$id} }, "{a=$req,r=$pts}";
}

sub esc {
    my $s = shift // '';
    $s =~ s/\\/\\\\/g;
    $s =~ s/"/\\"/g;
    return $s;
}

die "refusing to write an empty pool -- the database query returned nothing\n" unless @rows;

print "-- AUTO-GENERATED by custom/tools/gen_aa_pool.pl -- DO NOT HAND EDIT.\n";
printf "-- The death picker's pool: every ENABLED AA, %d of them.\n", scalar @rows;
print "-- Fields: id,name,icon,cls,cost,era,mr(rank count),desc,pr(prereqs). All sit at pool[1]\n";
print "-- because every rank is purchasable at level 1 (custom/sql/aotv4_aa_level1.sql).\n";
print "-- ⚠️ Regenerate after enabling or disabling ANY AA: a pool entry that is not enabled gets\n";
print "-- offered and then silently refused, with no message anywhere.\n";
print "return {\n  [1] = {\n";
for my $r (@rows) {
    my $prs = $pr{ $r->{id} } ? sprintf(',pr={%s}', join(',', @{ $pr{ $r->{id} } })) : '';
    printf "    {id=%s,name=\"%s\",icon=155,cls=65535,cost=%s,era=0,mr=%s,desc=\"%s\"%s},\n",
        $r->{id}, esc($r->{name}), $r->{cost}, $r->{mr}, esc($r->{desc}), $prs;
}
print "  },\n}\n";
