#!/usr/bin/perl
# =============================================================================================
# AoTv4 -- capture hand-placed hub spawns as a PORTABLE migration body            2026-08-17
#
#   perl .devcontainer/custom/tools/gen_hub_spawns.pl [first_npc] [last_npc] > body.sql
#   (defaults: 2000600 2000629 -- the twenty hub guards plus the ten Titan Hall induction NPCs)
#
# Reads the spawngroup / spawnentry / spawn2 chain this dev database holds for those npc ids and
# emits SQL that recreates it on ANOTHER database. Paste the output into a ManifestEntry.
#
# WHY THIS EXISTS
# `npc_types` only says what an NPC *is*; the three-table spawn chain is what puts one in the world.
# Placement is done by hand in game (`#npctypespawn <id>` then target it and `#npcspawn add 1200`),
# which writes rows into THIS database and nowhere else -- so without this step the hub NPCs exist on
# live and are invisible, which is the section 2 trap the whole hub work has already been bitten by.
#
# ⚠️⚠️ IT MUST NOT EMIT THE LOCAL spawn2 / spawngroup IDS. They are AUTO_INCREMENT values that mean
# nothing on another database -- the manifest already records this for the iceclad waypoint cleanup
# ("KEYED ON DISTANCE FROM THE WAYPOINT, NOT ON spawn2 IDS. Those ids are not guaranteed to..."), and
# hardcoding them here would either collide with unrelated live rows or overwrite them. The emitted
# SQL therefore allocates a contiguous block ABOVE whatever the target database is already using and
# derives every id from that one number.
#
# ⚠️ Every per-row spawn2 value is carried through as it actually is, rather than assumed uniform:
# `freeporttheater` alone holds three distinct settings combinations, so "they are all the same" is
# already false in the zone this was written for.
#
# ⚠️ The emitted block is guarded by the caller's ManifestEntry `.check`, not by INSERT IGNORE: the
# ids are computed, so a second run would allocate a DIFFERENT block and duplicate every spawn rather
# than collide. Key the check on the spawn2 rows for the zone -- see the suggested check printed at
# the foot of the output.
# =============================================================================================
use strict;
use warnings;

my $FIRST = shift // 2000600;
my $LAST  = shift // 2000629;

my $DB = 'mysql -h127.0.0.1 -upeq -ppeqpass peq -N -e';

sub dbq {
    my $sql = shift;
    $sql =~ s/\s+/ /g;
    $sql =~ s/"/\\"/g;
    return `$DB "$sql" 2>/dev/null`;
}

# One row per placed NPC. Ordered by npc id so the emitted block is stable across runs -- a
# regenerated body that differs only in row order produces a noisy, unreviewable diff.
my $sql = qq{
SELECT se.npcID, sg.name, s2.zone, s2.version, s2.x, s2.y, s2.z, s2.heading,
       s2.respawntime, s2.variance, s2.pathgrid, s2.path_when_zone_idle,
       s2._condition, s2.cond_value, s2.animation
FROM spawnentry se
JOIN spawngroup sg ON sg.id = se.spawngroupID
JOIN spawn2 s2 ON s2.spawngroupID = se.spawngroupID
WHERE se.npcID BETWEEN $FIRST AND $LAST
ORDER BY se.npcID
};

my @rows;
for my $line (split /\n/, dbq($sql)) {
    chomp $line;
    next unless $line =~ /\S/;
    my @f = split /\t/, $line;
    next unless @f >= 15 && $f[0] =~ /^\d+$/;
    push @rows, \@f;
}

if (!@rows) {
    print STDERR "gen_hub_spawns: no spawns found for npc ids $FIRST-$LAST.\n";
    print STDERR "Place them in game first: #npctypespawn <id>, target it, then #npcspawn add 1200\n";
    exit 1;
}

sub q_ { my $s = shift // ''; $s =~ s/'/''/g; return "'$s'" }

my %zones;
$zones{$_->[2]} = 1 for @rows;
my $zonelist = join ', ', map { "'$_'" } sort keys %zones;

print "-- AoTv4 hub spawns, generated by custom/tools/gen_hub_spawns.pl -- DO NOT HAND EDIT.\n";
print "-- npc ids $FIRST-$LAST, " . scalar(@rows) . " spawn points, zone(s) $zonelist.\n";
print "CREATE TEMPORARY TABLE aotv4_hub_spawn (\n";
print "  n INT, npc INT, gname VARCHAR(50), zone VARCHAR(32), ver INT,\n";
print "  x FLOAT, y FLOAT, z FLOAT, h FLOAT, respawn INT, variance INT,\n";
print "  pathgrid INT, pwzi INT, cond_ INT, condval INT, anim INT\n";
print ");\n";
print "INSERT INTO aotv4_hub_spawn VALUES\n";

my @vals;
my $n = 0;
for my $r (@rows) {
    my ($npc, $gname, $zone, $ver, $x, $y, $z, $h,
        $respawn, $variance, $pathgrid, $pwzi, $cond, $condval, $anim) = @$r;
    push @vals, sprintf("  (%d,%d,%s,%s,%d,%s,%s,%s,%s,%d,%d,%d,%d,%d,%d,%d)",
        $n++, $npc, q_($gname), q_($zone), $ver, $x, $y, $z, $h,
        $respawn, $variance, $pathgrid, $pwzi, $cond, $condval, $anim);
}
print join(",\n", @vals), ";\n\n";

print <<'SQL';
-- ⚠️⚠️ ONE ALLOCATION FOR ALL THREE TABLES. spawn2.id and spawngroup.id are independent
-- AUTO_INCREMENT sequences, so the block has to clear the HIGHEST of the two or a spawngroup id can
-- land on a spawn2 id that is already taken (and vice versa) on a database whose two sequences have
-- drifted apart. Taking the greatest of both and using one offset keeps the pairing 1:1, which is
-- what every later lookup assumes.
SET @aotv4_base := (SELECT GREATEST(
  (SELECT COALESCE(MAX(id), 0) FROM spawn2),
  (SELECT COALESCE(MAX(id), 0) FROM spawngroup)
) + 1);

INSERT INTO spawngroup
  (id, name, spawn_limit, dist, max_x, min_x, max_y, min_y, delay, mindelay, despawn, despawn_timer, wp_spawns)
SELECT @aotv4_base + n, gname, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 FROM aotv4_hub_spawn;

-- ⚠️ min_expansion / max_expansion -1 on BOTH spawnentry and spawn2. This server runs Classic
-- (Expansion:CurrentExpansion = 0), so anything left at a real expansion number is content-filtered
-- out and the NPC simply never appears -- with nothing logged. Same reason the PoK books carry -1.
INSERT INTO spawnentry
  (spawngroupID, npcID, chance, condition_value_filter, min_time, max_time, min_expansion, max_expansion, content_flags, content_flags_disabled)
SELECT @aotv4_base + n, npc, 100, 1, 0, 0, -1, -1, '', '' FROM aotv4_hub_spawn;

INSERT INTO spawn2
  (id, spawngroupID, zone, version, x, y, z, heading, respawntime, variance, pathgrid, path_when_zone_idle, _condition, cond_value, animation, min_expansion, max_expansion, content_flags, content_flags_disabled)
SELECT @aotv4_base + n, @aotv4_base + n, zone, ver, x, y, z, h, respawn, variance, pathgrid, pwzi, cond_, condval, anim, -1, -1, '', ''
FROM aotv4_hub_spawn;

DROP TEMPORARY TABLE aotv4_hub_spawn;
SQL

print "\n-- Suggested ManifestEntry check (scope by ZONE, never by an id band -- an id range is a\n";
print "-- guess about what a database contains, a zone name is a fact):\n";
for my $z (sort keys %zones) {
    print "--   .check     = \"SELECT s2.id FROM spawn2 s2 JOIN spawnentry se ON se.spawngroupID = s2.spawngroupID \"\n";
    print "--                \"WHERE s2.zone = '$z' AND se.npcID BETWEEN $FIRST AND $LAST\"\n";
    print "--   .condition = \"empty\"\n";
}
