#!/usr/bin/perl
# Generate uifiles_default/EQUI_AoTSpellChoiceWnd.xml (the level-up reward picker).
#
# The picker needs a per-row spell ICON, but this RoF2 build maps no runtime icon API:
# CTextureAnimation::SetCurCell, CSidlManager::FindAnimation and CListWnd::SetItemIcon are all
# absent from the address table, so a texture cell cannot be chosen from code.  The way around it
# is to move the choice into the XML: define one Ui2DAnimation per icon (each already pointing at
# the right cell of the right spellsNN.tga) and one Button per (row, icon).  They all start hidden
# and the dll shows only the one whose icon index the server sent.  CXWnd::Show IS mapped, so
# nothing here depends on an API we do not have.
#
# That trade only works because the reward pool is small: the 113 custom spells (spell_icons.lua)
# and the combat-skill rewards (skill_pool.lua) use just 22 distinct icons between them.  If the
# pool grows new icons, add them to @ICONS and regenerate -- an unknown icon simply draws nothing.
#
#   perl aotv4_client_install/gen_choice_xml.pl

use strict;
use warnings;

my $ROWS = 3;                                     # the server always offers three

# Distinct icons the reward pool can produce, READ from the generated Lua rather than hardcoded --
# the pool changes (it went from a 113-spell custom set to the ~2600-spell stock set) and a
# hardcoded list silently drifts into blank icons.  The dll does not carry a matching list either:
# it looks the button up by name at runtime, so this file is the single source of truth.
my @ICONS = do {
    my %seen;
    for my $f ("/src/.devcontainer/repo/quests/lua_modules/spell_icons.lua",
               "/src/.devcontainer/repo/quests/lua_modules/skill_pool.lua") {
        open(my $fh, '<', $f) or die "$f: $!";
        while (my $l = <$fh>) {
            $seen{$1} = 1 while $l =~ /(?:^\s*\[\d+\]\s*=\s*|icon\s*=\s*)(\d+)/g;
        }
        close $fh;
    }
    # The client's EQUI_Animations.xml declares Spells01..Spells07 only, so icon indices above
    # 7*36-1 = 251 have no texture to point at.  Referencing one is not an error, it just draws an
    # empty square, so skip those: the row keeps its name and description and simply shows no icon.
    sort { $a <=> $b } grep { $_ > 0 && $_ <= 251 } keys %seen;
};

my $CELL = 40;                                    # spell icons are 40x40
my $COLS = 6;                                     # 6 per row on a 240-wide sheet

# The window carries THREE tabs now: Choose (the reward cards), Known and Pool. The card layout
# below is unchanged -- it just lives on a page instead of directly on the screen.
#
# ⚠️ TAB_Y is the height of the tab strip. Every page sits at Y=TAB_Y inside the screen, and each
# page's own pieces are positioned relative to THAT, so the card coordinates did not have to move.
my ($WIN_CX, $WIN_CY) = (430, 500);
my $TAB_Y             = 22;
# ⚠️ Subtract the FRAME too, not just the tab strip. The window frame eats roughly 20px at the top
# (title bar) and 8 at the bottom, so a page of (WIN_CY - TAB_Y - 4) placed at Y=TAB_Y ended 24px
# BELOW what the window can show and the detail pane hung out of the bottom of the frame.
my $PAGE_CY           = $WIN_CY - $TAB_Y - 32;
my ($ROW_Y0, $ROW_H)  = (34, 58);
my $ICON_X            = 14;
my ($NAME_X, $NAME_W) = (64, 236);
# Label font index, as used by stock EQUI files: 3 is the ordinary body size, 4 and 5 are the
# header sizes (EQUI_TradeskillWnd uses 4, EQUI_BazaarConfirmationWnd's "Item Name" uses 5).
my $NAME_FONT = 4;
my ($BTN_X, $BTN_W, $BTN_H) = (310, 102, 26);
my ($DET_X, $DET_W) = (10, 406);
# ⚠️ DET_H was 174 (detail box ending at 412). It is 140 now to make room for the Reroll button
# underneath. The box could NOT simply move up instead: the three reward cards occupy 34..208
# (ROW_Y0 + 3*ROW_H) and DETNAME_Y sits directly below them, so the only spare space on the page is
# at the bottom. Page height is PAGE_CY (446), so the button at 384..410 still clears the frame.
my ($DETNAME_Y, $DET_Y, $DET_H) = (212, 238, 140);
my ($REROLL_W, $REROLL_H) = (170, 26);
my ($COST_W, $COST_GAP)   = (150, 10);
my $REROLL_Y = $DET_Y + $DET_H + 6;
# Cost box and button sit side by side, the pair centred under the description.
my $COST_X   = $DET_X + int(($DET_W - ($COST_W + $COST_GAP + $REROLL_W)) / 2);
my $REROLL_X = $COST_X + $COST_W + $COST_GAP;

my @out;
sub w { push @out, $_[0]; }

w('<?xml version="1.0" encoding="us-ascii"?>');
w('<XML ID="EQInterfaceDefinitionLanguage">');
w("\t" . '<Schema xmlns="EverQuestData" xmlns:dt="EverQuestDataTypes" />');
w('');
w("\t" . '<!-- AoTv4 level-up reward picker (CCustomWnd "AoTSpellChoiceWnd").  GENERATED by');
w("\t" . '     aotv4_client_install/gen_choice_xml.pl; regenerate rather than hand editing, or the');
w("\t" . '     icon table here and the dll\'s ASC_Icon lookup will drift apart.');
w('');
w("\t" . '     Three reward cards, each an icon, a name, a one line summary and a button, over a');
w("\t" . '     shared description pane.  The icon is a stack of hidden buttons (one per known icon');
w("\t" . '     index) because this client build exposes no runtime way to pick a texture cell; the');
w("\t" . '     dll just shows the right one.  See the generator header for why.');
w('');
w("\t" . '     Protocol is unchanged from the old GDI overlay, so the server needs no edits:');
w("\t" . '       server to dll : "SPELLCHOICEDATA name|icon^name|icon^name|icon"');
w("\t" . '                       "SPELLDESCDATA  desc^desc^desc"');
w("\t" . '       dll to server : "/say spellpick <1-3>"');
w('');
w("\t" . '     NEVER put a double hyphen inside an XML comment.  It is illegal XML, the SIDL parser');
w("\t" . '     aborts the whole file, and the client CRASHES at UI load.  Validate with');
w("\t" . '     aotv4_client_install/validate_ui_xml.sh before copying. -->');
w('');

w("\t" . '<!-- Icon cells.  sheet = icon/36 + 1, cell = icon mod 36, laid out 6 across at 40x40. -->');
for my $ic (@ICONS) {
    my $sheet = int($ic / 36) + 1;
    my $cell  = $ic % 36;
    my $x     = ($cell % $COLS) * $CELL;
    my $y     = int($cell / $COLS) * $CELL;
    w("\t<Ui2DAnimation item=\"A_AoTIcon$ic\">");
    w("\t\t<Cycle>false</Cycle>");
    w("\t\t<Frames>");
    # Capital S.  SIDL resolves this against the texture registry built from the TextureInfo
    # entries in EQUI_Animations.xml, which spell them "Spells01.tga", and that lookup is CASE
    # SENSITIVE.  Lowercase silently resolves to nothing: the button is created and shown but
    # draws an empty 40x40 hole, with no UIErrorLog entry.  (Our GDI icon loader gets away with
    # lowercase because it opens the file through Windows, which is not case sensitive.)
    w(sprintf("\t\t\t<Texture>Spells%02d.tga</Texture>", $sheet));
    w("\t\t\t<Location><X>$x</X><Y>$y</Y></Location>");
    w("\t\t\t<Size><CX>$CELL</CX><CY>$CELL</CY></Size>");
    w("\t\t\t<Hotspot><X>0</X><Y>0</Y></Hotspot>");
    w("\t\t\t<Duration>1000</Duration>");
    w("\t\t</Frames>");
    w("\t</Ui2DAnimation>");
}
w('');

my @pieces;

w("\t<Label item=\"ASC_Title\">");
w("\t\t<ScreenID>ASC_Title</ScreenID>");
w("\t\t<RelativePosition>true</RelativePosition>");
w("\t\t<Location><X>12</X><Y>8</Y></Location>");
w("\t\t<Size><CX>" . ($WIN_CX - 24) . "</CX><CY>18</CY></Size>");
w("\t\t<Text>Choose your reward</Text>");
w("\t\t<TextColor><R>240</R><G>224</G><B>150</B></TextColor>");
w("\t\t<NoWrap>true</NoWrap>");
w("\t</Label>");
w('');
push @pieces, 'ASC_Title';

for my $r (0 .. $ROWS - 1) {
    my $ry = $ROW_Y0 + $r * $ROW_H;
    w("\t<!-- reward row $r -->");
    for my $ic (@ICONS) {
        w("\t<Button item=\"ASC_Icon${r}_$ic\">");
        w("\t\t<ScreenID>ASC_Icon${r}_$ic</ScreenID>");
        w("\t\t<RelativePosition>true</RelativePosition>");
        w("\t\t<Location><X>$ICON_X</X><Y>" . ($ry + 4) . "</Y></Location>");
        w("\t\t<Size><CX>$CELL</CX><CY>$CELL</CY></Size>");
        w("\t\t<Text></Text>");
        # Inline draw template, which is the form stock EQUI_Inventory.xml uses for its icon
        # buttons.  A NAMED ButtonDrawTemplate has to register itself before the screen is built,
        # and that is the step that silently failed here: the button was found and shown but drew
        # nothing.  Every state points at the same cell, so the icon looks static rather than
        # like a button.
        w("\t\t<ButtonDrawTemplate>");
        w("\t\t\t<$_>A_AoTIcon$ic</$_>") for qw(Normal Pressed Flyby Disabled PressedFlyby);
        w("\t\t</ButtonDrawTemplate>");
        w("\t</Button>");
        push @pieces, "ASC_Icon${r}_$ic";
    }

    # No summary line under the name: the description pane below already carries the full text,
    # and the truncated copy just repeated it badly.  With the name alone, centre it against the
    # 40px icon rather than top aligning it.
    w("\t<Label item=\"ASC_Name$r\">");
    w("\t\t<ScreenID>ASC_Name$r</ScreenID>");
    w("\t\t<RelativePosition>true</RelativePosition>");
    w("\t\t<Location><X>$NAME_X</X><Y>" . ($ry + 13) . "</Y></Location>");
    w("\t\t<Size><CX>$NAME_W</CX><CY>24</CY></Size>");
    w("\t\t<Text></Text>");
    w("\t\t<Font>$NAME_FONT</Font>");
    w("\t\t<TextColor><R>245</R><G>235</G><B>190</B></TextColor>");
    w("\t\t<NoWrap>true</NoWrap>");
    w("\t</Label>");
    push @pieces, "ASC_Name$r";

    w("\t<Button item=\"ASC_Pick$r\">");
    w("\t\t<ScreenID>ASC_Pick$r</ScreenID>");
    w("\t\t<RelativePosition>true</RelativePosition>");
    w("\t\t<Location><X>$BTN_X</X><Y>" . ($ry + 10) . "</Y></Location>");
    w("\t\t<Size><CX>$BTN_W</CX><CY>$BTN_H</CY></Size>");
    w("\t\t<Text>Select</Text>");
    w("\t\t<TextColor><R>140</R><G>255</G><B>140</B></TextColor>");
    w("\t\t<Template>BDT_Normal</Template>");
    w("\t</Button>");
    push @pieces, "ASC_Pick$r";
    w('');
}

w("\t" . '<!-- Title of whichever row is previewed.  A real Label rather than a line of STML because');
w("\t" . '     STML on this build has no font size tag (colour and line break are the only ones');
w("\t" . '     confirmed), so this is the only way it can match the reward titles above it. -->');
w("\t<Label item=\"ASC_DetailName\">");
w("\t\t<ScreenID>ASC_DetailName</ScreenID>");
w("\t\t<RelativePosition>true</RelativePosition>");
w("\t\t<Location><X>" . ($DET_X + 4) . "</X><Y>$DETNAME_Y</Y></Location>");
w("\t\t<Size><CX>" . ($DET_W - 8) . "</CX><CY>24</CY></Size>");
w("\t\t<Text></Text>");
w("\t\t<Font>$NAME_FONT</Font>");
w("\t\t<TextColor><R>245</R><G>235</G><B>190</B></TextColor>");
w("\t\t<NoWrap>true</NoWrap>");
w("\t</Label>");
push @pieces, 'ASC_DetailName';
w('');

w("\t" . '<!-- Description of whichever row is previewed.  STML so it renders like the client\'s own');
w("\t" . '     spell text rather than something we drew ourselves. -->');
w("\t<STMLbox item=\"ASC_Detail\">");
w("\t\t<ScreenID>ASC_Detail</ScreenID>");
w("\t\t<DrawTemplate>WDT_Inner</DrawTemplate>");
w("\t\t<RelativePosition>true</RelativePosition>");
w("\t\t<Location><X>$DET_X</X><Y>$DET_Y</Y></Location>");
w("\t\t<Size><CX>$DET_W</CX><CY>$DET_H</CY></Size>");
w("\t\t<Style_Border>true</Style_Border>");
w("\t\t<Style_VScroll>true</Style_VScroll>");
w("\t\t<TextColor><R>240</R><G>240</G><B>240</B></TextColor>");
w("\t</STMLbox>");
w('');
push @pieces, 'ASC_Detail';

w("\t" . '<!-- What the next reroll costs.  An STMLbox rather than a Label purely because it draws a');
w("\t" . '     real bordered panel: Label has no confirmed border on this build, and an unbordered');
w("\t" . '     number floating beside the button does not read as a price field.  The dll fills it from');
w("\t" . '     the SPELLREROLLCOST line, because the price is per character and escalates, so the client');
w("\t" . '     cannot work it out and any hardcoded figure would be wrong after the first reroll. -->');
w("\t<STMLbox item=\"ASC_RerollCost\">");
w("\t\t<ScreenID>ASC_RerollCost</ScreenID>");
w("\t\t<DrawTemplate>WDT_Inner</DrawTemplate>");
w("\t\t<RelativePosition>true</RelativePosition>");
w("\t\t<Location><X>$COST_X</X><Y>$REROLL_Y</Y></Location>");
w("\t\t<Size><CX>$COST_W</CX><CY>$REROLL_H</CY></Size>");
w("\t\t<Style_Border>true</Style_Border>");
w("\t\t<TextColor><R>255</R><G>220</G><B>150</B></TextColor>");
w("\t</STMLbox>");
w('');
push @pieces, 'ASC_RerollCost';

w("\t" . '<!-- Replace these three rewards with three new ones, for coin.  The dll sends');
w("\t" . '     "/say spellreroll"; the SERVER prices it, checks the player can afford it and takes the');
w("\t" . '     money, so a modified client pressing this gets nothing but a refusal. -->');
w("\t<Button item=\"ASC_Reroll\">");
w("\t\t<ScreenID>ASC_Reroll</ScreenID>");
w("\t\t<RelativePosition>true</RelativePosition>");
w("\t\t<Location><X>$REROLL_X</X><Y>$REROLL_Y</Y></Location>");
w("\t\t<Size><CX>$REROLL_W</CX><CY>$REROLL_H</CY></Size>");
w("\t\t<Text>Reroll</Text>");
w("\t\t<TextColor><R>255</R><G>200</G><B>140</B></TextColor>");
w("\t\t<Template>BDT_Normal</Template>");
w("\t\t<TooltipReference>Pay the shown price for three different rewards</TooltipReference>");
w("\t</Button>");
w('');
push @pieces, 'ASC_Reroll';

# =================================================================================================
# Known and Pool tabs.
#
# These were originally a separate window (EQUI_AoTSpellJournalWnd.xml). They are folded in here so
# there is ONE spell window: the reward cards stay exactly as they were and simply become the first
# tab. The standalone Journal XML is kept as a backup but is no longer used.
#
# Both lists are plain Listboxes with a detail Listbox underneath, and BOTH are driven by
# core_spelljournal.cpp -- which builds its description text from the client's own spell record
# rather than from anything the server sends.
# =================================================================================================
my @known_pieces;
my @pool_pieces;

# ---- helpers so the two tabs cannot drift apart
sub listbox {
    my ($item, $y, $h, $cols, $vscroll) = @_;
    w("\t<Listbox item=\"$item\">");
    w("\t\t<ScreenID>$item</ScreenID>");
    w("\t\t<DrawTemplate>WDT_Inner</DrawTemplate>");
    w("\t\t<RelativePosition>true</RelativePosition>");
    w("\t\t<Location><X>$DET_X</X><Y>$y</Y></Location>");
    w("\t\t<Size><CX>$DET_W</CX><CY>$h</CY></Size>");
    w("\t\t<Style_Border>true</Style_Border>");
    w("\t\t<Style_VScroll>" . ($vscroll ? 'true' : 'false') . "</Style_VScroll>");
    for my $c (@$cols) {
        w("\t\t<Columns>");
        w("\t\t\t<Width>$c->[0]</Width>");
        w("\t\t\t<Heading>$c->[1]</Heading>") if defined $c->[1];
        w("\t\t</Columns>");
    }
    w("\t</Listbox>");
    w('');
}

my $LIST_Y = 8;
my $LIST_H = 240;
my $LDET_Y = $LIST_Y + $LIST_H + 8;
my $LDET_H = $PAGE_CY - $LDET_Y - 12;

# ---- Known tab
#
# ⚠️⚠️ THE KNOWN TAB IS A PERMANENT LIBRARY, NOT A VIEW OF THE SPELLBOOK. It lists every spell this
# character has ever been awarded, with the RANK it has been taken to -- both of which live in data
# buckets and survive the roguelite wipe. That is why it needs server data (SPELLRANKDATA) where it
# used to cost nothing at all.
#
# Two actions, with deliberately different scopes (aotv4_spell_ranks_sys):
#   KEEP     only a spell currently CARRIED, max 2. Survives death, at its earned rank.
#   UPGRADE  anything DISCOVERED. Rank is permanent character progress, so it is not hostage to
#            whether the spell happens to be in the book today.
#
# The requirement box sits between the detail pane and the buttons, in the same shape as the reroll
# price box on the Choose tab: it shows what the next rank costs and what the player is carrying, so
# a refused Upgrade explains itself instead of just failing.
# ⚠️⚠️ THE TWO BOXES ARE A MATCHED PAIR AND SHARE ONE HEIGHT. A first pass gave the description 94
# and the requirement box 52, which looked lopsided AND clipped: the requirement text is three lines
# ("Rank N requires" plus one per material) and needs about 60. Deriving both from the same figure
# means they cannot drift apart when the page is next re-laid out.
# ⚠️ The Known LIST is shortened to pay for it rather than stealing from the description -- the list
# scrolls, so losing a couple of visible rows costs nothing, whereas a clipped panel loses
# information outright.
my $KLIST_H = 200;                                  # Known list, shorter than the other tabs'
my $KBTN_H  = 24;
my $KBTN_Y  = $PAGE_CY - $KBTN_H - 8;
my $KDET_Y  = $LIST_Y + $KLIST_H + 8;
my $KBOX_H  = int((($KBTN_Y - 6) - $KDET_Y - 6) / 2);   # detail and requirement, equal
my $KREQ_Y  = $KDET_Y + $KBOX_H + 6;

# ⚠️ NO per-row level column. It carried the level the reward was taken at, which the band headers
# ("Taken at character level 31 to 40") already say -- and the exact number is actively misleading
# when the character is above the level cap: era_system.clamp_level runs BEFORE spell_choice.offer on
# a level up, so a character sitting at 40 with a cap of 35 is momentarily pulled to 35 and the award
# is honestly recorded at 35. The data is still kept and still drives the kept-spell forfeit; it is
# only the column that is gone.
listbox('ASC_KnownList', $LIST_Y, $KLIST_H,
        [[298, 'Spell'], [94, 'Rank']], 1);
listbox('ASC_KnownDetail', $KDET_Y, $KBOX_H, [[$DET_W - 12, undef]], 1);

# ⚠️ STMLbox, not Label. Section 3: a Label has no confirmed border on this build, and the reroll
# price box is an STMLbox for exactly this reason. It also has to wrap two requirement lines.
w("\t<STMLbox item=\"ASC_KnownReq\">");
w("\t\t<ScreenID>ASC_KnownReq</ScreenID>");
w("\t\t<DrawTemplate>WDT_Inner</DrawTemplate>");
w("\t\t<RelativePosition>true</RelativePosition>");
# ⚠️ X and width MUST match the listbox helper's ($DET_X / $DET_W), not be re-derived. A first pass
# used 6 and $DET_W-12 and the requirement box sat 4px left of the description above it with a
# narrower right edge -- subtle, but two stacked panels that do not share their edges read as broken
# rather than as a design.
w("\t\t<Location><X>$DET_X</X><Y>$KREQ_Y</Y></Location>");
w("\t\t<Size><CX>$DET_W</CX><CY>$KBOX_H</CY></Size>");
w("\t\t<Style_Border>true</Style_Border>");
w("\t\t<Style_VScroll>false</Style_VScroll>");
w("\t\t<Text>Select a spell.</Text>");
w("\t</STMLbox>");
w('');

# ⚠️ <Template>BDT_Normal</Template>, NOT <ButtonDrawTemplate> -- the tag differs from the inline
# form the icon buttons use, and only the ~34 BDT_* names defined in EQUI_Templates.xml resolve.
# Anything else draws an empty hole with no error (section 3).
my $KBW = 96;
# ⚠️ Right-aligned to the SAME edge as the two panels above ($DET_X + $DET_W). Positioning from
# $DET_W alone ignores the panels' left offset and leaves the buttons 10px adrift of the column they
# belong to.
my $KBTN_R = $DET_X + $DET_W;
for my $b (['ASC_KnownKeep',    'Keep',    $KBTN_R - (2 * $KBW) - 8],
           ['ASC_KnownUpgrade', 'Upgrade', $KBTN_R - $KBW]) {
    my ($item, $text, $x) = @$b;
    w("\t<Button item=\"$item\">");
    w("\t\t<ScreenID>$item</ScreenID>");
    w("\t\t<RelativePosition>true</RelativePosition>");
    w("\t\t<Location><X>$x</X><Y>$KBTN_Y</Y></Location>");
    w("\t\t<Size><CX>$KBW</CX><CY>$KBTN_H</CY></Size>");
    w("\t\t<Text>$text</Text>");
    w("\t\t<TextColor><R>255</R><G>230</G><B>140</B></TextColor>");
    w("\t\t<Template>BDT_Normal</Template>");
    w("\t</Button>");
    w('');
}

push @known_pieces, 'ASC_KnownList', 'ASC_KnownDetail',
                    'ASC_KnownReq', 'ASC_KnownKeep', 'ASC_KnownUpgrade';

# ---- Pool tab: a level stepper above the list
w("\t<Button item=\"ASC_PoolPrev\">");
w("\t\t<ScreenID>ASC_PoolPrev</ScreenID>");
w("\t\t<RelativePosition>true</RelativePosition>");
w("\t\t<Location><X>$DET_X</X><Y>6</Y></Location>");
w("\t\t<Size><CX>60</CX><CY>24</CY></Size>");
w("\t\t<Text>&lt;&lt;</Text>");
w("\t\t<TextColor><R>255</R><G>255</G><B>255</B></TextColor>");
w("\t\t<Template>BDT_Normal</Template>");
w("\t</Button>");
w('');
w("\t<Label item=\"ASC_PoolLevel\">");
w("\t\t<ScreenID>ASC_PoolLevel</ScreenID>");
w("\t\t<RelativePosition>true</RelativePosition>");
w("\t\t<Location><X>" . ($DET_X + 66) . "</X><Y>10</Y></Location>");
w("\t\t<Size><CX>" . ($DET_W - 132) . "</CX><CY>20</CY></Size>");
w("\t\t<Text>Level</Text>");
w("\t\t<Font>$NAME_FONT</Font>");
w("\t\t<TextColor><R>245</R><G>235</G><B>190</B></TextColor>");
w("\t\t<AlignCenter>true</AlignCenter>");
w("\t\t<NoWrap>true</NoWrap>");
w("\t</Label>");
w('');
w("\t<Button item=\"ASC_PoolNext\">");
w("\t\t<ScreenID>ASC_PoolNext</ScreenID>");
w("\t\t<RelativePosition>true</RelativePosition>");
w("\t\t<Location><X>" . ($DET_X + $DET_W - 60) . "</X><Y>6</Y></Location>");
w("\t\t<Size><CX>60</CX><CY>24</CY></Size>");
w("\t\t<Text>&gt;&gt;</Text>");
w("\t\t<TextColor><R>255</R><G>255</G><B>255</B></TextColor>");
w("\t\t<Template>BDT_Normal</Template>");
w("\t</Button>");
w('');
listbox('ASC_PoolList', 36, $LIST_H - 28,
        [[298, 'Spell'], [94, 'Status']], 1);
listbox('ASC_PoolDetail', $LDET_Y, $LDET_H, [[$DET_W - 12, undef]], 1);
push @pool_pieces, 'ASC_PoolPrev', 'ASC_PoolLevel', 'ASC_PoolNext',
                   'ASC_PoolList', 'ASC_PoolDetail';

# ---- the three pages
sub page {
    my ($item, $tabtext, $pieces) = @_;
    w("\t<Page item=\"$item\">");
    w("\t\t<ScreenID>$item</ScreenID>");
    w("\t\t<RelativePosition>false</RelativePosition>");
    w("\t\t<Location><X>0</X><Y>$TAB_Y</Y></Location>");
    w("\t\t<Size><CX>$WIN_CX</CX><CY>$PAGE_CY</CY></Size>");
    w("\t\t<Style_VScroll>false</Style_VScroll>");
    w("\t\t<Style_HScroll>false</Style_HScroll>");
    w("\t\t<Style_Transparent>false</Style_Transparent>");
    w("\t\t<DrawTemplate>WDT_Def</DrawTemplate>");
    w("\t\t<TabText>$tabtext</TabText>");
    w("\t\t<TabTextColor><R>255</R><G>255</G><B>255</B></TabTextColor>");
    w("\t\t<TabTextActiveColor><R>255</R><G>255</G><B>0</B></TabTextActiveColor>");
    w("\t\t<Pieces>$_</Pieces>") for @$pieces;
    w("\t</Page>");
    w('');
}

page('ASC_ChoosePage', 'Choose', \@pieces);
page('ASC_KnownPage',  'Known',  \@known_pieces);
page('ASC_PoolPage',   'Pool',   \@pool_pieces);

w("\t<TabBox item=\"ASC_Tabs\">");
w("\t\t<ScreenID>ASC_Tabs</ScreenID>");
w("\t\t<RelativePosition>true</RelativePosition>");
w("\t\t<Location><X>0</X><Y>0</Y></Location>");
w("\t\t<Size><CX>$WIN_CX</CX><CY>$WIN_CY</CY></Size>");
w("\t\t<TabBorderTemplate>FT_DefTabBorder</TabBorderTemplate>");
w("\t\t<PageBorderTemplate>FT_DefPageBorder</PageBorderTemplate>");
w("\t\t<Pages>ASC_ChoosePage</Pages>");
w("\t\t<Pages>ASC_KnownPage</Pages>");
w("\t\t<Pages>ASC_PoolPage</Pages>");
w("\t</TabBox>");
w('');

w("\t<Screen item=\"AoTSpellChoiceWnd\">");
w("\t\t<RelativePosition>false</RelativePosition>");
w("\t\t<Location><X>300</X><Y>150</Y></Location>");
w("\t\t<Size><CX>$WIN_CX</CX><CY>$WIN_CY</CY></Size>");
w("\t\t<Text>Spells</Text>");
w("\t\t<Style_Transparent>false</Style_Transparent>");
w("\t\t<DrawTemplate>WDT_Def</DrawTemplate>");
w("\t\t<Style_Titlebar>true</Style_Titlebar>");
w("\t\t<Style_Closebox>true</Style_Closebox>");
w("\t\t<Style_Border>true</Style_Border>");
w("\t\t<Style_Sizable>false</Style_Sizable>");
w("\t\t<Escapable>true</Escapable>");
# ⚠️ The screen now holds ONLY the TabBox. Every other piece belongs to a page; listing one here as
# well would place it twice and it would draw outside the tab it belongs to.
w("\t\t<Pieces>ASC_Tabs</Pieces>");
w("\t</Screen>");
w('</XML>');

my $path = "/src/aotv4_client_install/uifiles_default/EQUI_AoTSpellChoiceWnd.xml";
open(my $fh, '>', $path) or die "$path: $!";
print $fh join("\n", @out), "\n";
close $fh;
printf "wrote %s: %d lines, %d icons, %d pieces\n", $path, scalar(@out), scalar(@ICONS), scalar(@pieces);
