#!/usr/bin/perl
# Generate uifiles_default/EQUI_AoTSpellChoiceWnd.xml (the level-up reward picker).
#
# The picker needs a per-row spell ICON, but this RoF2 build maps no runtime icon API:
# CTextureAnimation::SetCurCell, CSidlManager::FindAnimation and CListWnd::SetItemIcon are all
# absent from the address table, so a texture cell cannot be chosen from code.  The way around it
# is to move the choice into the XML: define one Ui2DAnimation per icon (each already pointing at
# the right cell of the right spellsNN.tga) and one Button per (row, icon).  They all start hidden
# and the dll shows only the one whose icon index the server sent.  CXWnd::Show IS mapped, so
# nothing here depends on an API we do not have.
#
# That trade only works because the reward pool is small: the 113 custom spells (spell_icons.lua)
# and the combat-skill rewards (skill_pool.lua) use just 22 distinct icons between them.  If the
# pool grows new icons, add them to @ICONS and regenerate -- an unknown icon simply draws nothing.
#
#   perl aotv4_client_install/gen_choice_xml.pl

use strict;
use warnings;

my $ROWS = 3;                                     # the server always offers three

# Distinct icons the reward pool can produce, READ from the generated Lua rather than hardcoded --
# the pool changes (it went from a 113-spell custom set to the ~2600-spell stock set) and a
# hardcoded list silently drifts into blank icons.  The dll does not carry a matching list either:
# it looks the button up by name at runtime, so this file is the single source of truth.
my @ICONS = do {
    my %seen;
    for my $f ("/src/.devcontainer/repo/quests/lua_modules/spell_icons.lua",
               "/src/.devcontainer/repo/quests/lua_modules/skill_pool.lua") {
        open(my $fh, '<', $f) or die "$f: $!";
        while (my $l = <$fh>) {
            $seen{$1} = 1 while $l =~ /(?:^\s*\[\d+\]\s*=\s*|icon\s*=\s*)(\d+)/g;
        }
        close $fh;
    }
    # The client's EQUI_Animations.xml declares Spells01..Spells07 only, so icon indices above
    # 7*36-1 = 251 have no texture to point at.  Referencing one is not an error, it just draws an
    # empty square, so skip those: the row keeps its name and description and simply shows no icon.
    sort { $a <=> $b } grep { $_ > 0 && $_ <= 251 } keys %seen;
};

my $CELL = 40;                                    # spell icons are 40x40
my $COLS = 6;                                     # 6 per row on a 240-wide sheet

# The window carries THREE tabs now: Choose (the reward cards), Known and Pool. The card layout
# below is unchanged -- it just lives on a page instead of directly on the screen.
#
# ⚠️ TAB_Y is the height of the tab strip. Every page sits at Y=TAB_Y inside the screen, and each
# page's own pieces are positioned relative to THAT, so the card coordinates did not have to move.
my ($WIN_CX, $WIN_CY) = (430, 500);
my $TAB_Y             = 22;
# ⚠️ Subtract the FRAME too, not just the tab strip. The window frame eats roughly 20px at the top
# (title bar) and 8 at the bottom, so a page of (WIN_CY - TAB_Y - 4) placed at Y=TAB_Y ended 24px
# BELOW what the window can show and the detail pane hung out of the bottom of the frame.
my $PAGE_CY           = $WIN_CY - $TAB_Y - 32;
my ($ROW_Y0, $ROW_H)  = (34, 58);
my $ICON_X            = 14;
my ($NAME_X, $NAME_W) = (64, 236);
# Label font index, as used by stock EQUI files: 3 is the ordinary body size, 4 and 5 are the
# header sizes (EQUI_TradeskillWnd uses 4, EQUI_BazaarConfirmationWnd's "Item Name" uses 5).
my $NAME_FONT = 4;
my ($BTN_X, $BTN_W, $BTN_H) = (310, 102, 26);
my ($DET_X, $DET_W) = (10, 406);
my ($DETNAME_Y, $DET_Y, $DET_H) = (212, 238, 174);

my @out;
sub w { push @out, $_[0]; }

w('<?xml version="1.0" encoding="us-ascii"?>');
w('<XML ID="EQInterfaceDefinitionLanguage">');
w("\t" . '<Schema xmlns="EverQuestData" xmlns:dt="EverQuestDataTypes" />');
w('');
w("\t" . '<!-- AoTv4 level-up reward picker (CCustomWnd "AoTSpellChoiceWnd").  GENERATED by');
w("\t" . '     aotv4_client_install/gen_choice_xml.pl; regenerate rather than hand editing, or the');
w("\t" . '     icon table here and the dll\'s ASC_Icon lookup will drift apart.');
w('');
w("\t" . '     Three reward cards, each an icon, a name, a one line summary and a button, over a');
w("\t" . '     shared description pane.  The icon is a stack of hidden buttons (one per known icon');
w("\t" . '     index) because this client build exposes no runtime way to pick a texture cell; the');
w("\t" . '     dll just shows the right one.  See the generator header for why.');
w('');
w("\t" . '     Protocol is unchanged from the old GDI overlay, so the server needs no edits:');
w("\t" . '       server to dll : "SPELLCHOICEDATA name|icon^name|icon^name|icon"');
w("\t" . '                       "SPELLDESCDATA  desc^desc^desc"');
w("\t" . '       dll to server : "/say spellpick <1-3>"');
w('');
w("\t" . '     NEVER put a double hyphen inside an XML comment.  It is illegal XML, the SIDL parser');
w("\t" . '     aborts the whole file, and the client CRASHES at UI load.  Validate with');
w("\t" . '     aotv4_client_install/validate_ui_xml.sh before copying. -->');
w('');

w("\t" . '<!-- Icon cells.  sheet = icon/36 + 1, cell = icon mod 36, laid out 6 across at 40x40. -->');
for my $ic (@ICONS) {
    my $sheet = int($ic / 36) + 1;
    my $cell  = $ic % 36;
    my $x     = ($cell % $COLS) * $CELL;
    my $y     = int($cell / $COLS) * $CELL;
    w("\t<Ui2DAnimation item=\"A_AoTIcon$ic\">");
    w("\t\t<Cycle>false</Cycle>");
    w("\t\t<Frames>");
    # Capital S.  SIDL resolves this against the texture registry built from the TextureInfo
    # entries in EQUI_Animations.xml, which spell them "Spells01.tga", and that lookup is CASE
    # SENSITIVE.  Lowercase silently resolves to nothing: the button is created and shown but
    # draws an empty 40x40 hole, with no UIErrorLog entry.  (Our GDI icon loader gets away with
    # lowercase because it opens the file through Windows, which is not case sensitive.)
    w(sprintf("\t\t\t<Texture>Spells%02d.tga</Texture>", $sheet));
    w("\t\t\t<Location><X>$x</X><Y>$y</Y></Location>");
    w("\t\t\t<Size><CX>$CELL</CX><CY>$CELL</CY></Size>");
    w("\t\t\t<Hotspot><X>0</X><Y>0</Y></Hotspot>");
    w("\t\t\t<Duration>1000</Duration>");
    w("\t\t</Frames>");
    w("\t</Ui2DAnimation>");
}
w('');

my @pieces;

w("\t<Label item=\"ASC_Title\">");
w("\t\t<ScreenID>ASC_Title</ScreenID>");
w("\t\t<RelativePosition>true</RelativePosition>");
w("\t\t<Location><X>12</X><Y>8</Y></Location>");
w("\t\t<Size><CX>" . ($WIN_CX - 24) . "</CX><CY>18</CY></Size>");
w("\t\t<Text>Choose your reward</Text>");
w("\t\t<TextColor><R>240</R><G>224</G><B>150</B></TextColor>");
w("\t\t<NoWrap>true</NoWrap>");
w("\t</Label>");
w('');
push @pieces, 'ASC_Title';

for my $r (0 .. $ROWS - 1) {
    my $ry = $ROW_Y0 + $r * $ROW_H;
    w("\t<!-- reward row $r -->");
    for my $ic (@ICONS) {
        w("\t<Button item=\"ASC_Icon${r}_$ic\">");
        w("\t\t<ScreenID>ASC_Icon${r}_$ic</ScreenID>");
        w("\t\t<RelativePosition>true</RelativePosition>");
        w("\t\t<Location><X>$ICON_X</X><Y>" . ($ry + 4) . "</Y></Location>");
        w("\t\t<Size><CX>$CELL</CX><CY>$CELL</CY></Size>");
        w("\t\t<Text></Text>");
        # Inline draw template, which is the form stock EQUI_Inventory.xml uses for its icon
        # buttons.  A NAMED ButtonDrawTemplate has to register itself before the screen is built,
        # and that is the step that silently failed here: the button was found and shown but drew
        # nothing.  Every state points at the same cell, so the icon looks static rather than
        # like a button.
        w("\t\t<ButtonDrawTemplate>");
        w("\t\t\t<$_>A_AoTIcon$ic</$_>") for qw(Normal Pressed Flyby Disabled PressedFlyby);
        w("\t\t</ButtonDrawTemplate>");
        w("\t</Button>");
        push @pieces, "ASC_Icon${r}_$ic";
    }

    # No summary line under the name: the description pane below already carries the full text,
    # and the truncated copy just repeated it badly.  With the name alone, centre it against the
    # 40px icon rather than top aligning it.
    w("\t<Label item=\"ASC_Name$r\">");
    w("\t\t<ScreenID>ASC_Name$r</ScreenID>");
    w("\t\t<RelativePosition>true</RelativePosition>");
    w("\t\t<Location><X>$NAME_X</X><Y>" . ($ry + 13) . "</Y></Location>");
    w("\t\t<Size><CX>$NAME_W</CX><CY>24</CY></Size>");
    w("\t\t<Text></Text>");
    w("\t\t<Font>$NAME_FONT</Font>");
    w("\t\t<TextColor><R>245</R><G>235</G><B>190</B></TextColor>");
    w("\t\t<NoWrap>true</NoWrap>");
    w("\t</Label>");
    push @pieces, "ASC_Name$r";

    w("\t<Button item=\"ASC_Pick$r\">");
    w("\t\t<ScreenID>ASC_Pick$r</ScreenID>");
    w("\t\t<RelativePosition>true</RelativePosition>");
    w("\t\t<Location><X>$BTN_X</X><Y>" . ($ry + 10) . "</Y></Location>");
    w("\t\t<Size><CX>$BTN_W</CX><CY>$BTN_H</CY></Size>");
    w("\t\t<Text>Select</Text>");
    w("\t\t<TextColor><R>140</R><G>255</G><B>140</B></TextColor>");
    w("\t\t<Template>BDT_Normal</Template>");
    w("\t</Button>");
    push @pieces, "ASC_Pick$r";
    w('');
}

w("\t" . '<!-- Title of whichever row is previewed.  A real Label rather than a line of STML because');
w("\t" . '     STML on this build has no font size tag (colour and line break are the only ones');
w("\t" . '     confirmed), so this is the only way it can match the reward titles above it. -->');
w("\t<Label item=\"ASC_DetailName\">");
w("\t\t<ScreenID>ASC_DetailName</ScreenID>");
w("\t\t<RelativePosition>true</RelativePosition>");
w("\t\t<Location><X>" . ($DET_X + 4) . "</X><Y>$DETNAME_Y</Y></Location>");
w("\t\t<Size><CX>" . ($DET_W - 8) . "</CX><CY>24</CY></Size>");
w("\t\t<Text></Text>");
w("\t\t<Font>$NAME_FONT</Font>");
w("\t\t<TextColor><R>245</R><G>235</G><B>190</B></TextColor>");
w("\t\t<NoWrap>true</NoWrap>");
w("\t</Label>");
push @pieces, 'ASC_DetailName';
w('');

w("\t" . '<!-- Description of whichever row is previewed.  STML so it renders like the client\'s own');
w("\t" . '     spell text rather than something we drew ourselves. -->');
w("\t<STMLbox item=\"ASC_Detail\">");
w("\t\t<ScreenID>ASC_Detail</ScreenID>");
w("\t\t<DrawTemplate>WDT_Inner</DrawTemplate>");
w("\t\t<RelativePosition>true</RelativePosition>");
w("\t\t<Location><X>$DET_X</X><Y>$DET_Y</Y></Location>");
w("\t\t<Size><CX>$DET_W</CX><CY>$DET_H</CY></Size>");
w("\t\t<Style_Border>true</Style_Border>");
w("\t\t<Style_VScroll>true</Style_VScroll>");
w("\t\t<TextColor><R>240</R><G>240</G><B>240</B></TextColor>");
w("\t</STMLbox>");
w('');
push @pieces, 'ASC_Detail';

# =================================================================================================
# Known and Pool tabs.
#
# These were originally a separate window (EQUI_AoTSpellJournalWnd.xml). They are folded in here so
# there is ONE spell window: the reward cards stay exactly as they were and simply become the first
# tab. The standalone Journal XML is kept as a backup but is no longer used.
#
# Both lists are plain Listboxes with a detail Listbox underneath, and BOTH are driven by
# core_spelljournal.cpp -- which builds its description text from the client's own spell record
# rather than from anything the server sends.
# =================================================================================================
my @known_pieces;
my @pool_pieces;

# ---- helpers so the two tabs cannot drift apart
sub listbox {
    my ($item, $y, $h, $cols, $vscroll) = @_;
    w("\t<Listbox item=\"$item\">");
    w("\t\t<ScreenID>$item</ScreenID>");
    w("\t\t<DrawTemplate>WDT_Inner</DrawTemplate>");
    w("\t\t<RelativePosition>true</RelativePosition>");
    w("\t\t<Location><X>$DET_X</X><Y>$y</Y></Location>");
    w("\t\t<Size><CX>$DET_W</CX><CY>$h</CY></Size>");
    w("\t\t<Style_Border>true</Style_Border>");
    w("\t\t<Style_VScroll>" . ($vscroll ? 'true' : 'false') . "</Style_VScroll>");
    for my $c (@$cols) {
        w("\t\t<Columns>");
        w("\t\t\t<Width>$c->[0]</Width>");
        w("\t\t\t<Heading>$c->[1]</Heading>") if defined $c->[1];
        w("\t\t</Columns>");
    }
    w("\t</Listbox>");
    w('');
}

my $LIST_Y = 8;
my $LIST_H = 240;
my $LDET_Y = $LIST_Y + $LIST_H + 8;
my $LDET_H = $PAGE_CY - $LDET_Y - 12;

# ---- Known tab
listbox('ASC_KnownList', $LIST_Y, $LIST_H,
        [[46, 'Lvl'], [252, 'Spell'], [94, 'Type']], 1);
listbox('ASC_KnownDetail', $LDET_Y, $LDET_H, [[$DET_W - 12, undef]], 1);
push @known_pieces, 'ASC_KnownList', 'ASC_KnownDetail';

# ---- Pool tab: a level stepper above the list
w("\t<Button item=\"ASC_PoolPrev\">");
w("\t\t<ScreenID>ASC_PoolPrev</ScreenID>");
w("\t\t<RelativePosition>true</RelativePosition>");
w("\t\t<Location><X>$DET_X</X><Y>6</Y></Location>");
w("\t\t<Size><CX>60</CX><CY>24</CY></Size>");
w("\t\t<Text>&lt;&lt;</Text>");
w("\t\t<TextColor><R>255</R><G>255</G><B>255</B></TextColor>");
w("\t\t<Template>BDT_Normal</Template>");
w("\t</Button>");
w('');
w("\t<Label item=\"ASC_PoolLevel\">");
w("\t\t<ScreenID>ASC_PoolLevel</ScreenID>");
w("\t\t<RelativePosition>true</RelativePosition>");
w("\t\t<Location><X>" . ($DET_X + 66) . "</X><Y>10</Y></Location>");
w("\t\t<Size><CX>" . ($DET_W - 132) . "</CX><CY>20</CY></Size>");
w("\t\t<Text>Level</Text>");
w("\t\t<Font>$NAME_FONT</Font>");
w("\t\t<TextColor><R>245</R><G>235</G><B>190</B></TextColor>");
w("\t\t<AlignCenter>true</AlignCenter>");
w("\t\t<NoWrap>true</NoWrap>");
w("\t</Label>");
w('');
w("\t<Button item=\"ASC_PoolNext\">");
w("\t\t<ScreenID>ASC_PoolNext</ScreenID>");
w("\t\t<RelativePosition>true</RelativePosition>");
w("\t\t<Location><X>" . ($DET_X + $DET_W - 60) . "</X><Y>6</Y></Location>");
w("\t\t<Size><CX>60</CX><CY>24</CY></Size>");
w("\t\t<Text>&gt;&gt;</Text>");
w("\t\t<TextColor><R>255</R><G>255</G><B>255</B></TextColor>");
w("\t\t<Template>BDT_Normal</Template>");
w("\t</Button>");
w('');
listbox('ASC_PoolList', 36, $LIST_H - 28,
        [[298, 'Spell'], [94, 'Status']], 1);
listbox('ASC_PoolDetail', $LDET_Y, $LDET_H, [[$DET_W - 12, undef]], 1);
push @pool_pieces, 'ASC_PoolPrev', 'ASC_PoolLevel', 'ASC_PoolNext',
                   'ASC_PoolList', 'ASC_PoolDetail';

# ---- the three pages
sub page {
    my ($item, $tabtext, $pieces) = @_;
    w("\t<Page item=\"$item\">");
    w("\t\t<ScreenID>$item</ScreenID>");
    w("\t\t<RelativePosition>false</RelativePosition>");
    w("\t\t<Location><X>0</X><Y>$TAB_Y</Y></Location>");
    w("\t\t<Size><CX>$WIN_CX</CX><CY>$PAGE_CY</CY></Size>");
    w("\t\t<Style_VScroll>false</Style_VScroll>");
    w("\t\t<Style_HScroll>false</Style_HScroll>");
    w("\t\t<Style_Transparent>false</Style_Transparent>");
    w("\t\t<DrawTemplate>WDT_Def</DrawTemplate>");
    w("\t\t<TabText>$tabtext</TabText>");
    w("\t\t<TabTextColor><R>255</R><G>255</G><B>255</B></TabTextColor>");
    w("\t\t<TabTextActiveColor><R>255</R><G>255</G><B>0</B></TabTextActiveColor>");
    w("\t\t<Pieces>$_</Pieces>") for @$pieces;
    w("\t</Page>");
    w('');
}

page('ASC_ChoosePage', 'Choose', \@pieces);
page('ASC_KnownPage',  'Known',  \@known_pieces);
page('ASC_PoolPage',   'Pool',   \@pool_pieces);

w("\t<TabBox item=\"ASC_Tabs\">");
w("\t\t<ScreenID>ASC_Tabs</ScreenID>");
w("\t\t<RelativePosition>true</RelativePosition>");
w("\t\t<Location><X>0</X><Y>0</Y></Location>");
w("\t\t<Size><CX>$WIN_CX</CX><CY>$WIN_CY</CY></Size>");
w("\t\t<TabBorderTemplate>FT_DefTabBorder</TabBorderTemplate>");
w("\t\t<PageBorderTemplate>FT_DefPageBorder</PageBorderTemplate>");
w("\t\t<Pages>ASC_ChoosePage</Pages>");
w("\t\t<Pages>ASC_KnownPage</Pages>");
w("\t\t<Pages>ASC_PoolPage</Pages>");
w("\t</TabBox>");
w('');

w("\t<Screen item=\"AoTSpellChoiceWnd\">");
w("\t\t<RelativePosition>false</RelativePosition>");
w("\t\t<Location><X>300</X><Y>150</Y></Location>");
w("\t\t<Size><CX>$WIN_CX</CX><CY>$WIN_CY</CY></Size>");
w("\t\t<Text>Spells</Text>");
w("\t\t<Style_Transparent>false</Style_Transparent>");
w("\t\t<DrawTemplate>WDT_Def</DrawTemplate>");
w("\t\t<Style_Titlebar>true</Style_Titlebar>");
w("\t\t<Style_Closebox>true</Style_Closebox>");
w("\t\t<Style_Border>true</Style_Border>");
w("\t\t<Style_Sizable>false</Style_Sizable>");
w("\t\t<Escapable>true</Escapable>");
# ⚠️ The screen now holds ONLY the TabBox. Every other piece belongs to a page; listing one here as
# well would place it twice and it would draw outside the tab it belongs to.
w("\t\t<Pieces>ASC_Tabs</Pieces>");
w("\t</Screen>");
w('</XML>');

my $path = "/src/aotv4_client_install/uifiles_default/EQUI_AoTSpellChoiceWnd.xml";
open(my $fh, '>', $path) or die "$path: $!";
print $fh join("\n", @out), "\n";
close $fh;
printf "wrote %s: %d lines, %d icons, %d pieces\n", $path, scalar(@out), scalar(@ICONS), scalar(@pieces);
