-- AoTv4 -- Delve difficulty MODES + the end-of-delve BOSS step.            2026-07-30
-- ============================================================================================
-- Adds six parallel difficulty modes over the same six Dragons of Norrath zones, and gives every
-- delve a second objective: once the trash goal is met, a boss appears and must be killed.
--
-- ⚠️⚠️ THIS SCRIPT OWNS EVERY DELVE TASK, 2000300-2000359 -- INCLUDING THE STANDARD FAMILY that
-- `aotv4_dungeon.sql` originally created. It supersedes the `tasks` / `task_activities` block in that
-- file, because the boss step has to be added to Standard too and split ownership between two scripts
-- would mean whichever ran last silently won. Run THIS one after it. The rest of aotv4_dungeon.sql
-- (the chest npc, the zone rows) is untouched and still owned there.
--
-- ⚠️⚠️ EACH MODE NEEDS ITS OWN TASK ROWS AND THAT IS NOT AVOIDABLE. `task_activities.goalcount` and
-- `tasks.duration` are STATIC COLUMNS -- nothing changes a kill target or a timer at runtime. A mode
-- that alters either can only be expressed as a different task row, so the task id is
-- `<zone base> + <mode offset>`:
--     +0  Standard    +10 Hard    +20 Swarm    +30 Gauntlet    +40 Onslaught    +50 Fragile
-- Keep those offsets in step with `M.MODES.taskoff` in lua_modules/aotv4_dungeon.lua -- a mismatch
-- means AssignTask silently targets a task that does not exist and the player gets no journal entry.
--
-- ⚠️ Tasks and activities are loaded by the ZONE at boot, not from shared memory, so this needs a
-- zone restart and NOT ./shared_memory. The boss npc_types row is the same -- zone restart only.
-- ============================================================================================

-- ---------------------------------------------------------------- the boss
-- ⚠️ ONE npc type, randomised at spawn by Lua -- not a pool of rows. `task_activities.npc_match_list`
-- is static, so the task can only match a fixed id; the variety has to come from what Lua does to the
-- spawned mob (name, appearance, stats), never from picking a different row.
--
-- ⚠️ THE NAME MUST KEEP ITS LEADING '#'. That is not decoration: the score sheet decides "named"
-- with the same heuristic as §17c and quest_difficulty.pl -- EQ trash is lowercase, named mobs are
-- proper nouns or lead with '#' -- and a named kill is worth 3x in M.kill_value. Rename it to
-- something lowercase and every boss silently scores as trash.
--
-- ⚠️ Cloned VIA A TEMP TABLE so all ~100 npc_types columns stay byte-identical to a real named mob.
-- Never hand-list the columns; that is how `aggro_spell_id` (which does not exist on this schema)
-- got into an earlier pass of aotv4_dungeon.sql.
DROP TEMPORARY TABLE IF EXISTS tmp_delve_boss;
CREATE TEMPORARY TABLE tmp_delve_boss AS SELECT * FROM npc_types WHERE id = 119170;

UPDATE tmp_delve_boss SET
    id          = 2000301,
    name        = '#a_delve_warden',
    lastname    = 'Delve Warden',
    level       = 1,          -- scaled at spawn; this is only a floor
    hp          = 1000,       -- ditto: ModifyNPCStat rewrites it per run
    size        = 8,
    runspeed    = 1.25,       -- faster than trash so it closes; not so fast it cannot be kited
    npc_faction_id = 0,
    loottable_id   = 0,       -- loot is out of scope; the chest is the reward
    merchant_id    = 0;

DELETE FROM npc_types WHERE id = 2000301;
INSERT INTO npc_types SELECT * FROM tmp_delve_boss;
DROP TEMPORARY TABLE tmp_delve_boss;

-- ---------------------------------------------------------------- mode / zone definition tables
-- The 36 tasks and 72 activities are generated by cross joining these two, rather than written out:
-- hand-listing them is how the goalcount ladder and the mode offsets drift apart.
DROP TEMPORARY TABLE IF EXISTS tmp_delve_mode;
CREATE TEMPORARY TABLE tmp_delve_mode (
    moff      INT,            -- task id offset; must match M.MODES.taskoff
    mname     VARCHAR(32),
    goalmul   DECIMAL(5,2),   -- multiplies the zone's base trash count
    bosses    INT,            -- goalcount of the boss activity
    dur       INT             -- tasks.duration; only Onslaught differs
);
INSERT INTO tmp_delve_mode VALUES
    ( 0, 'Standard',  1.00, 1, 21600),
    (10, 'Hard',      1.00, 1, 21600),
    (20, 'Swarm',     3.00, 1, 21600),
    (30, 'Gauntlet',  0.34, 3, 21600),
    -- ⚠️ Onslaught's ENTIRE mechanic is this duration column. 1800s = 30 minutes; when it expires the
    -- engine fails the task and global_player's event_task_fail ends the run. No code, no timer of
    -- our own -- which is exactly why a timed mode was worth including.
    (40, 'Onslaught', 1.00, 1,  1800),
    (50, 'Fragile',   1.00, 1, 21600);

DROP TEMPORARY TABLE IF EXISTS tmp_delve_zone;
CREATE TEMPORARY TABLE tmp_delve_zone (
    base      INT,            -- the Standard task id for this zone
    zoneid    INT,
    zname     VARCHAR(64),
    goal      INT,            -- base trash count; climbs with the zone
    tgt       VARCHAR(64),
    descr     VARCHAR(255),
    emote     VARCHAR(255)
);
INSERT INTO tmp_delve_zone VALUES
    (2000300, 341, 'Lavaspinner''s Lair', 30, 'the lair''s defenders',
     'The lavaspinners have overrun the lair. Cut them down, then face what they were guarding.',
     'The lair falls silent. Something glitters where the last of them dropped.'),
    (2000301, 342, 'Tirranun''s Delve',   35, 'Tirranun''s brood',
     'Tirranun''s brood has grown bold in the deep. Thin them out, then face what they answer to.',
     'The delve goes quiet. Something glitters where the last of them dropped.'),
    (2000302, 338, 'Stillmoon Temple',    40, 'the temple guardians',
     'The temple guardians no longer answer to anyone. Put them down, then face their keeper.',
     'The temple stills. Something glitters where the last of them dropped.'),
    (2000303, 339, 'Stillmoon Ascent',    45, 'the ascent''s wardens',
     'Cut a path up the ascent, then face what waits at the top of it.',
     'The ascent falls quiet. Something glitters where the last of them dropped.'),
    (2000304, 340, 'Thundercrest Isles',  50, 'the storm drakes',
     'The storm drakes rule the isles unchallenged. Break them, then face the one that leads them.',
     'The storm passes. Something glitters where the last of them dropped.'),
    (2000305, 343, 'The Nest',            60, 'the brood of the Nest',
     'The Nest is thick with brood. Clear it out, then face what has been feeding them.',
     'The Nest goes still. Something glitters where the last of them dropped.');

-- ---------------------------------------------------------------- tasks
-- ⚠️ The cleanup DELETE names ONLY 2000300-2000359, the range this script itself creates. That rule
-- exists because aotv4_moonfire_line.sql once swept 43318-43323 -- six spells belonging to another
-- script -- with no error (§5). 2000359 is the top of the six mode families, not a round number.
DELETE FROM task_activities WHERE taskid BETWEEN 2000300 AND 2000359;
DELETE FROM tasks          WHERE id     BETWEEN 2000300 AND 2000359;

INSERT INTO tasks
  (id, type, duration, duration_code, title, description, reward_text, reward_id_list,
   cash_reward, exp_reward, reward_method, reward_points, min_level, max_level, level_spread,
   min_players, max_players, repeatable, faction_reward, completion_emote, enabled)
SELECT
    z.base + m.moff,
    0,
    m.dur,
    3,
    -- ⚠️ Standard carries NO mode suffix, so its title is byte-identical to what it has always been.
    -- The other five are tagged, because a player running three modes on one zone otherwise cannot
    -- tell which journal entry is which.
    CONCAT('Delve: ', z.zname, CASE WHEN m.moff = 0 THEN '' ELSE CONCAT(' (', m.mname, ')') END),
    z.descr,
    'A reward chest, and a Delver''s Sigil for your first delve', '', 0, 0, 0, 0,
    1, 200, 0, 1, 6, 1, 0,
    z.emote, 1
FROM tmp_delve_zone z CROSS JOIN tmp_delve_mode m;

-- ---------------------------------------------------------------- activity 0: the trash
-- ⚠️ AN EMPTY npc_match_list MATCHES EVERY NPC -- the mechanic, not an oversight
-- (task_client_state.cpp:528 wraps the whole name test in `if (!npc_match_list.empty() && ...)`).
-- ⚠️ `zones` is the BASE zone id; instances keep it, so one activity row serves every instance.
INSERT INTO task_activities
  (taskid, activityid, step, activitytype, target_name, goalmethod, goalcount,
   description_override, npc_match_list, item_id_list, zones, optional)
SELECT
    z.base + m.moff, 0, 1, 2, z.tgt, 0,
    -- ⚠️ GREATEST(...,1): Gauntlet's 0.34 multiplier must never round a zone down to a goal of zero,
    -- which would complete the trash step instantly and skip straight to the bosses.
    GREATEST(ROUND(z.goal * m.goalmul), 1),
    '', '', '', z.zoneid, 0
FROM tmp_delve_zone z CROSS JOIN tmp_delve_mode m;

-- ---------------------------------------------------------------- activity 1: the boss
-- ⚠️ step 2, so the task system only opens it once the trash goal is met -- that ordering is native
-- and is why no Lua is needed to gate the boss objective; Lua only has to SPAWN the thing, off
-- event_task_stage_complete for activity 0.
-- ⚠️ npc_match_list is the boss npc id as TEXT. It matches on npc_type id, which is why the boss has
-- to be one fixed row (see the boss note at the top).
-- ⚠️ No `zones` restriction needed beyond the same base zone id; the boss only ever exists inside a
-- delve instance because nothing else spawns it.
INSERT INTO task_activities
  (taskid, activityid, step, activitytype, target_name, goalmethod, goalcount,
   description_override, npc_match_list, item_id_list, zones, optional)
SELECT
    z.base + m.moff, 1, 2, 2,
    CASE WHEN m.bosses > 1 THEN 'the delve wardens' ELSE 'the delve warden' END,
    0, m.bosses,
    CASE WHEN m.bosses > 1
         THEN 'Defeat the wardens of the delve'
         ELSE 'Defeat the warden of the delve' END,
    '2000301', '', z.zoneid, 0
FROM tmp_delve_zone z CROSS JOIN tmp_delve_mode m;

DROP TEMPORARY TABLE tmp_delve_mode;
DROP TEMPORARY TABLE tmp_delve_zone;

-- ---------------------------------------------------------------- verify
SELECT 'tasks'      AS what, COUNT(*) AS n FROM tasks          WHERE id     BETWEEN 2000300 AND 2000359
UNION ALL
SELECT 'activities', COUNT(*)              FROM task_activities WHERE taskid BETWEEN 2000300 AND 2000359
UNION ALL
SELECT 'boss npc',   COUNT(*)              FROM npc_types       WHERE id = 2000301;
-- expected: tasks 36, activities 72, boss npc 1
