-- AoTv4 -- delete the retired custom reward set, spells 43000-43112 (113 rows).
-- =================================================================================================
-- This is the 113-spell custom ability set (Ember, Zap, Smolder, Kick, Strike, Counterattack,
-- Moonfire...) generated by custom/spells/gen_spells.py and renumbered 50xxx -> 43xxx. It was
-- RETIRED FROM THE POOL on 2026-07-27 (CLAUDE.md section 20) because it proved mostly redundant with
-- native spells, and because being all-slots-254 marker rows it renders as "no effects" in any
-- client-side description. Only the OFFERING stopped then; the rows stayed. This removes them.
--
-- ⚠️⚠️ THE 43xxx BAND IS NOT HOMOGENEOUS AND THIS SCRIPT DELETES ONLY 43000-43112. Everything from
-- 43150 up is live or still referenced, and deleting the range wholesale would destroy all four AA
-- trees, Shield Wall, the pet wards, the class auras and every spell rank:
--     43150-43199  helpers (11 rows)      -- see the orphan note below
--     43300-43349  custom spell lines     (28)  reptile, sloth, moonfire, promised, kindred, mark, thirst
--     43350-43399  their triggers + Shield Wall buffs (31)
--     43400-43454  AA-tree buffs and pet wards      (38)
--     43500-43565  class auras                      (32)
--     43576-44327  spell ranks Rk. II-V             (752)
--
-- ⚠️ VERIFIED SAFE BEFORE DELETION (2026-08-01):
--   * 0 of them appear in the offerable pool (spell_pool.lua) or the blacklist
--   * 0 are referenced by any other spell (recourse, trigger, effect_base_value, effect_limit_value)
--   * 0 are referenced by aa_rank_effects or aa_ranks.spell
--   * 0 appear in spell_desc.lua / spell_icons.lua / spell_ranks.lua
--
-- ⚠️⚠️ 42 STOCK ITEMS DO REFERENCE THEM, AND THAT IS EXPECTED -- LEAVE THOSE ITEMS ALONE.
-- The 50xxx -> 43xxx renumber landed on top of ids stock EQ already used, so items 143000+
-- ("Tome: Breather", "Tome: Cyclone Roar", "Tome: Insult", "Tome: Warrior's Bulwark" ...) carry a
-- `scrolleffect` pointing into this band. Those stock disciplines were overwritten and no longer
-- exist anywhere in spells_new -- checked by name. The tomes are UNOBTAINABLE here (0 rows in
-- lootdrop_entries, 0 on any merchant; they are level 70+ content behind a Classic expansion lock
-- and a level 30 cap), so the collision has never been reachable. After this script they point at
-- nothing instead of pointing at the wrong spell, which is strictly better. Do not "fix" them by
-- deleting the items: they are stock rows, and a future expansion unlock is the time to reconsider.
--
-- ⚠️ THE 11 HELPERS AT 43150-43199 ARE NOW ORPHANED, AND ARE DELIBERATELY LEFT IN PLACE.
-- 43150 (Open Wounds mark) was applied by 43052 and 43155 (Duel lock) by 43030 -- both in the 113 --
-- so nothing applies them any more. Their scripts and the lua_modules/aotv4_reactions.lua code that
-- reads them still work; they simply never fire. Removing them is a separate decision.
--
-- ⚠️⚠️ `spells_new` IS IN SHARED MEMORY. World down -> ./shared_memory -> restart. A zone restart is
-- NOT enough, and running this without the rebuild leaves the zones serving the old mmap, which
-- looks exactly like the script having done nothing.
--
-- Companion Lua removal (same change, 2026-08-01):
--   deleted  lua_modules/aotv4_pets.lua, lua_modules/aotv4_summon_table.lua
--   deleted  quests/global/spells/{43010,43011,43015,43017,43025,43027,43028,43030,43035,
--                                  43052,43054,43055,43056,43059}.lua
--   edited   global/global_player.lua  (pets require, the repeating "aotpet" timer, its branch)
--   edited   global/global_npc.lua     (pets require, on_pet_spawn, the whole event_damage_given)
--   edited   lua_modules/aotv4_reactions.lua (4 reaction branches + their state and tuning)
--
-- Restore: custom/sql/aotv4_custom_spells_backup.sql holds all 202 original custom rows, and
-- peq_pre_43xxx_purge.sql.gz is a targeted dump of 43000-43199 taken immediately before this ran.
-- ⚠️ Re-runnable. The DELETE names only the ids this script owns -- never widen it (CLAUDE.md
-- section 5 records a near-miss where a cleanup DELETE silently swept up another script's line).

SELECT COUNT(*) AS before_delete FROM spells_new WHERE id BETWEEN 43000 AND 43112;

DELETE FROM spells_new WHERE id BETWEEN 43000 AND 43112;

-- ---------------------------------------------------------------- verify
SELECT 'deleted 43000-43112'  AS what, COUNT(*) AS remaining FROM spells_new WHERE id BETWEEN 43000 AND 43112
UNION ALL SELECT 'helpers 43150-43199 (kept)',   COUNT(*) FROM spells_new WHERE id BETWEEN 43150 AND 43199
UNION ALL SELECT 'custom lines 43300-43349',     COUNT(*) FROM spells_new WHERE id BETWEEN 43300 AND 43349
UNION ALL SELECT 'triggers 43350-43399',         COUNT(*) FROM spells_new WHERE id BETWEEN 43350 AND 43399
UNION ALL SELECT 'AA buffs 43400-43454',         COUNT(*) FROM spells_new WHERE id BETWEEN 43400 AND 43454
UNION ALL SELECT 'class auras 43500-43565',      COUNT(*) FROM spells_new WHERE id BETWEEN 43500 AND 43565
UNION ALL SELECT 'spell ranks 43576-44327',      COUNT(*) FROM spells_new WHERE id BETWEEN 43576 AND 44327;
