-- GENERATED by gen_hunter_god_oow.sh from our DB's #-named mobs. Do not hand-edit; regenerate.
-- GoD/OoW Hunter achievements (categories 3307/3308). npc_name_kill objectives, earnable (mobs spawn here).

INSERT INTO custom_achievements (id,category_id,slug,name,description,points,hidden,enabled,sort_order,created_at) VALUES
  (330701,3307,'hunter-330701','Hunter of Natimbi, the Broken Shores','Defeat the named creatures dwelling here.',20,0,1,330701,1785000000)
  ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),description=VALUES(description),points=VALUES(points),enabled=VALUES(enabled);
DELETE FROM custom_achievement_objectives WHERE achievement_id=330701;
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000000,330701,0,'npc_name_kill','npc_name',280080,'cragbeast queen',1,280,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000001,330701,1,'npc_name_kill','npc_name',280074,'kemik arulon',1,280,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000002,330701,2,'npc_name_kill','npc_name',280066,'madronoa',1,280,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000003,330701,3,'npc_name_kill','npc_name',280070,'an enticing potameid',1,280,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000004,330701,4,'npc_name_kill','npc_name',280075,'kyv heartpiercer',1,280,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000005,330701,5,'npc_name_kill','npc_name',280081,'tumia lehio',1,280,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000006,330701,6,'npc_name_kill','npc_name',280076,'a fierce cragwalker',1,280,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000007,330701,7,'npc_name_kill','npc_name',280079,'duara yuenki',1,280,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000008,330701,8,'npc_name_kill','npc_name',280077,'a swift scavenger',1,280,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000009,330701,9,'npc_name_kill','npc_name',280073,'whiahdi',1,280,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000010,330701,10,'npc_name_kill','npc_name',280078,'vimidon',1,280,0);

INSERT INTO custom_achievements (id,category_id,slug,name,description,points,hidden,enabled,sort_order,created_at) VALUES
  (330702,3307,'hunter-330702','Hunter of Qinimi, Court of Nihilia','Defeat the named creatures dwelling here.',20,0,1,330702,1785000000)
  ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),description=VALUES(description),points=VALUES(points),enabled=VALUES(enabled);
DELETE FROM custom_achievement_objectives WHERE achievement_id=330702;
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000011,330702,0,'npc_name_kill','npc_name',281118,'pixtt tixxrt kvrok',1,281,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000012,330702,1,'npc_name_kill','npc_name',281122,'trixxrt`s guardsman',1,281,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000013,330702,2,'npc_name_kill','npc_name',281077,'pixtt xictic krvne ',1,281,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000014,330702,3,'npc_name_kill','npc_name',281133,'rav krixt tekrik',1,281,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000015,330702,4,'npc_name_kill','npc_name',281120,'a chamber guardian',1,281,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000016,330702,5,'npc_name_kill','npc_name',281135,'pixtt kerxek vket',1,281,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000017,330702,6,'npc_name_kill','npc_name',281134,'pixtt krakt ticov',1,281,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000018,330702,7,'npc_name_kill','npc_name',281103,'pixtt trext rexi',1,281,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000019,330702,8,'npc_name_kill','npc_name',281132,'rav tirdox ikveok',1,281,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000020,330702,9,'npc_name_kill','npc_name',281137,'rker the penmaster',1,281,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000021,330702,10,'npc_name_kill','npc_name',281051,'councilman sislono nislan',1,281,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000022,330702,11,'npc_name_kill','npc_name',281038,'councilman tentric',1,281,0);

INSERT INTO custom_achievements (id,category_id,slug,name,description,points,hidden,enabled,sort_order,created_at) VALUES
  (330703,3307,'hunter-330703','Hunter of Riwwi, Coliseum of Games','Defeat the named creatures dwelling here.',20,0,1,330703,1785000000)
  ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),description=VALUES(description),points=VALUES(points),enabled=VALUES(enabled);
DELETE FROM custom_achievement_objectives WHERE achievement_id=330703;
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000023,330703,0,'npc_name_kill','npc_name',282058,'pixtt kekken',1,282,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000024,330703,1,'npc_name_kill','npc_name',282057,'pixtt uxnikk',1,282,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000025,330703,2,'npc_name_kill','npc_name',282096,'officiator keviazh',1,282,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000026,330703,3,'npc_name_kill','npc_name',282107,'dedgerex',1,282,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000027,330703,4,'npc_name_kill','npc_name',282113,'reluctant gladiator',1,282,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000028,330703,5,'npc_name_kill','npc_name',282106,'viqu the blindeye',1,282,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000029,330703,6,'npc_name_kill','npc_name',282114,'chef vuzcv',1,282,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000030,330703,7,'npc_name_kill','npc_name',282110,'pixxt hihkx',1,282,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000031,330703,8,'npc_name_kill','npc_name',282111,'pixxt kihkx',1,282,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000032,330703,9,'npc_name_kill','npc_name',282112,'ra`tuk hrux vekxit',1,282,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000033,330703,10,'npc_name_kill','npc_name',282049,'namosa bubundu',1,282,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000034,330703,11,'npc_name_kill','npc_name',282097,'an enslaved yunjo',1,282,0);

INSERT INTO custom_achievements (id,category_id,slug,name,description,points,hidden,enabled,sort_order,created_at) VALUES
  (330704,3307,'hunter-330704','Hunter of Ferubi, Forgotten Temple of Taelosia','Defeat the named creatures dwelling here.',20,0,1,330704,1785000000)
  ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),description=VALUES(description),points=VALUES(points),enabled=VALUES(enabled);
DELETE FROM custom_achievement_objectives WHERE achievement_id=330704;
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000035,330704,0,'npc_name_kill','npc_name',284074,'smith rondo',1,284,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000036,330704,1,'npc_name_kill','npc_name',284100,'pxet vzanki kzan',1,284,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000037,330704,2,'npc_name_kill','npc_name',284102,'rav hunter',1,284,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000038,330704,3,'npc_name_kill','npc_name',284101,'rav ptvin',1,284,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000039,330704,4,'npc_name_kill','npc_name',284106,'mage trap',1,284,0);

INSERT INTO custom_achievements (id,category_id,slug,name,description,points,hidden,enabled,sort_order,created_at) VALUES
  (330705,3307,'hunter-330705','Hunter of the Sewers of Nihilia','Defeat the named creatures dwelling here.',20,0,1,330705,1785000000)
  ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),description=VALUES(description),points=VALUES(points),enabled=VALUES(enabled);
DELETE FROM custom_achievement_objectives WHERE achievement_id=330705;
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000040,330705,0,'npc_name_kill','npc_name',286100,'blistering larva',1,286,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000041,330705,1,'npc_name_kill','npc_name',286102,'rigara the lost',1,286,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000042,330705,2,'npc_name_kill','npc_name',286101,'sludgeeating fly',1,286,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000043,330705,3,'npc_name_kill','npc_name',287142,'kril v`lak',1,287,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000044,330705,4,'npc_name_kill','npc_name',287143,'ukun packleader',1,287,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000045,330705,5,'npc_name_kill','npc_name',287141,'grimy turepta',1,287,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000046,330705,6,'npc_name_kill','npc_name',288079,'diseased larva',1,288,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000047,330705,7,'npc_name_kill','npc_name',285082,'festering sewer gnat',1,285,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000048,330705,8,'npc_name_kill','npc_name',288076,'sewage slime',1,288,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000049,330705,9,'npc_name_kill','npc_name',288080,'slime devourer',1,288,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000050,330705,10,'npc_name_kill','npc_name',285083,'xthid the undying',1,285,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000051,330705,11,'npc_name_kill','npc_name',288078,'cryxtetl',1,288,0);

INSERT INTO custom_achievements (id,category_id,slug,name,description,points,hidden,enabled,sort_order,created_at) VALUES
  (330706,3307,'hunter-330706','Hunter of Barindu, the Hanging Gardens','Defeat the named creatures dwelling here.',20,0,1,330706,1785000000)
  ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),description=VALUES(description),points=VALUES(points),enabled=VALUES(enabled);
DELETE FROM custom_achievement_objectives WHERE achievement_id=330706;
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000052,330706,0,'npc_name_kill','npc_name',283163,'aneuk overseer',1,283,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000053,330706,1,'npc_name_kill','npc_name',283050,'ikaav ixvet pox',1,283,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000054,330706,2,'npc_name_kill','npc_name',283018,'mastruq utk hykat',1,283,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000055,330706,3,'npc_name_kill','npc_name',283159,'kyv rux vhedt',1,283,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000056,330706,4,'npc_name_kill','npc_name',283160,'ra`tuk kjyt gykk',1,283,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000057,330706,5,'npc_name_kill','npc_name',283161,'frenzied noc corpsethrasher',1,283,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000058,330706,6,'npc_name_kill','npc_name',283149,'a controlled earth churner',1,283,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000059,330706,7,'npc_name_kill','npc_name',283054,'apprentice udranda',1,283,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000060,330706,8,'npc_name_kill','npc_name',283101,'taiandao',1,283,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000061,330706,9,'npc_name_kill','npc_name',283056,'high priest diru riwirn',1,283,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000062,330706,10,'npc_name_kill','npc_name',283087,'njanu dinari',1,283,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000063,330706,11,'npc_name_kill','npc_name',283055,'gamesh',1,283,0);

INSERT INTO custom_achievements (id,category_id,slug,name,description,points,hidden,enabled,sort_order,created_at) VALUES
  (330707,3307,'hunter-330707','Hunter of Vxed, the Crumbling Caverns','Defeat the named creatures dwelling here.',20,0,1,330707,1785000000)
  ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),description=VALUES(description),points=VALUES(points),enabled=VALUES(enabled);
DELETE FROM custom_achievement_objectives WHERE achievement_id=330707;
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000064,330707,0,'npc_name_kill','npc_name',290072,'vuranish xxuro',1,290,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000065,330707,1,'npc_name_kill','npc_name',290057,'chavoor the trickster',1,290,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000066,330707,2,'npc_name_kill','npc_name',290058,'ikaav firecaller',1,290,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000067,330707,3,'npc_name_kill','npc_name',290060,'kyv hunter',1,290,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000068,330707,4,'npc_name_kill','npc_name',290061,'misguided beludu creque',1,290,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000069,330707,5,'npc_name_kill','npc_name',290064,'ukun bloodbeast',1,290,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000070,330707,6,'npc_name_kill','npc_name',290063,'umbiki',1,290,0);

INSERT INTO custom_achievements (id,category_id,slug,name,description,points,hidden,enabled,sort_order,created_at) VALUES
  (330708,3307,'hunter-330708','Hunter of Kod''Taz, Broken Trial Grounds','Defeat the named creatures dwelling here.',20,0,1,330708,1785000000)
  ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),description=VALUES(description),points=VALUES(points),enabled=VALUES(enabled);
DELETE FROM custom_achievement_objectives WHERE achievement_id=330708;
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000071,330708,0,'npc_name_kill','npc_name',293192,'cragbeast rager',1,293,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000072,330708,1,'npc_name_kill','npc_name',293198,'hexxt warmonger',1,293,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000073,330708,2,'npc_name_kill','npc_name',293203,'pixtt neuromancer',1,293,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000074,330708,3,'npc_name_kill','npc_name',293206,'pixtt tyrannist',1,293,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000075,330708,4,'npc_name_kill','npc_name',293191,'controlled spirithunter',1,293,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000076,330708,5,'npc_name_kill','npc_name',293194,'hexxt bonegrinder',1,293,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000077,330708,6,'npc_name_kill','npc_name',293199,'hynid howler',1,293,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000078,330708,7,'npc_name_kill','npc_name',293189,'coerced tiv chanter',1,293,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000079,330708,8,'npc_name_kill','npc_name',293190,'constrained spiritscourge',1,293,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000080,330708,9,'npc_name_kill','npc_name',293193,'enslaved vrex zealot',1,293,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000081,330708,10,'npc_name_kill','npc_name',293195,'hexxt deathaim',1,293,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000082,330708,11,'npc_name_kill','npc_name',293196,'hexxt markmaker',1,293,0);

INSERT INTO custom_achievements (id,category_id,slug,name,description,points,hidden,enabled,sort_order,created_at) VALUES
  (330709,3307,'hunter-330709','Hunter of Yxtta, Pulpit of Exiles','Defeat the named creatures dwelling here.',20,0,1,330709,1785000000)
  ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),description=VALUES(description),points=VALUES(points),enabled=VALUES(enabled);
DELETE FROM custom_achievement_objectives WHERE achievement_id=330709;
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000083,330709,0,'npc_name_kill','npc_name',291113,'jerimo jiao',1,291,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000084,330709,1,'npc_name_kill','npc_name',291111,'pixtt suir mindrider',1,291,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000085,330709,2,'npc_name_kill','npc_name',291115,'primal arachnid',1,291,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000086,330709,3,'npc_name_kill','npc_name',291117,'primal insect',1,291,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000087,330709,4,'npc_name_kill','npc_name',291102,'primal reptile',1,291,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000088,330709,5,'npc_name_kill','npc_name',291123,'tqiv trusik fanatic',1,291,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000089,330709,6,'npc_name_kill','npc_name',291107,'mastered destroyer',1,291,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000090,330709,7,'npc_name_kill','npc_name',291122,'pixtt flamedirge',1,291,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000091,330709,8,'npc_name_kill','npc_name',291139,'pixtt ravager',1,291,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000092,330709,9,'npc_name_kill','npc_name',291093,'pixtt souleater',1,291,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000093,330709,10,'npc_name_kill','npc_name',291128,'a commanded guardian',1,291,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000094,330709,11,'npc_name_kill','npc_name',291121,'hexxt huntmaster',1,291,0);

INSERT INTO custom_achievements (id,category_id,slug,name,description,points,hidden,enabled,sort_order,created_at) VALUES
  (330710,3307,'hunter-330710','Hunter of Qvic, Prayer Grounds of Calling','Defeat the named creatures dwelling here.',20,0,1,330710,1785000000)
  ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),description=VALUES(description),points=VALUES(points),enabled=VALUES(enabled);
DELETE FROM custom_achievement_objectives WHERE achievement_id=330710;
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000095,330710,0,'npc_name_kill','npc_name',295140,'cynosure kvanjji',1,295,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000096,330710,1,'npc_name_kill','npc_name',295141,'hexxt pvin nki',1,295,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000097,330710,2,'npc_name_kill','npc_name',295142,'pixtt invi mal',1,295,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000098,330710,3,'npc_name_kill','npc_name',295143,'pixtt ttinq val',1,295,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000099,330710,4,'npc_name_kill','npc_name',295144,'vrex indra',1,295,0);

INSERT INTO custom_achievements (id,category_id,slug,name,description,points,hidden,enabled,sort_order,created_at) VALUES
  (330801,3308,'hunter-330801','Hunter of Dranik''s Scar','Defeat the named creatures dwelling here.',25,0,1,330801,1785000000)
  ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),description=VALUES(description),points=VALUES(points),enabled=VALUES(enabled);
DELETE FROM custom_achievement_objectives WHERE achievement_id=330801;
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000100,330801,0,'npc_name_kill','npc_name',302048,'grathnok gilforgan',1,302,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000101,330801,1,'npc_name_kill','npc_name',302038,'karsor the mad',1,302,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000102,330801,2,'npc_name_kill','npc_name',302065,'yerika sisslak',1,302,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000103,330801,3,'npc_name_kill','npc_name',302080,'kyv bowmaster',1,302,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000104,330801,4,'npc_name_kill','npc_name',302079,'kirspos the cruel',1,302,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000105,330801,5,'npc_name_kill','npc_name',302062,'kyv darkscout',1,302,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000106,330801,6,'npc_name_kill','npc_name',302064,'murkglider hiveguard',1,302,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000107,330801,7,'npc_name_kill','npc_name',302075,'scaleback',1,302,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000108,330801,8,'npc_name_kill','npc_name',302063,'fang',1,302,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000109,330801,9,'npc_name_kill','npc_name',302082,'noc bloodtusk',1,302,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000110,330801,10,'npc_name_kill','npc_name',302083,'noc razortusk',1,302,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000111,330801,11,'npc_name_kill','npc_name',302056,'ertalon the thrall',1,302,0);

INSERT INTO custom_achievements (id,category_id,slug,name,description,points,hidden,enabled,sort_order,created_at) VALUES
  (330802,3308,'hunter-330802','Hunter of Harbinger''s Spire','Defeat the named creatures dwelling here.',25,0,1,330802,1785000000)
  ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),description=VALUES(description),points=VALUES(points),enabled=VALUES(enabled);
DELETE FROM custom_achievement_objectives WHERE achievement_id=330802;
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000112,330802,0,'npc_name_kill','npc_name',335054,'taskmaster yarln',1,335,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000113,330802,1,'npc_name_kill','npc_name',335039,'a discordling stalker',1,335,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000114,330802,2,'npc_name_kill','npc_name',335025,'asus the quick',1,335,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000115,330802,3,'npc_name_kill','npc_name',335026,'builder gorb',1,335,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000116,330802,4,'npc_name_kill','npc_name',335049,'foreman guppu',1,335,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000117,330802,5,'npc_name_kill','npc_name',335050,'girplan architect',1,335,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000118,330802,6,'npc_name_kill','npc_name',335040,'karg the fiend',1,335,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000119,330802,7,'npc_name_kill','npc_name',335041,'varin deathclaw',1,335,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000120,330802,8,'npc_name_kill','npc_name',335038,'a discordling sneak',1,335,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000121,330802,9,'npc_name_kill','npc_name',335032,'retind oaln',1,335,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000122,330802,10,'npc_name_kill','npc_name',335052,'the prime mover',1,335,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000123,330802,11,'npc_name_kill','npc_name',335030,'inventor krang',1,335,0);

INSERT INTO custom_achievements (id,category_id,slug,name,description,points,hidden,enabled,sort_order,created_at) VALUES
  (330803,3308,'hunter-330803','Hunter of Dranik''s Hollows','Defeat the named creatures dwelling here.',25,0,1,330803,1785000000)
  ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),description=VALUES(description),points=VALUES(points),enabled=VALUES(enabled);
DELETE FROM custom_achievement_objectives WHERE achievement_id=330803;
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000124,330803,0,'npc_name_kill','npc_name',320026,'muridae the plagued',1,320,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000125,330803,1,'npc_name_kill','npc_name',320014,'inky murkglider',1,320,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000126,330803,2,'npc_name_kill','npc_name',320012,'silentpaw',1,320,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000127,330803,3,'npc_name_kill','npc_name',318039,'discordling hollower',1,318,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000128,330803,4,'npc_name_kill','npc_name',318038,'girplan pathmaker',1,318,0);

INSERT INTO custom_achievements (id,category_id,slug,name,description,points,hidden,enabled,sort_order,created_at) VALUES
  (330804,3308,'hunter-330804','Hunter of Nobles'' Causeway','Defeat the named creatures dwelling here.',25,0,1,330804,1785000000)
  ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),description=VALUES(description),points=VALUES(points),enabled=VALUES(enabled);
DELETE FROM custom_achievement_objectives WHERE achievement_id=330804;
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000129,330804,0,'npc_name_kill','npc_name',303078,'withering murkglider',1,303,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000130,330804,1,'npc_name_kill','npc_name',303009,'drarakon the mad',1,303,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000131,330804,2,'npc_name_kill','npc_name',303087,'stone thrower',1,303,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000132,330804,3,'npc_name_kill','npc_name',303034,'alkron wyrmsong',1,303,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000133,330804,4,'npc_name_kill','npc_name',303079,'bone cracker',1,303,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000134,330804,5,'npc_name_kill','npc_name',303115,'slavedriver menlo',1,303,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000135,330804,6,'npc_name_kill','npc_name',303002,'bazu scavenger',1,303,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000136,330804,7,'npc_name_kill','npc_name',303107,'grinbar the ancient',1,303,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000137,330804,8,'npc_name_kill','npc_name',303111,'guardian etrias',1,303,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000138,330804,9,'npc_name_kill','npc_name',303112,'guardian naven',1,303,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000139,330804,10,'npc_name_kill','npc_name',303067,'first placeholder',1,303,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000140,330804,11,'npc_name_kill','npc_name',303085,'jillaa oogblat',1,303,0);

INSERT INTO custom_achievements (id,category_id,slug,name,description,points,hidden,enabled,sort_order,created_at) VALUES
  (330805,3308,'hunter-330805','Hunter of The Bloodfields','Defeat the named creatures dwelling here.',25,0,1,330805,1785000000)
  ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),description=VALUES(description),points=VALUES(points),enabled=VALUES(enabled);
DELETE FROM custom_achievement_objectives WHERE achievement_id=330805;
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000141,330805,0,'npc_name_kill','npc_name',301035,'kragsmash',1,301,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000142,330805,1,'npc_name_kill','npc_name',301024,'caller donivin',1,301,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000143,330805,2,'npc_name_kill','npc_name',301032,'elite dragorn jekisia',1,301,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000144,330805,3,'npc_name_kill','npc_name',301037,'tormented scout',1,301,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000145,330805,4,'npc_name_kill','npc_name',301006,'clergyman rexith',1,301,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000146,330805,5,'npc_name_kill','npc_name',301054,'high priest wersin',1,301,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000147,330805,6,'npc_name_kill','npc_name',301053,'ikaav slumberer',1,301,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000148,330805,7,'npc_name_kill','npc_name',301061,'lieutenant lihad',1,301,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000149,330805,8,'npc_name_kill','npc_name',301051,'noc deathstalker',1,301,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000150,330805,9,'npc_name_kill','npc_name',301047,'the domineering ukun',1,301,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000151,330805,10,'npc_name_kill','npc_name',301058,'the heavy burdened golem',1,301,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000152,330805,11,'npc_name_kill','npc_name',301033,'a reclusive girplan',1,301,0);

INSERT INTO custom_achievements (id,category_id,slug,name,description,points,hidden,enabled,sort_order,created_at) VALUES
  (330806,3308,'hunter-330806','Hunter of Catacombs of Dranik','Defeat the named creatures dwelling here.',25,0,1,330806,1785000000)
  ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),description=VALUES(description),points=VALUES(points),enabled=VALUES(enabled);
DELETE FROM custom_achievement_objectives WHERE achievement_id=330806;
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000153,330806,0,'npc_name_kill','npc_name',328037,'shade of redis linrok',1,328,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000154,330806,1,'npc_name_kill','npc_name',328040,'dragorn marshal greshka',1,328,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000155,330806,2,'npc_name_kill','npc_name',329034,'elite overlord vijaz',1,329,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000156,330806,3,'npc_name_kill','npc_name',328041,'high enchantress zy`chia',1,328,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000157,330806,4,'npc_name_kill','npc_name',329035,'high sorceress vi`tara',1,329,0);

INSERT INTO custom_achievements (id,category_id,slug,name,description,points,hidden,enabled,sort_order,created_at) VALUES
  (330807,3308,'hunter-330807','Hunter of Sewers of Dranik','Defeat the named creatures dwelling here.',25,0,1,330807,1785000000)
  ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),description=VALUES(description),points=VALUES(points),enabled=VALUES(enabled);
DELETE FROM custom_achievement_objectives WHERE achievement_id=330807;
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000158,330807,0,'npc_name_kill','npc_name',332064,'nightfang glider',1,332,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000159,330807,1,'npc_name_kill','npc_name',332065,'silania janaid',1,332,0);

INSERT INTO custom_achievements (id,category_id,slug,name,description,points,hidden,enabled,sort_order,created_at) VALUES
  (330808,3308,'hunter-330808','Hunter of The Ruined City of Dranik','Defeat the named creatures dwelling here.',25,0,1,330808,1785000000)
  ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),description=VALUES(description),points=VALUES(points),enabled=VALUES(enabled);
DELETE FROM custom_achievement_objectives WHERE achievement_id=330808;
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000160,330808,0,'npc_name_kill','npc_name',336201,'murkglider breeder',1,336,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000161,330808,1,'npc_name_kill','npc_name',336141,'zun`muram volklana',1,336,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000162,330808,2,'npc_name_kill','npc_name',336214,'a cracked earthshaker',1,336,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000163,330808,3,'npc_name_kill','npc_name',336143,'bloated girplan',1,336,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000164,330808,4,'npc_name_kill','npc_name',336197,'bolno the peon',1,336,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000165,330808,5,'npc_name_kill','npc_name',336187,'ikaav slaveherder',1,336,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000166,330808,6,'npc_name_kill','npc_name',336228,'kyv bowhound',1,336,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000167,330808,7,'npc_name_kill','npc_name',336196,'mistress ujani',1,336,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000168,330808,8,'npc_name_kill','npc_name',336139,'reinad scalebreath',1,336,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000169,330808,9,'npc_name_kill','npc_name',336162,'souldrainer',1,336,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000170,330808,10,'npc_name_kill','npc_name',336137,'stoneworker stonetooth',1,336,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000171,330808,11,'npc_name_kill','npc_name',336136,'ukun fleshhunter',1,336,0);

INSERT INTO custom_achievements (id,category_id,slug,name,description,points,hidden,enabled,sort_order,created_at) VALUES
  (330809,3308,'hunter-330809','Hunter of Muramite Proving Grounds','Defeat the named creatures dwelling here.',25,0,1,330809,1785000000)
  ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),description=VALUES(description),points=VALUES(points),enabled=VALUES(enabled);
DELETE FROM custom_achievement_objectives WHERE achievement_id=330809;
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000172,330809,0,'npc_name_kill','npc_name',316034,'lightningcaller vhalek',1,316,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000173,330809,1,'npc_name_kill','npc_name',316046,'blind hunter rekamu',1,316,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000174,330809,2,'npc_name_kill','npc_name',316050,'cleaver wiex',1,316,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000175,330809,3,'npc_name_kill','npc_name',316022,'discordling enchainer kuroun',1,316,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000176,330809,4,'npc_name_kill','npc_name',316045,'miseryfiend ghio',1,316,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000177,330809,5,'npc_name_kill','npc_name',316060,'neuromancer vionne',1,316,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000178,330809,6,'npc_name_kill','npc_name',316056,'odiumate isienne',1,316,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000179,330809,7,'npc_name_kill','npc_name',316044,'sentinel siofet',1,316,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000180,330809,8,'npc_name_kill','npc_name',316052,'taskfiend caikap',1,316,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000181,330809,9,'npc_name_kill','npc_name',309037,'allaina deepeyes',1,309,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000182,330809,10,'npc_name_kill','npc_name',309029,'allionae ullui',1,309,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000183,330809,11,'npc_name_kill','npc_name',309041,'bavabwa steeltoe',1,309,0);

INSERT INTO custom_achievements (id,category_id,slug,name,description,points,hidden,enabled,sort_order,created_at) VALUES
  (330810,3308,'hunter-330810','Hunter of Wall of Slaughter','Defeat the named creatures dwelling here.',25,0,1,330810,1785000000)
  ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),description=VALUES(description),points=VALUES(points),enabled=VALUES(enabled);
DELETE FROM custom_achievement_objectives WHERE achievement_id=330810;
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000184,330810,0,'npc_name_kill','npc_name',300031,'cipheron',1,300,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000185,330810,1,'npc_name_kill','npc_name',300037,'girplan guardian',1,300,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000186,330810,2,'npc_name_kill','npc_name',300057,'herrian warfrost',1,300,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000187,330810,3,'npc_name_kill','npc_name',300066,'hulcror',1,300,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000188,330810,4,'npc_name_kill','npc_name',300094,'a gelidran spy',1,300,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000189,330810,5,'npc_name_kill','npc_name',300064,'dragorn nightwalker',1,300,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000190,330810,6,'npc_name_kill','npc_name',300063,'tarn icewind',1,300,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000191,330810,7,'npc_name_kill','npc_name',300042,'the murkglider hivequeen',1,300,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000192,330810,8,'npc_name_kill','npc_name',300069,'a mangled muramite captain',1,300,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000193,330810,9,'npc_name_kill','npc_name',300060,'chimera seether',1,300,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000194,330810,10,'npc_name_kill','npc_name',300061,'feran savageclaw',1,300,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000195,330810,11,'npc_name_kill','npc_name',300043,'pyrique redwing',1,300,0);

INSERT INTO custom_achievements (id,category_id,slug,name,description,points,hidden,enabled,sort_order,created_at) VALUES
  (330811,3308,'hunter-330811','Hunter of Riftseekers'' Sanctum','Defeat the named creatures dwelling here.',25,0,1,330811,1785000000)
  ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),description=VALUES(description),points=VALUES(points),enabled=VALUES(enabled);
DELETE FROM custom_achievement_objectives WHERE achievement_id=330811;
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000196,330811,0,'npc_name_kill','npc_name',334087,'craftmaster tieranu',1,334,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000197,330811,1,'npc_name_kill','npc_name',334041,'king gelaqua',1,334,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000198,330811,2,'npc_name_kill','npc_name',334049,'queen pyrilonis',1,334,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000199,330811,3,'npc_name_kill','npc_name',334014,'chailak',1,334,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000200,330811,4,'npc_name_kill','npc_name',334121,'channeler pyren',1,334,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000201,330811,5,'npc_name_kill','npc_name',334066,'discordling gemkeeper',1,334,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000202,330811,6,'npc_name_kill','npc_name',334093,'familiar venomtail',1,334,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000203,330811,7,'npc_name_kill','npc_name',334102,'feratha',1,334,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000204,330811,8,'npc_name_kill','npc_name',334088,'gelidran conjurer',1,334,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000205,330811,9,'npc_name_kill','npc_name',334076,'gelidran frostformer',1,334,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000206,330811,10,'npc_name_kill','npc_name',334105,'gelidran icekeeper',1,334,0);
INSERT INTO custom_achievement_objectives (id,achievement_id,objective_index,objective_type,target_type,target_id,target_name,required_count,zone_id,class_mask) VALUES (83000207,330811,11,'npc_name_kill','npc_name',334020,'girplan stonesinger',1,334,0);

