-- AA names + descriptions. type 1 = title, type 4 = description (verified against Natural
-- Durability 107). The AA packet carries only the SID -- the CLIENT resolves it from its own
-- dbstr_us.txt, which is why title_sid = -1 renders NOTHING rather than falling back to a name.
DELETE FROM db_str WHERE id BETWEEN 40000 AND 40005 AND type IN (1,4);
INSERT INTO db_str (id,type,value) VALUES
 (40000,1,'Shield Oath'),
 (40000,4,'Your defensive stance sharpens your blows and your presence. Increases melee damage by 4, 7, 10, 13 and 15 percent, and hate generated by 8, 12, 16, 20 and 25 percent.'),
 (40001,1,'Stonestride'),
 (40001,4,'Your footing turns aside the worst of a blow. Reduces the damage of each melee hit against you by 2, 4, 7, 10 and 14 points.'),
 (40002,1,'Unyielding'),
 (40002,4,'You are harder to land a blow upon. Increases your chance to avoid melee attacks by 2, 4, 6, 8 and 11.'),
 (40003,1,'Bloodied Bash'),
 (40003,4,'You drink from the wounds your shield opens. Bash and Slam heal you for 25, 40, 55, 70 and 85 percent of the damage they deal.'),
 (40004,1,'Bulwark'),
 (40004,4,'You bear a shared burden more easily. Reduces the additional damage taken when splitting a blow with allies through the shield command.'),
 (40005,1,'Aegis Reflex'),
 (40005,4,'Every blow your armour turns aside is remembered. Deflections build a reserve, and when a blow finally lands the reserve strengthens the next heal you receive by up to 10, 18, 28, 40 and 60 percent.');
-- point every rank of each ability at its ability-level strings
UPDATE aa_ranks r JOIN aa_ability a ON r.id BETWEEN a.first_rank_id AND a.first_rank_id+4
SET r.title_sid = a.id, r.desc_sid = a.id WHERE a.id BETWEEN 40000 AND 40005;
