-- Magician tier 1 -- Elemental Fist. GENERATED by custom/tools/gen_class_abilities.py.
-- ⚠️ The payload is aotv4_class_abilities.PAYLOAD[44736]; this file only routes to it.
-- ⚠️⚠️ THE SCRIPT RUNS **BEFORE** THE SPELL APPLIES ITS OWN EFFECTS (the event fires at
-- spell_effects.cpp:163, the slot loop starts at :225) -- and RETURNING NON-ZERO CANCELS
-- THEM. Never return a value from these handlers.
-- ⚠️⚠️ THE HANDLER IS `event_spell_effect`, WITH NO SUFFIX. LuaParser::ConvertLuaEvent
-- (lua_parser.cpp:1604) collapses EVENT_SPELL_EFFECT_BOT/_CLIENT/_NPC into one, and the
-- name table maps all of them to "event_spell_effect" (:104). Defining
-- event_spell_effect_client / _npc compiles, luachecks and is NEVER CALLED -- the spell
-- still plays its animation and applies its own SPAs, so the ability looks alive and does
-- nothing. That is exactly how all 48 of these shipped inert the first time.
local ab = require("aotv4_class_abilities")

function event_spell_effect(e) ab.fire(44736, e) end
