#pragma once

// core_fellowship -- native SIDL Fellowship window (AoTv4), opened by "/fellowship" or the AoT menu.
// =========================================================================================
// A 12-person social group with persistent cross-zone chat and a travellable campfire.
//
// ⚠️⚠️ THIS IS NOT THE CLIENT'S OWN FELLOWSHIP WINDOW, AND THAT ONE CANNOT BE MADE TO WORK. The
// client HAS it -- `pinstCFellowshipWnd` is mapped at 0xF712AC -- but server side
// `OP_FellowshipUpdate` is a NAME IN `emu_oplist.h` AND NOTHING ELSE: no handler in
// client_packet.cpp, no struct in eq_packet_structs.h, and NO MAPPING IN THE RoF2 PATCH, so it has
// no wire opcode for this client at all. Forcing the native window open shows an empty panel
// forever; populating it would mean reverse-engineering both the opcode number and the packet
// format with no reference. CLAUDE.md section 13 records the same dead end for the native trader
// window, which had MORE to work with than this does (a mapped opcode and a real activation path)
// and was still abandoned.
//
// ⚠️ SO THE LOOK IS COPIED INSTEAD OF THE PLUMBING. `EQUI_AoTFellowshipWnd.xml` is GENERATED by
// transforming the client's own EQUI_FellowshipWnd.xml -- every coordinate, size and template is
// byte for byte the native window's, with the screen renamed AoTFellowshipWnd and every piece
// prefixed AFW_ so it cannot collide. It is identical rather than similar because it IS the same
// layout.
//
// Its OWN translation unit, like core_advloot.cpp / core_autoskill.cpp / core_difficulty.cpp.
//
// It installs NO detours. This dll already owns dsp_chat, InterpretCmd and ProcessGameEvents, and
// two modules cannot hook the same address, so the existing detours call INTO the entry points
// below:
//
//   InitFellowship()            -- core_init.h (InitOptions), gated by areFellowshipWindowEnabled.
//   FellowshipParseTransport()  -- from the dsp_chat swallow chain. True if it ate an FSHIP* line.
//   FellowshipIsOurEcho()       -- true for the "/say fship*" echoes, so dsp_chat swallows them.
//   FellowshipShow()            -- "/fellowship" (core_bazaar.h) and the AoT menu button.
//   FellowshipOnUiReset()       -- from the CleanGameUI/ReloadUI detour core_achievements_native.cpp
//                                  owns; DELETES the window (nulling alone leaves it registered
//                                  with the window manager after its widgets are freed).
//
// Protocol (chat; the dll swallows all of it):
//   server -> dll : "FSHIPDATA <name>^leader|online|zone|charname^..."
//                   "FSHIPFIRE <zone>|<minutes>|<type>"      (empty zone = no fire burning)
//   dll -> server : "/say fshipreq"                 refresh
//                   "/say fshipform <name>"         create
//                   "/say fshipinv <name>"          invite (blank = your current target)
//                   "/say fshipkick <name>"         remove
//                   "/say fshipleader <name>"       hand over leadership
//                   "/say fshipleave"               leave
//                   "/say fshipend"                 disband (leader)
//                   "/say fshiplight <type>"        light a campfire here
//                   "/say fshipdouse"               put your campfire out
//                   "/say fshipgo"                  travel to the campfire
//                   "/say fshipmotd <text>"         set the message of the day
//
// ⚠️ The dll validates NOTHING. Every cap, permission and gate -- the 12 limit, leader-only actions,
// the four travel gates (region unlocked, not in combat, not in an instance, cooldown) -- is
// re-checked server side, so a modified client pressing a button gains only a refusal in chat.
//
// 📌 XP sharing is deliberately absent. The design declined it, so `AFW_ToggleExpSharingButton` is
// HIDDEN rather than left on screen doing nothing -- a live-looking button that silently does
// nothing reads as a broken window (the lesson CLAUDE.md section 16 records for AdvLoot's Loot
// button).

void InitFellowship();
bool FellowshipParseTransport(const char* message);
bool FellowshipIsOurEcho(const char* message);
void FellowshipShow();
void FellowshipOnUiReset();
